// Code generated by ent, DO NOT EDIT.

package enterprisememberbudgetperiod

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldLTE(FieldID, id))
}

// MemberID applies equality check predicate on the "member_id" field. It's identical to MemberIDEQ.
func MemberID(v int64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldEQ(FieldMemberID, v))
}

// PeriodStart applies equality check predicate on the "period_start" field. It's identical to PeriodStartEQ.
func PeriodStart(v time.Time) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldEQ(FieldPeriodStart, v))
}

// Timezone applies equality check predicate on the "timezone" field. It's identical to TimezoneEQ.
func Timezone(v string) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldEQ(FieldTimezone, v))
}

// UsedUsd applies equality check predicate on the "used_usd" field. It's identical to UsedUsdEQ.
func UsedUsd(v float64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldEQ(FieldUsedUsd, v))
}

// ReservedUsd applies equality check predicate on the "reserved_usd" field. It's identical to ReservedUsdEQ.
func ReservedUsd(v float64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldEQ(FieldReservedUsd, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldEQ(FieldVersion, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldEQ(FieldUpdatedAt, v))
}

// MemberIDEQ applies the EQ predicate on the "member_id" field.
func MemberIDEQ(v int64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldEQ(FieldMemberID, v))
}

// MemberIDNEQ applies the NEQ predicate on the "member_id" field.
func MemberIDNEQ(v int64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldNEQ(FieldMemberID, v))
}

// MemberIDIn applies the In predicate on the "member_id" field.
func MemberIDIn(vs ...int64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldIn(FieldMemberID, vs...))
}

// MemberIDNotIn applies the NotIn predicate on the "member_id" field.
func MemberIDNotIn(vs ...int64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldNotIn(FieldMemberID, vs...))
}

// PeriodStartEQ applies the EQ predicate on the "period_start" field.
func PeriodStartEQ(v time.Time) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldEQ(FieldPeriodStart, v))
}

// PeriodStartNEQ applies the NEQ predicate on the "period_start" field.
func PeriodStartNEQ(v time.Time) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldNEQ(FieldPeriodStart, v))
}

// PeriodStartIn applies the In predicate on the "period_start" field.
func PeriodStartIn(vs ...time.Time) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldIn(FieldPeriodStart, vs...))
}

// PeriodStartNotIn applies the NotIn predicate on the "period_start" field.
func PeriodStartNotIn(vs ...time.Time) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldNotIn(FieldPeriodStart, vs...))
}

// PeriodStartGT applies the GT predicate on the "period_start" field.
func PeriodStartGT(v time.Time) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldGT(FieldPeriodStart, v))
}

// PeriodStartGTE applies the GTE predicate on the "period_start" field.
func PeriodStartGTE(v time.Time) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldGTE(FieldPeriodStart, v))
}

// PeriodStartLT applies the LT predicate on the "period_start" field.
func PeriodStartLT(v time.Time) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldLT(FieldPeriodStart, v))
}

// PeriodStartLTE applies the LTE predicate on the "period_start" field.
func PeriodStartLTE(v time.Time) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldLTE(FieldPeriodStart, v))
}

// TimezoneEQ applies the EQ predicate on the "timezone" field.
func TimezoneEQ(v string) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldEQ(FieldTimezone, v))
}

// TimezoneNEQ applies the NEQ predicate on the "timezone" field.
func TimezoneNEQ(v string) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldNEQ(FieldTimezone, v))
}

// TimezoneIn applies the In predicate on the "timezone" field.
func TimezoneIn(vs ...string) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldIn(FieldTimezone, vs...))
}

// TimezoneNotIn applies the NotIn predicate on the "timezone" field.
func TimezoneNotIn(vs ...string) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldNotIn(FieldTimezone, vs...))
}

// TimezoneGT applies the GT predicate on the "timezone" field.
func TimezoneGT(v string) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldGT(FieldTimezone, v))
}

// TimezoneGTE applies the GTE predicate on the "timezone" field.
func TimezoneGTE(v string) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldGTE(FieldTimezone, v))
}

// TimezoneLT applies the LT predicate on the "timezone" field.
func TimezoneLT(v string) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldLT(FieldTimezone, v))
}

// TimezoneLTE applies the LTE predicate on the "timezone" field.
func TimezoneLTE(v string) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldLTE(FieldTimezone, v))
}

// TimezoneContains applies the Contains predicate on the "timezone" field.
func TimezoneContains(v string) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldContains(FieldTimezone, v))
}

// TimezoneHasPrefix applies the HasPrefix predicate on the "timezone" field.
func TimezoneHasPrefix(v string) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldHasPrefix(FieldTimezone, v))
}

// TimezoneHasSuffix applies the HasSuffix predicate on the "timezone" field.
func TimezoneHasSuffix(v string) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldHasSuffix(FieldTimezone, v))
}

// TimezoneEqualFold applies the EqualFold predicate on the "timezone" field.
func TimezoneEqualFold(v string) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldEqualFold(FieldTimezone, v))
}

// TimezoneContainsFold applies the ContainsFold predicate on the "timezone" field.
func TimezoneContainsFold(v string) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldContainsFold(FieldTimezone, v))
}

// UsedUsdEQ applies the EQ predicate on the "used_usd" field.
func UsedUsdEQ(v float64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldEQ(FieldUsedUsd, v))
}

// UsedUsdNEQ applies the NEQ predicate on the "used_usd" field.
func UsedUsdNEQ(v float64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldNEQ(FieldUsedUsd, v))
}

// UsedUsdIn applies the In predicate on the "used_usd" field.
func UsedUsdIn(vs ...float64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldIn(FieldUsedUsd, vs...))
}

// UsedUsdNotIn applies the NotIn predicate on the "used_usd" field.
func UsedUsdNotIn(vs ...float64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldNotIn(FieldUsedUsd, vs...))
}

// UsedUsdGT applies the GT predicate on the "used_usd" field.
func UsedUsdGT(v float64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldGT(FieldUsedUsd, v))
}

// UsedUsdGTE applies the GTE predicate on the "used_usd" field.
func UsedUsdGTE(v float64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldGTE(FieldUsedUsd, v))
}

// UsedUsdLT applies the LT predicate on the "used_usd" field.
func UsedUsdLT(v float64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldLT(FieldUsedUsd, v))
}

// UsedUsdLTE applies the LTE predicate on the "used_usd" field.
func UsedUsdLTE(v float64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldLTE(FieldUsedUsd, v))
}

// ReservedUsdEQ applies the EQ predicate on the "reserved_usd" field.
func ReservedUsdEQ(v float64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldEQ(FieldReservedUsd, v))
}

// ReservedUsdNEQ applies the NEQ predicate on the "reserved_usd" field.
func ReservedUsdNEQ(v float64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldNEQ(FieldReservedUsd, v))
}

// ReservedUsdIn applies the In predicate on the "reserved_usd" field.
func ReservedUsdIn(vs ...float64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldIn(FieldReservedUsd, vs...))
}

// ReservedUsdNotIn applies the NotIn predicate on the "reserved_usd" field.
func ReservedUsdNotIn(vs ...float64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldNotIn(FieldReservedUsd, vs...))
}

// ReservedUsdGT applies the GT predicate on the "reserved_usd" field.
func ReservedUsdGT(v float64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldGT(FieldReservedUsd, v))
}

// ReservedUsdGTE applies the GTE predicate on the "reserved_usd" field.
func ReservedUsdGTE(v float64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldGTE(FieldReservedUsd, v))
}

// ReservedUsdLT applies the LT predicate on the "reserved_usd" field.
func ReservedUsdLT(v float64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldLT(FieldReservedUsd, v))
}

// ReservedUsdLTE applies the LTE predicate on the "reserved_usd" field.
func ReservedUsdLTE(v float64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldLTE(FieldReservedUsd, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int64) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldLTE(FieldVersion, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasMember applies the HasEdge predicate on the "member" edge.
func HasMember() predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MemberTable, MemberColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMemberWith applies the HasEdge predicate on the "member" edge with a given conditions (other predicates).
func HasMemberWith(preds ...predicate.EnterpriseMember) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(func(s *sql.Selector) {
		step := newMemberStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EnterpriseMemberBudgetPeriod) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EnterpriseMemberBudgetPeriod) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EnterpriseMemberBudgetPeriod) predicate.EnterpriseMemberBudgetPeriod {
	return predicate.EnterpriseMemberBudgetPeriod(sql.NotPredicates(p))
}
