// Code generated by ent, DO NOT EDIT.

package enterprisemembergroupbinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// MemberID applies equality check predicate on the "member_id" field. It's identical to MemberIDEQ.
func MemberID(v int64) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldEQ(FieldMemberID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldEQ(FieldGroupID, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// MemberIDEQ applies the EQ predicate on the "member_id" field.
func MemberIDEQ(v int64) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldEQ(FieldMemberID, v))
}

// MemberIDNEQ applies the NEQ predicate on the "member_id" field.
func MemberIDNEQ(v int64) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldNEQ(FieldMemberID, v))
}

// MemberIDIn applies the In predicate on the "member_id" field.
func MemberIDIn(vs ...int64) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldIn(FieldMemberID, vs...))
}

// MemberIDNotIn applies the NotIn predicate on the "member_id" field.
func MemberIDNotIn(vs ...int64) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldNotIn(FieldMemberID, vs...))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldNotIn(FieldGroupID, vs...))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldLTE(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasMember applies the HasEdge predicate on the "member" edge.
func HasMember() predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, MemberColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, MemberTable, MemberColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMemberWith applies the HasEdge predicate on the "member" edge with a given conditions (other predicates).
func HasMemberWith(preds ...predicate.EnterpriseMember) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(func(s *sql.Selector) {
		step := newMemberStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, GroupColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EnterpriseMemberGroupBinding) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EnterpriseMemberGroupBinding) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EnterpriseMemberGroupBinding) predicate.EnterpriseMemberGroupBinding {
	return predicate.EnterpriseMemberGroupBinding(sql.NotPredicates(p))
}
