// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/enterprisemember"
	"github.com/Wei-Shaw/sub2api/ent/enterprisemembergroupbinding"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// EnterpriseMemberGroupBindingUpdate is the builder for updating EnterpriseMemberGroupBinding entities.
type EnterpriseMemberGroupBindingUpdate struct {
	config
	hooks    []Hook
	mutation *EnterpriseMemberGroupBindingMutation
}

// Where appends a list predicates to the EnterpriseMemberGroupBindingUpdate builder.
func (_u *EnterpriseMemberGroupBindingUpdate) Where(ps ...predicate.EnterpriseMemberGroupBinding) *EnterpriseMemberGroupBindingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMemberID sets the "member_id" field.
func (_u *EnterpriseMemberGroupBindingUpdate) SetMemberID(v int64) *EnterpriseMemberGroupBindingUpdate {
	_u.mutation.SetMemberID(v)
	return _u
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (_u *EnterpriseMemberGroupBindingUpdate) SetNillableMemberID(v *int64) *EnterpriseMemberGroupBindingUpdate {
	if v != nil {
		_u.SetMemberID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *EnterpriseMemberGroupBindingUpdate) SetGroupID(v int64) *EnterpriseMemberGroupBindingUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *EnterpriseMemberGroupBindingUpdate) SetNillableGroupID(v *int64) *EnterpriseMemberGroupBindingUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *EnterpriseMemberGroupBindingUpdate) SetSortOrder(v int) *EnterpriseMemberGroupBindingUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *EnterpriseMemberGroupBindingUpdate) SetNillableSortOrder(v *int) *EnterpriseMemberGroupBindingUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *EnterpriseMemberGroupBindingUpdate) AddSortOrder(v int) *EnterpriseMemberGroupBindingUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnterpriseMemberGroupBindingUpdate) SetUpdatedAt(v time.Time) *EnterpriseMemberGroupBindingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMember sets the "member" edge to the EnterpriseMember entity.
func (_u *EnterpriseMemberGroupBindingUpdate) SetMember(v *EnterpriseMember) *EnterpriseMemberGroupBindingUpdate {
	return _u.SetMemberID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *EnterpriseMemberGroupBindingUpdate) SetGroup(v *Group) *EnterpriseMemberGroupBindingUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the EnterpriseMemberGroupBindingMutation object of the builder.
func (_u *EnterpriseMemberGroupBindingUpdate) Mutation() *EnterpriseMemberGroupBindingMutation {
	return _u.mutation
}

// ClearMember clears the "member" edge to the EnterpriseMember entity.
func (_u *EnterpriseMemberGroupBindingUpdate) ClearMember() *EnterpriseMemberGroupBindingUpdate {
	_u.mutation.ClearMember()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *EnterpriseMemberGroupBindingUpdate) ClearGroup() *EnterpriseMemberGroupBindingUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EnterpriseMemberGroupBindingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnterpriseMemberGroupBindingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EnterpriseMemberGroupBindingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnterpriseMemberGroupBindingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnterpriseMemberGroupBindingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := enterprisemembergroupbinding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnterpriseMemberGroupBindingUpdate) check() error {
	if v, ok := _u.mutation.SortOrder(); ok {
		if err := enterprisemembergroupbinding.SortOrderValidator(v); err != nil {
			return &ValidationError{Name: "sort_order", err: fmt.Errorf(`ent: validator failed for field "EnterpriseMemberGroupBinding.sort_order": %w`, err)}
		}
	}
	if _u.mutation.MemberCleared() && len(_u.mutation.MemberIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EnterpriseMemberGroupBinding.member"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EnterpriseMemberGroupBinding.group"`)
	}
	return nil
}

func (_u *EnterpriseMemberGroupBindingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(enterprisemembergroupbinding.Table, enterprisemembergroupbinding.Columns, sqlgraph.NewFieldSpec(enterprisemembergroupbinding.FieldMemberID, field.TypeInt64), sqlgraph.NewFieldSpec(enterprisemembergroupbinding.FieldGroupID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(enterprisemembergroupbinding.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(enterprisemembergroupbinding.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(enterprisemembergroupbinding.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MemberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enterprisemembergroupbinding.MemberTable,
			Columns: []string{enterprisemembergroupbinding.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisemember.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enterprisemembergroupbinding.MemberTable,
			Columns: []string{enterprisemembergroupbinding.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisemember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enterprisemembergroupbinding.GroupTable,
			Columns: []string{enterprisemembergroupbinding.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enterprisemembergroupbinding.GroupTable,
			Columns: []string{enterprisemembergroupbinding.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{enterprisemembergroupbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EnterpriseMemberGroupBindingUpdateOne is the builder for updating a single EnterpriseMemberGroupBinding entity.
type EnterpriseMemberGroupBindingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EnterpriseMemberGroupBindingMutation
}

// SetMemberID sets the "member_id" field.
func (_u *EnterpriseMemberGroupBindingUpdateOne) SetMemberID(v int64) *EnterpriseMemberGroupBindingUpdateOne {
	_u.mutation.SetMemberID(v)
	return _u
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (_u *EnterpriseMemberGroupBindingUpdateOne) SetNillableMemberID(v *int64) *EnterpriseMemberGroupBindingUpdateOne {
	if v != nil {
		_u.SetMemberID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *EnterpriseMemberGroupBindingUpdateOne) SetGroupID(v int64) *EnterpriseMemberGroupBindingUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *EnterpriseMemberGroupBindingUpdateOne) SetNillableGroupID(v *int64) *EnterpriseMemberGroupBindingUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *EnterpriseMemberGroupBindingUpdateOne) SetSortOrder(v int) *EnterpriseMemberGroupBindingUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *EnterpriseMemberGroupBindingUpdateOne) SetNillableSortOrder(v *int) *EnterpriseMemberGroupBindingUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *EnterpriseMemberGroupBindingUpdateOne) AddSortOrder(v int) *EnterpriseMemberGroupBindingUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnterpriseMemberGroupBindingUpdateOne) SetUpdatedAt(v time.Time) *EnterpriseMemberGroupBindingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMember sets the "member" edge to the EnterpriseMember entity.
func (_u *EnterpriseMemberGroupBindingUpdateOne) SetMember(v *EnterpriseMember) *EnterpriseMemberGroupBindingUpdateOne {
	return _u.SetMemberID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *EnterpriseMemberGroupBindingUpdateOne) SetGroup(v *Group) *EnterpriseMemberGroupBindingUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the EnterpriseMemberGroupBindingMutation object of the builder.
func (_u *EnterpriseMemberGroupBindingUpdateOne) Mutation() *EnterpriseMemberGroupBindingMutation {
	return _u.mutation
}

// ClearMember clears the "member" edge to the EnterpriseMember entity.
func (_u *EnterpriseMemberGroupBindingUpdateOne) ClearMember() *EnterpriseMemberGroupBindingUpdateOne {
	_u.mutation.ClearMember()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *EnterpriseMemberGroupBindingUpdateOne) ClearGroup() *EnterpriseMemberGroupBindingUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the EnterpriseMemberGroupBindingUpdate builder.
func (_u *EnterpriseMemberGroupBindingUpdateOne) Where(ps ...predicate.EnterpriseMemberGroupBinding) *EnterpriseMemberGroupBindingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EnterpriseMemberGroupBindingUpdateOne) Select(field string, fields ...string) *EnterpriseMemberGroupBindingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EnterpriseMemberGroupBinding entity.
func (_u *EnterpriseMemberGroupBindingUpdateOne) Save(ctx context.Context) (*EnterpriseMemberGroupBinding, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnterpriseMemberGroupBindingUpdateOne) SaveX(ctx context.Context) *EnterpriseMemberGroupBinding {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EnterpriseMemberGroupBindingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnterpriseMemberGroupBindingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnterpriseMemberGroupBindingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := enterprisemembergroupbinding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnterpriseMemberGroupBindingUpdateOne) check() error {
	if v, ok := _u.mutation.SortOrder(); ok {
		if err := enterprisemembergroupbinding.SortOrderValidator(v); err != nil {
			return &ValidationError{Name: "sort_order", err: fmt.Errorf(`ent: validator failed for field "EnterpriseMemberGroupBinding.sort_order": %w`, err)}
		}
	}
	if _u.mutation.MemberCleared() && len(_u.mutation.MemberIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EnterpriseMemberGroupBinding.member"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EnterpriseMemberGroupBinding.group"`)
	}
	return nil
}

func (_u *EnterpriseMemberGroupBindingUpdateOne) sqlSave(ctx context.Context) (_node *EnterpriseMemberGroupBinding, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(enterprisemembergroupbinding.Table, enterprisemembergroupbinding.Columns, sqlgraph.NewFieldSpec(enterprisemembergroupbinding.FieldMemberID, field.TypeInt64), sqlgraph.NewFieldSpec(enterprisemembergroupbinding.FieldGroupID, field.TypeInt64))
	if id, ok := _u.mutation.MemberID(); !ok {
		return nil, &ValidationError{Name: "member_id", err: errors.New(`ent: missing "EnterpriseMemberGroupBinding.member_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := _u.mutation.GroupID(); !ok {
		return nil, &ValidationError{Name: "group_id", err: errors.New(`ent: missing "EnterpriseMemberGroupBinding.group_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !enterprisemembergroupbinding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(enterprisemembergroupbinding.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(enterprisemembergroupbinding.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(enterprisemembergroupbinding.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MemberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enterprisemembergroupbinding.MemberTable,
			Columns: []string{enterprisemembergroupbinding.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisemember.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enterprisemembergroupbinding.MemberTable,
			Columns: []string{enterprisemembergroupbinding.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisemember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enterprisemembergroupbinding.GroupTable,
			Columns: []string{enterprisemembergroupbinding.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enterprisemembergroupbinding.GroupTable,
			Columns: []string{enterprisemembergroupbinding.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EnterpriseMemberGroupBinding{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{enterprisemembergroupbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
