// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/enterprisemember"
	"github.com/Wei-Shaw/sub2api/ent/enterprisememberbudgetentry"
	"github.com/Wei-Shaw/sub2api/ent/enterprisememberbudgetperiod"
	"github.com/Wei-Shaw/sub2api/ent/enterprisememberbudgetreservation"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// EnterpriseMemberCreate is the builder for creating a EnterpriseMember entity.
type EnterpriseMemberCreate struct {
	config
	mutation *EnterpriseMemberMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *EnterpriseMemberCreate) SetCreatedAt(v time.Time) *EnterpriseMemberCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EnterpriseMemberCreate) SetNillableCreatedAt(v *time.Time) *EnterpriseMemberCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EnterpriseMemberCreate) SetUpdatedAt(v time.Time) *EnterpriseMemberCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EnterpriseMemberCreate) SetNillableUpdatedAt(v *time.Time) *EnterpriseMemberCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *EnterpriseMemberCreate) SetDeletedAt(v time.Time) *EnterpriseMemberCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *EnterpriseMemberCreate) SetNillableDeletedAt(v *time.Time) *EnterpriseMemberCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetEnterpriseUserID sets the "enterprise_user_id" field.
func (_c *EnterpriseMemberCreate) SetEnterpriseUserID(v int64) *EnterpriseMemberCreate {
	_c.mutation.SetEnterpriseUserID(v)
	return _c
}

// SetMemberCode sets the "member_code" field.
func (_c *EnterpriseMemberCreate) SetMemberCode(v string) *EnterpriseMemberCreate {
	_c.mutation.SetMemberCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *EnterpriseMemberCreate) SetName(v string) *EnterpriseMemberCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *EnterpriseMemberCreate) SetStatus(v string) *EnterpriseMemberCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *EnterpriseMemberCreate) SetNillableStatus(v *string) *EnterpriseMemberCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (_c *EnterpriseMemberCreate) SetMonthlyLimitUsd(v float64) *EnterpriseMemberCreate {
	_c.mutation.SetMonthlyLimitUsd(v)
	return _c
}

// SetNillableMonthlyLimitUsd sets the "monthly_limit_usd" field if the given value is not nil.
func (_c *EnterpriseMemberCreate) SetNillableMonthlyLimitUsd(v *float64) *EnterpriseMemberCreate {
	if v != nil {
		_c.SetMonthlyLimitUsd(*v)
	}
	return _c
}

// SetRateLimit5h sets the "rate_limit_5h" field.
func (_c *EnterpriseMemberCreate) SetRateLimit5h(v float64) *EnterpriseMemberCreate {
	_c.mutation.SetRateLimit5h(v)
	return _c
}

// SetNillableRateLimit5h sets the "rate_limit_5h" field if the given value is not nil.
func (_c *EnterpriseMemberCreate) SetNillableRateLimit5h(v *float64) *EnterpriseMemberCreate {
	if v != nil {
		_c.SetRateLimit5h(*v)
	}
	return _c
}

// SetRateLimit1d sets the "rate_limit_1d" field.
func (_c *EnterpriseMemberCreate) SetRateLimit1d(v float64) *EnterpriseMemberCreate {
	_c.mutation.SetRateLimit1d(v)
	return _c
}

// SetNillableRateLimit1d sets the "rate_limit_1d" field if the given value is not nil.
func (_c *EnterpriseMemberCreate) SetNillableRateLimit1d(v *float64) *EnterpriseMemberCreate {
	if v != nil {
		_c.SetRateLimit1d(*v)
	}
	return _c
}

// SetRateLimit7d sets the "rate_limit_7d" field.
func (_c *EnterpriseMemberCreate) SetRateLimit7d(v float64) *EnterpriseMemberCreate {
	_c.mutation.SetRateLimit7d(v)
	return _c
}

// SetNillableRateLimit7d sets the "rate_limit_7d" field if the given value is not nil.
func (_c *EnterpriseMemberCreate) SetNillableRateLimit7d(v *float64) *EnterpriseMemberCreate {
	if v != nil {
		_c.SetRateLimit7d(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *EnterpriseMemberCreate) SetVersion(v int64) *EnterpriseMemberCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *EnterpriseMemberCreate) SetNillableVersion(v *int64) *EnterpriseMemberCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetEnterpriseUser sets the "enterprise_user" edge to the User entity.
func (_c *EnterpriseMemberCreate) SetEnterpriseUser(v *User) *EnterpriseMemberCreate {
	return _c.SetEnterpriseUserID(v.ID)
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_c *EnterpriseMemberCreate) AddAPIKeyIDs(ids ...int64) *EnterpriseMemberCreate {
	_c.mutation.AddAPIKeyIDs(ids...)
	return _c
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_c *EnterpriseMemberCreate) AddAPIKeys(v ...*APIKey) *EnterpriseMemberCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAPIKeyIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_c *EnterpriseMemberCreate) AddUsageLogIDs(ids ...int64) *EnterpriseMemberCreate {
	_c.mutation.AddUsageLogIDs(ids...)
	return _c
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_c *EnterpriseMemberCreate) AddUsageLogs(v ...*UsageLog) *EnterpriseMemberCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUsageLogIDs(ids...)
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_c *EnterpriseMemberCreate) AddGroupIDs(ids ...int64) *EnterpriseMemberCreate {
	_c.mutation.AddGroupIDs(ids...)
	return _c
}

// AddGroups adds the "groups" edges to the Group entity.
func (_c *EnterpriseMemberCreate) AddGroups(v ...*Group) *EnterpriseMemberCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddGroupIDs(ids...)
}

// AddBudgetPeriodIDs adds the "budget_periods" edge to the EnterpriseMemberBudgetPeriod entity by IDs.
func (_c *EnterpriseMemberCreate) AddBudgetPeriodIDs(ids ...int64) *EnterpriseMemberCreate {
	_c.mutation.AddBudgetPeriodIDs(ids...)
	return _c
}

// AddBudgetPeriods adds the "budget_periods" edges to the EnterpriseMemberBudgetPeriod entity.
func (_c *EnterpriseMemberCreate) AddBudgetPeriods(v ...*EnterpriseMemberBudgetPeriod) *EnterpriseMemberCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBudgetPeriodIDs(ids...)
}

// AddBudgetReservationIDs adds the "budget_reservations" edge to the EnterpriseMemberBudgetReservation entity by IDs.
func (_c *EnterpriseMemberCreate) AddBudgetReservationIDs(ids ...int64) *EnterpriseMemberCreate {
	_c.mutation.AddBudgetReservationIDs(ids...)
	return _c
}

// AddBudgetReservations adds the "budget_reservations" edges to the EnterpriseMemberBudgetReservation entity.
func (_c *EnterpriseMemberCreate) AddBudgetReservations(v ...*EnterpriseMemberBudgetReservation) *EnterpriseMemberCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBudgetReservationIDs(ids...)
}

// AddBudgetEntryIDs adds the "budget_entries" edge to the EnterpriseMemberBudgetEntry entity by IDs.
func (_c *EnterpriseMemberCreate) AddBudgetEntryIDs(ids ...int64) *EnterpriseMemberCreate {
	_c.mutation.AddBudgetEntryIDs(ids...)
	return _c
}

// AddBudgetEntries adds the "budget_entries" edges to the EnterpriseMemberBudgetEntry entity.
func (_c *EnterpriseMemberCreate) AddBudgetEntries(v ...*EnterpriseMemberBudgetEntry) *EnterpriseMemberCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBudgetEntryIDs(ids...)
}

// Mutation returns the EnterpriseMemberMutation object of the builder.
func (_c *EnterpriseMemberCreate) Mutation() *EnterpriseMemberMutation {
	return _c.mutation
}

// Save creates the EnterpriseMember in the database.
func (_c *EnterpriseMemberCreate) Save(ctx context.Context) (*EnterpriseMember, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EnterpriseMemberCreate) SaveX(ctx context.Context) *EnterpriseMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnterpriseMemberCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnterpriseMemberCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EnterpriseMemberCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if enterprisemember.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized enterprisemember.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := enterprisemember.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if enterprisemember.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized enterprisemember.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := enterprisemember.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := enterprisemember.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.MonthlyLimitUsd(); !ok {
		v := enterprisemember.DefaultMonthlyLimitUsd
		_c.mutation.SetMonthlyLimitUsd(v)
	}
	if _, ok := _c.mutation.RateLimit5h(); !ok {
		v := enterprisemember.DefaultRateLimit5h
		_c.mutation.SetRateLimit5h(v)
	}
	if _, ok := _c.mutation.RateLimit1d(); !ok {
		v := enterprisemember.DefaultRateLimit1d
		_c.mutation.SetRateLimit1d(v)
	}
	if _, ok := _c.mutation.RateLimit7d(); !ok {
		v := enterprisemember.DefaultRateLimit7d
		_c.mutation.SetRateLimit7d(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := enterprisemember.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *EnterpriseMemberCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EnterpriseMember.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EnterpriseMember.updated_at"`)}
	}
	if _, ok := _c.mutation.EnterpriseUserID(); !ok {
		return &ValidationError{Name: "enterprise_user_id", err: errors.New(`ent: missing required field "EnterpriseMember.enterprise_user_id"`)}
	}
	if _, ok := _c.mutation.MemberCode(); !ok {
		return &ValidationError{Name: "member_code", err: errors.New(`ent: missing required field "EnterpriseMember.member_code"`)}
	}
	if v, ok := _c.mutation.MemberCode(); ok {
		if err := enterprisemember.MemberCodeValidator(v); err != nil {
			return &ValidationError{Name: "member_code", err: fmt.Errorf(`ent: validator failed for field "EnterpriseMember.member_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "EnterpriseMember.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := enterprisemember.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "EnterpriseMember.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "EnterpriseMember.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := enterprisemember.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EnterpriseMember.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MonthlyLimitUsd(); !ok {
		return &ValidationError{Name: "monthly_limit_usd", err: errors.New(`ent: missing required field "EnterpriseMember.monthly_limit_usd"`)}
	}
	if _, ok := _c.mutation.RateLimit5h(); !ok {
		return &ValidationError{Name: "rate_limit_5h", err: errors.New(`ent: missing required field "EnterpriseMember.rate_limit_5h"`)}
	}
	if _, ok := _c.mutation.RateLimit1d(); !ok {
		return &ValidationError{Name: "rate_limit_1d", err: errors.New(`ent: missing required field "EnterpriseMember.rate_limit_1d"`)}
	}
	if _, ok := _c.mutation.RateLimit7d(); !ok {
		return &ValidationError{Name: "rate_limit_7d", err: errors.New(`ent: missing required field "EnterpriseMember.rate_limit_7d"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "EnterpriseMember.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := enterprisemember.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "EnterpriseMember.version": %w`, err)}
		}
	}
	if len(_c.mutation.EnterpriseUserIDs()) == 0 {
		return &ValidationError{Name: "enterprise_user", err: errors.New(`ent: missing required edge "EnterpriseMember.enterprise_user"`)}
	}
	return nil
}

func (_c *EnterpriseMemberCreate) sqlSave(ctx context.Context) (*EnterpriseMember, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EnterpriseMemberCreate) createSpec() (*EnterpriseMember, *sqlgraph.CreateSpec) {
	var (
		_node = &EnterpriseMember{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(enterprisemember.Table, sqlgraph.NewFieldSpec(enterprisemember.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(enterprisemember.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(enterprisemember.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(enterprisemember.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.MemberCode(); ok {
		_spec.SetField(enterprisemember.FieldMemberCode, field.TypeString, value)
		_node.MemberCode = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(enterprisemember.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(enterprisemember.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.MonthlyLimitUsd(); ok {
		_spec.SetField(enterprisemember.FieldMonthlyLimitUsd, field.TypeFloat64, value)
		_node.MonthlyLimitUsd = value
	}
	if value, ok := _c.mutation.RateLimit5h(); ok {
		_spec.SetField(enterprisemember.FieldRateLimit5h, field.TypeFloat64, value)
		_node.RateLimit5h = value
	}
	if value, ok := _c.mutation.RateLimit1d(); ok {
		_spec.SetField(enterprisemember.FieldRateLimit1d, field.TypeFloat64, value)
		_node.RateLimit1d = value
	}
	if value, ok := _c.mutation.RateLimit7d(); ok {
		_spec.SetField(enterprisemember.FieldRateLimit7d, field.TypeFloat64, value)
		_node.RateLimit7d = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(enterprisemember.FieldVersion, field.TypeInt64, value)
		_node.Version = value
	}
	if nodes := _c.mutation.EnterpriseUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enterprisemember.EnterpriseUserTable,
			Columns: []string{enterprisemember.EnterpriseUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EnterpriseUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.APIKeysTable,
			Columns: []string{enterprisemember.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.UsageLogsTable,
			Columns: []string{enterprisemember.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   enterprisemember.GroupsTable,
			Columns: enterprisemember.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &EnterpriseMemberGroupBindingCreate{config: _c.config, mutation: newEnterpriseMemberGroupBindingMutation(_c.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BudgetPeriodsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.BudgetPeriodsTable,
			Columns: []string{enterprisemember.BudgetPeriodsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisememberbudgetperiod.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BudgetReservationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.BudgetReservationsTable,
			Columns: []string{enterprisemember.BudgetReservationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisememberbudgetreservation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BudgetEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.BudgetEntriesTable,
			Columns: []string{enterprisemember.BudgetEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisememberbudgetentry.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EnterpriseMember.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EnterpriseMemberUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EnterpriseMemberCreate) OnConflict(opts ...sql.ConflictOption) *EnterpriseMemberUpsertOne {
	_c.conflict = opts
	return &EnterpriseMemberUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EnterpriseMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EnterpriseMemberCreate) OnConflictColumns(columns ...string) *EnterpriseMemberUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EnterpriseMemberUpsertOne{
		create: _c,
	}
}

type (
	// EnterpriseMemberUpsertOne is the builder for "upsert"-ing
	//  one EnterpriseMember node.
	EnterpriseMemberUpsertOne struct {
		create *EnterpriseMemberCreate
	}

	// EnterpriseMemberUpsert is the "OnConflict" setter.
	EnterpriseMemberUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *EnterpriseMemberUpsert) SetUpdatedAt(v time.Time) *EnterpriseMemberUpsert {
	u.Set(enterprisemember.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnterpriseMemberUpsert) UpdateUpdatedAt() *EnterpriseMemberUpsert {
	u.SetExcluded(enterprisemember.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EnterpriseMemberUpsert) SetDeletedAt(v time.Time) *EnterpriseMemberUpsert {
	u.Set(enterprisemember.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EnterpriseMemberUpsert) UpdateDeletedAt() *EnterpriseMemberUpsert {
	u.SetExcluded(enterprisemember.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EnterpriseMemberUpsert) ClearDeletedAt() *EnterpriseMemberUpsert {
	u.SetNull(enterprisemember.FieldDeletedAt)
	return u
}

// SetEnterpriseUserID sets the "enterprise_user_id" field.
func (u *EnterpriseMemberUpsert) SetEnterpriseUserID(v int64) *EnterpriseMemberUpsert {
	u.Set(enterprisemember.FieldEnterpriseUserID, v)
	return u
}

// UpdateEnterpriseUserID sets the "enterprise_user_id" field to the value that was provided on create.
func (u *EnterpriseMemberUpsert) UpdateEnterpriseUserID() *EnterpriseMemberUpsert {
	u.SetExcluded(enterprisemember.FieldEnterpriseUserID)
	return u
}

// SetMemberCode sets the "member_code" field.
func (u *EnterpriseMemberUpsert) SetMemberCode(v string) *EnterpriseMemberUpsert {
	u.Set(enterprisemember.FieldMemberCode, v)
	return u
}

// UpdateMemberCode sets the "member_code" field to the value that was provided on create.
func (u *EnterpriseMemberUpsert) UpdateMemberCode() *EnterpriseMemberUpsert {
	u.SetExcluded(enterprisemember.FieldMemberCode)
	return u
}

// SetName sets the "name" field.
func (u *EnterpriseMemberUpsert) SetName(v string) *EnterpriseMemberUpsert {
	u.Set(enterprisemember.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EnterpriseMemberUpsert) UpdateName() *EnterpriseMemberUpsert {
	u.SetExcluded(enterprisemember.FieldName)
	return u
}

// SetStatus sets the "status" field.
func (u *EnterpriseMemberUpsert) SetStatus(v string) *EnterpriseMemberUpsert {
	u.Set(enterprisemember.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EnterpriseMemberUpsert) UpdateStatus() *EnterpriseMemberUpsert {
	u.SetExcluded(enterprisemember.FieldStatus)
	return u
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *EnterpriseMemberUpsert) SetMonthlyLimitUsd(v float64) *EnterpriseMemberUpsert {
	u.Set(enterprisemember.FieldMonthlyLimitUsd, v)
	return u
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *EnterpriseMemberUpsert) UpdateMonthlyLimitUsd() *EnterpriseMemberUpsert {
	u.SetExcluded(enterprisemember.FieldMonthlyLimitUsd)
	return u
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *EnterpriseMemberUpsert) AddMonthlyLimitUsd(v float64) *EnterpriseMemberUpsert {
	u.Add(enterprisemember.FieldMonthlyLimitUsd, v)
	return u
}

// SetRateLimit5h sets the "rate_limit_5h" field.
func (u *EnterpriseMemberUpsert) SetRateLimit5h(v float64) *EnterpriseMemberUpsert {
	u.Set(enterprisemember.FieldRateLimit5h, v)
	return u
}

// UpdateRateLimit5h sets the "rate_limit_5h" field to the value that was provided on create.
func (u *EnterpriseMemberUpsert) UpdateRateLimit5h() *EnterpriseMemberUpsert {
	u.SetExcluded(enterprisemember.FieldRateLimit5h)
	return u
}

// AddRateLimit5h adds v to the "rate_limit_5h" field.
func (u *EnterpriseMemberUpsert) AddRateLimit5h(v float64) *EnterpriseMemberUpsert {
	u.Add(enterprisemember.FieldRateLimit5h, v)
	return u
}

// SetRateLimit1d sets the "rate_limit_1d" field.
func (u *EnterpriseMemberUpsert) SetRateLimit1d(v float64) *EnterpriseMemberUpsert {
	u.Set(enterprisemember.FieldRateLimit1d, v)
	return u
}

// UpdateRateLimit1d sets the "rate_limit_1d" field to the value that was provided on create.
func (u *EnterpriseMemberUpsert) UpdateRateLimit1d() *EnterpriseMemberUpsert {
	u.SetExcluded(enterprisemember.FieldRateLimit1d)
	return u
}

// AddRateLimit1d adds v to the "rate_limit_1d" field.
func (u *EnterpriseMemberUpsert) AddRateLimit1d(v float64) *EnterpriseMemberUpsert {
	u.Add(enterprisemember.FieldRateLimit1d, v)
	return u
}

// SetRateLimit7d sets the "rate_limit_7d" field.
func (u *EnterpriseMemberUpsert) SetRateLimit7d(v float64) *EnterpriseMemberUpsert {
	u.Set(enterprisemember.FieldRateLimit7d, v)
	return u
}

// UpdateRateLimit7d sets the "rate_limit_7d" field to the value that was provided on create.
func (u *EnterpriseMemberUpsert) UpdateRateLimit7d() *EnterpriseMemberUpsert {
	u.SetExcluded(enterprisemember.FieldRateLimit7d)
	return u
}

// AddRateLimit7d adds v to the "rate_limit_7d" field.
func (u *EnterpriseMemberUpsert) AddRateLimit7d(v float64) *EnterpriseMemberUpsert {
	u.Add(enterprisemember.FieldRateLimit7d, v)
	return u
}

// SetVersion sets the "version" field.
func (u *EnterpriseMemberUpsert) SetVersion(v int64) *EnterpriseMemberUpsert {
	u.Set(enterprisemember.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *EnterpriseMemberUpsert) UpdateVersion() *EnterpriseMemberUpsert {
	u.SetExcluded(enterprisemember.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *EnterpriseMemberUpsert) AddVersion(v int64) *EnterpriseMemberUpsert {
	u.Add(enterprisemember.FieldVersion, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.EnterpriseMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EnterpriseMemberUpsertOne) UpdateNewValues() *EnterpriseMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(enterprisemember.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EnterpriseMember.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EnterpriseMemberUpsertOne) Ignore() *EnterpriseMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EnterpriseMemberUpsertOne) DoNothing() *EnterpriseMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EnterpriseMemberCreate.OnConflict
// documentation for more info.
func (u *EnterpriseMemberUpsertOne) Update(set func(*EnterpriseMemberUpsert)) *EnterpriseMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EnterpriseMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EnterpriseMemberUpsertOne) SetUpdatedAt(v time.Time) *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertOne) UpdateUpdatedAt() *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EnterpriseMemberUpsertOne) SetDeletedAt(v time.Time) *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertOne) UpdateDeletedAt() *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EnterpriseMemberUpsertOne) ClearDeletedAt() *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.ClearDeletedAt()
	})
}

// SetEnterpriseUserID sets the "enterprise_user_id" field.
func (u *EnterpriseMemberUpsertOne) SetEnterpriseUserID(v int64) *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetEnterpriseUserID(v)
	})
}

// UpdateEnterpriseUserID sets the "enterprise_user_id" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertOne) UpdateEnterpriseUserID() *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateEnterpriseUserID()
	})
}

// SetMemberCode sets the "member_code" field.
func (u *EnterpriseMemberUpsertOne) SetMemberCode(v string) *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetMemberCode(v)
	})
}

// UpdateMemberCode sets the "member_code" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertOne) UpdateMemberCode() *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateMemberCode()
	})
}

// SetName sets the "name" field.
func (u *EnterpriseMemberUpsertOne) SetName(v string) *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertOne) UpdateName() *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateName()
	})
}

// SetStatus sets the "status" field.
func (u *EnterpriseMemberUpsertOne) SetStatus(v string) *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertOne) UpdateStatus() *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateStatus()
	})
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *EnterpriseMemberUpsertOne) SetMonthlyLimitUsd(v float64) *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetMonthlyLimitUsd(v)
	})
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *EnterpriseMemberUpsertOne) AddMonthlyLimitUsd(v float64) *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.AddMonthlyLimitUsd(v)
	})
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertOne) UpdateMonthlyLimitUsd() *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateMonthlyLimitUsd()
	})
}

// SetRateLimit5h sets the "rate_limit_5h" field.
func (u *EnterpriseMemberUpsertOne) SetRateLimit5h(v float64) *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetRateLimit5h(v)
	})
}

// AddRateLimit5h adds v to the "rate_limit_5h" field.
func (u *EnterpriseMemberUpsertOne) AddRateLimit5h(v float64) *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.AddRateLimit5h(v)
	})
}

// UpdateRateLimit5h sets the "rate_limit_5h" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertOne) UpdateRateLimit5h() *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateRateLimit5h()
	})
}

// SetRateLimit1d sets the "rate_limit_1d" field.
func (u *EnterpriseMemberUpsertOne) SetRateLimit1d(v float64) *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetRateLimit1d(v)
	})
}

// AddRateLimit1d adds v to the "rate_limit_1d" field.
func (u *EnterpriseMemberUpsertOne) AddRateLimit1d(v float64) *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.AddRateLimit1d(v)
	})
}

// UpdateRateLimit1d sets the "rate_limit_1d" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertOne) UpdateRateLimit1d() *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateRateLimit1d()
	})
}

// SetRateLimit7d sets the "rate_limit_7d" field.
func (u *EnterpriseMemberUpsertOne) SetRateLimit7d(v float64) *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetRateLimit7d(v)
	})
}

// AddRateLimit7d adds v to the "rate_limit_7d" field.
func (u *EnterpriseMemberUpsertOne) AddRateLimit7d(v float64) *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.AddRateLimit7d(v)
	})
}

// UpdateRateLimit7d sets the "rate_limit_7d" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertOne) UpdateRateLimit7d() *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateRateLimit7d()
	})
}

// SetVersion sets the "version" field.
func (u *EnterpriseMemberUpsertOne) SetVersion(v int64) *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *EnterpriseMemberUpsertOne) AddVersion(v int64) *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertOne) UpdateVersion() *EnterpriseMemberUpsertOne {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateVersion()
	})
}

// Exec executes the query.
func (u *EnterpriseMemberUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EnterpriseMemberCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EnterpriseMemberUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EnterpriseMemberUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EnterpriseMemberUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EnterpriseMemberCreateBulk is the builder for creating many EnterpriseMember entities in bulk.
type EnterpriseMemberCreateBulk struct {
	config
	err      error
	builders []*EnterpriseMemberCreate
	conflict []sql.ConflictOption
}

// Save creates the EnterpriseMember entities in the database.
func (_c *EnterpriseMemberCreateBulk) Save(ctx context.Context) ([]*EnterpriseMember, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EnterpriseMember, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EnterpriseMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EnterpriseMemberCreateBulk) SaveX(ctx context.Context) []*EnterpriseMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnterpriseMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnterpriseMemberCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EnterpriseMember.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EnterpriseMemberUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EnterpriseMemberCreateBulk) OnConflict(opts ...sql.ConflictOption) *EnterpriseMemberUpsertBulk {
	_c.conflict = opts
	return &EnterpriseMemberUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EnterpriseMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EnterpriseMemberCreateBulk) OnConflictColumns(columns ...string) *EnterpriseMemberUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EnterpriseMemberUpsertBulk{
		create: _c,
	}
}

// EnterpriseMemberUpsertBulk is the builder for "upsert"-ing
// a bulk of EnterpriseMember nodes.
type EnterpriseMemberUpsertBulk struct {
	create *EnterpriseMemberCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.EnterpriseMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EnterpriseMemberUpsertBulk) UpdateNewValues() *EnterpriseMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(enterprisemember.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EnterpriseMember.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EnterpriseMemberUpsertBulk) Ignore() *EnterpriseMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EnterpriseMemberUpsertBulk) DoNothing() *EnterpriseMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EnterpriseMemberCreateBulk.OnConflict
// documentation for more info.
func (u *EnterpriseMemberUpsertBulk) Update(set func(*EnterpriseMemberUpsert)) *EnterpriseMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EnterpriseMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EnterpriseMemberUpsertBulk) SetUpdatedAt(v time.Time) *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertBulk) UpdateUpdatedAt() *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EnterpriseMemberUpsertBulk) SetDeletedAt(v time.Time) *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertBulk) UpdateDeletedAt() *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EnterpriseMemberUpsertBulk) ClearDeletedAt() *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.ClearDeletedAt()
	})
}

// SetEnterpriseUserID sets the "enterprise_user_id" field.
func (u *EnterpriseMemberUpsertBulk) SetEnterpriseUserID(v int64) *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetEnterpriseUserID(v)
	})
}

// UpdateEnterpriseUserID sets the "enterprise_user_id" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertBulk) UpdateEnterpriseUserID() *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateEnterpriseUserID()
	})
}

// SetMemberCode sets the "member_code" field.
func (u *EnterpriseMemberUpsertBulk) SetMemberCode(v string) *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetMemberCode(v)
	})
}

// UpdateMemberCode sets the "member_code" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertBulk) UpdateMemberCode() *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateMemberCode()
	})
}

// SetName sets the "name" field.
func (u *EnterpriseMemberUpsertBulk) SetName(v string) *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertBulk) UpdateName() *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateName()
	})
}

// SetStatus sets the "status" field.
func (u *EnterpriseMemberUpsertBulk) SetStatus(v string) *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertBulk) UpdateStatus() *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateStatus()
	})
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *EnterpriseMemberUpsertBulk) SetMonthlyLimitUsd(v float64) *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetMonthlyLimitUsd(v)
	})
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *EnterpriseMemberUpsertBulk) AddMonthlyLimitUsd(v float64) *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.AddMonthlyLimitUsd(v)
	})
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertBulk) UpdateMonthlyLimitUsd() *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateMonthlyLimitUsd()
	})
}

// SetRateLimit5h sets the "rate_limit_5h" field.
func (u *EnterpriseMemberUpsertBulk) SetRateLimit5h(v float64) *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetRateLimit5h(v)
	})
}

// AddRateLimit5h adds v to the "rate_limit_5h" field.
func (u *EnterpriseMemberUpsertBulk) AddRateLimit5h(v float64) *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.AddRateLimit5h(v)
	})
}

// UpdateRateLimit5h sets the "rate_limit_5h" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertBulk) UpdateRateLimit5h() *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateRateLimit5h()
	})
}

// SetRateLimit1d sets the "rate_limit_1d" field.
func (u *EnterpriseMemberUpsertBulk) SetRateLimit1d(v float64) *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetRateLimit1d(v)
	})
}

// AddRateLimit1d adds v to the "rate_limit_1d" field.
func (u *EnterpriseMemberUpsertBulk) AddRateLimit1d(v float64) *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.AddRateLimit1d(v)
	})
}

// UpdateRateLimit1d sets the "rate_limit_1d" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertBulk) UpdateRateLimit1d() *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateRateLimit1d()
	})
}

// SetRateLimit7d sets the "rate_limit_7d" field.
func (u *EnterpriseMemberUpsertBulk) SetRateLimit7d(v float64) *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetRateLimit7d(v)
	})
}

// AddRateLimit7d adds v to the "rate_limit_7d" field.
func (u *EnterpriseMemberUpsertBulk) AddRateLimit7d(v float64) *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.AddRateLimit7d(v)
	})
}

// UpdateRateLimit7d sets the "rate_limit_7d" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertBulk) UpdateRateLimit7d() *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateRateLimit7d()
	})
}

// SetVersion sets the "version" field.
func (u *EnterpriseMemberUpsertBulk) SetVersion(v int64) *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *EnterpriseMemberUpsertBulk) AddVersion(v int64) *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *EnterpriseMemberUpsertBulk) UpdateVersion() *EnterpriseMemberUpsertBulk {
	return u.Update(func(s *EnterpriseMemberUpsert) {
		s.UpdateVersion()
	})
}

// Exec executes the query.
func (u *EnterpriseMemberUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EnterpriseMemberCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EnterpriseMemberCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EnterpriseMemberUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
