// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/enterprisemember"
	"github.com/Wei-Shaw/sub2api/ent/enterprisememberbudgetentry"
	"github.com/Wei-Shaw/sub2api/ent/enterprisememberbudgetperiod"
	"github.com/Wei-Shaw/sub2api/ent/enterprisememberbudgetreservation"
	"github.com/Wei-Shaw/sub2api/ent/enterprisemembergroupbinding"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// EnterpriseMemberQuery is the builder for querying EnterpriseMember entities.
type EnterpriseMemberQuery struct {
	config
	ctx                               *QueryContext
	order                             []enterprisemember.OrderOption
	inters                            []Interceptor
	predicates                        []predicate.EnterpriseMember
	withEnterpriseUser                *UserQuery
	withAPIKeys                       *APIKeyQuery
	withUsageLogs                     *UsageLogQuery
	withGroups                        *GroupQuery
	withBudgetPeriods                 *EnterpriseMemberBudgetPeriodQuery
	withBudgetReservations            *EnterpriseMemberBudgetReservationQuery
	withBudgetEntries                 *EnterpriseMemberBudgetEntryQuery
	withEnterpriseMemberGroupBindings *EnterpriseMemberGroupBindingQuery
	modifiers                         []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EnterpriseMemberQuery builder.
func (_q *EnterpriseMemberQuery) Where(ps ...predicate.EnterpriseMember) *EnterpriseMemberQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *EnterpriseMemberQuery) Limit(limit int) *EnterpriseMemberQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *EnterpriseMemberQuery) Offset(offset int) *EnterpriseMemberQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *EnterpriseMemberQuery) Unique(unique bool) *EnterpriseMemberQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *EnterpriseMemberQuery) Order(o ...enterprisemember.OrderOption) *EnterpriseMemberQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryEnterpriseUser chains the current query on the "enterprise_user" edge.
func (_q *EnterpriseMemberQuery) QueryEnterpriseUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(enterprisemember.Table, enterprisemember.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, enterprisemember.EnterpriseUserTable, enterprisemember.EnterpriseUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAPIKeys chains the current query on the "api_keys" edge.
func (_q *EnterpriseMemberQuery) QueryAPIKeys() *APIKeyQuery {
	query := (&APIKeyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(enterprisemember.Table, enterprisemember.FieldID, selector),
			sqlgraph.To(apikey.Table, apikey.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, enterprisemember.APIKeysTable, enterprisemember.APIKeysColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUsageLogs chains the current query on the "usage_logs" edge.
func (_q *EnterpriseMemberQuery) QueryUsageLogs() *UsageLogQuery {
	query := (&UsageLogClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(enterprisemember.Table, enterprisemember.FieldID, selector),
			sqlgraph.To(usagelog.Table, usagelog.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, enterprisemember.UsageLogsTable, enterprisemember.UsageLogsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGroups chains the current query on the "groups" edge.
func (_q *EnterpriseMemberQuery) QueryGroups() *GroupQuery {
	query := (&GroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(enterprisemember.Table, enterprisemember.FieldID, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, enterprisemember.GroupsTable, enterprisemember.GroupsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBudgetPeriods chains the current query on the "budget_periods" edge.
func (_q *EnterpriseMemberQuery) QueryBudgetPeriods() *EnterpriseMemberBudgetPeriodQuery {
	query := (&EnterpriseMemberBudgetPeriodClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(enterprisemember.Table, enterprisemember.FieldID, selector),
			sqlgraph.To(enterprisememberbudgetperiod.Table, enterprisememberbudgetperiod.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, enterprisemember.BudgetPeriodsTable, enterprisemember.BudgetPeriodsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBudgetReservations chains the current query on the "budget_reservations" edge.
func (_q *EnterpriseMemberQuery) QueryBudgetReservations() *EnterpriseMemberBudgetReservationQuery {
	query := (&EnterpriseMemberBudgetReservationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(enterprisemember.Table, enterprisemember.FieldID, selector),
			sqlgraph.To(enterprisememberbudgetreservation.Table, enterprisememberbudgetreservation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, enterprisemember.BudgetReservationsTable, enterprisemember.BudgetReservationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBudgetEntries chains the current query on the "budget_entries" edge.
func (_q *EnterpriseMemberQuery) QueryBudgetEntries() *EnterpriseMemberBudgetEntryQuery {
	query := (&EnterpriseMemberBudgetEntryClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(enterprisemember.Table, enterprisemember.FieldID, selector),
			sqlgraph.To(enterprisememberbudgetentry.Table, enterprisememberbudgetentry.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, enterprisemember.BudgetEntriesTable, enterprisemember.BudgetEntriesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEnterpriseMemberGroupBindings chains the current query on the "enterprise_member_group_bindings" edge.
func (_q *EnterpriseMemberQuery) QueryEnterpriseMemberGroupBindings() *EnterpriseMemberGroupBindingQuery {
	query := (&EnterpriseMemberGroupBindingClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(enterprisemember.Table, enterprisemember.FieldID, selector),
			sqlgraph.To(enterprisemembergroupbinding.Table, enterprisemembergroupbinding.MemberColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, enterprisemember.EnterpriseMemberGroupBindingsTable, enterprisemember.EnterpriseMemberGroupBindingsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first EnterpriseMember entity from the query.
// Returns a *NotFoundError when no EnterpriseMember was found.
func (_q *EnterpriseMemberQuery) First(ctx context.Context) (*EnterpriseMember, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{enterprisemember.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *EnterpriseMemberQuery) FirstX(ctx context.Context) *EnterpriseMember {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EnterpriseMember ID from the query.
// Returns a *NotFoundError when no EnterpriseMember ID was found.
func (_q *EnterpriseMemberQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{enterprisemember.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *EnterpriseMemberQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EnterpriseMember entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EnterpriseMember entity is found.
// Returns a *NotFoundError when no EnterpriseMember entities are found.
func (_q *EnterpriseMemberQuery) Only(ctx context.Context) (*EnterpriseMember, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{enterprisemember.Label}
	default:
		return nil, &NotSingularError{enterprisemember.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *EnterpriseMemberQuery) OnlyX(ctx context.Context) *EnterpriseMember {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EnterpriseMember ID in the query.
// Returns a *NotSingularError when more than one EnterpriseMember ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *EnterpriseMemberQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{enterprisemember.Label}
	default:
		err = &NotSingularError{enterprisemember.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *EnterpriseMemberQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EnterpriseMembers.
func (_q *EnterpriseMemberQuery) All(ctx context.Context) ([]*EnterpriseMember, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EnterpriseMember, *EnterpriseMemberQuery]()
	return withInterceptors[[]*EnterpriseMember](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *EnterpriseMemberQuery) AllX(ctx context.Context) []*EnterpriseMember {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EnterpriseMember IDs.
func (_q *EnterpriseMemberQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(enterprisemember.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *EnterpriseMemberQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *EnterpriseMemberQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*EnterpriseMemberQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *EnterpriseMemberQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *EnterpriseMemberQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *EnterpriseMemberQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EnterpriseMemberQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *EnterpriseMemberQuery) Clone() *EnterpriseMemberQuery {
	if _q == nil {
		return nil
	}
	return &EnterpriseMemberQuery{
		config:                            _q.config,
		ctx:                               _q.ctx.Clone(),
		order:                             append([]enterprisemember.OrderOption{}, _q.order...),
		inters:                            append([]Interceptor{}, _q.inters...),
		predicates:                        append([]predicate.EnterpriseMember{}, _q.predicates...),
		withEnterpriseUser:                _q.withEnterpriseUser.Clone(),
		withAPIKeys:                       _q.withAPIKeys.Clone(),
		withUsageLogs:                     _q.withUsageLogs.Clone(),
		withGroups:                        _q.withGroups.Clone(),
		withBudgetPeriods:                 _q.withBudgetPeriods.Clone(),
		withBudgetReservations:            _q.withBudgetReservations.Clone(),
		withBudgetEntries:                 _q.withBudgetEntries.Clone(),
		withEnterpriseMemberGroupBindings: _q.withEnterpriseMemberGroupBindings.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithEnterpriseUser tells the query-builder to eager-load the nodes that are connected to
// the "enterprise_user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EnterpriseMemberQuery) WithEnterpriseUser(opts ...func(*UserQuery)) *EnterpriseMemberQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEnterpriseUser = query
	return _q
}

// WithAPIKeys tells the query-builder to eager-load the nodes that are connected to
// the "api_keys" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EnterpriseMemberQuery) WithAPIKeys(opts ...func(*APIKeyQuery)) *EnterpriseMemberQuery {
	query := (&APIKeyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAPIKeys = query
	return _q
}

// WithUsageLogs tells the query-builder to eager-load the nodes that are connected to
// the "usage_logs" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EnterpriseMemberQuery) WithUsageLogs(opts ...func(*UsageLogQuery)) *EnterpriseMemberQuery {
	query := (&UsageLogClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUsageLogs = query
	return _q
}

// WithGroups tells the query-builder to eager-load the nodes that are connected to
// the "groups" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EnterpriseMemberQuery) WithGroups(opts ...func(*GroupQuery)) *EnterpriseMemberQuery {
	query := (&GroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGroups = query
	return _q
}

// WithBudgetPeriods tells the query-builder to eager-load the nodes that are connected to
// the "budget_periods" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EnterpriseMemberQuery) WithBudgetPeriods(opts ...func(*EnterpriseMemberBudgetPeriodQuery)) *EnterpriseMemberQuery {
	query := (&EnterpriseMemberBudgetPeriodClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBudgetPeriods = query
	return _q
}

// WithBudgetReservations tells the query-builder to eager-load the nodes that are connected to
// the "budget_reservations" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EnterpriseMemberQuery) WithBudgetReservations(opts ...func(*EnterpriseMemberBudgetReservationQuery)) *EnterpriseMemberQuery {
	query := (&EnterpriseMemberBudgetReservationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBudgetReservations = query
	return _q
}

// WithBudgetEntries tells the query-builder to eager-load the nodes that are connected to
// the "budget_entries" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EnterpriseMemberQuery) WithBudgetEntries(opts ...func(*EnterpriseMemberBudgetEntryQuery)) *EnterpriseMemberQuery {
	query := (&EnterpriseMemberBudgetEntryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBudgetEntries = query
	return _q
}

// WithEnterpriseMemberGroupBindings tells the query-builder to eager-load the nodes that are connected to
// the "enterprise_member_group_bindings" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EnterpriseMemberQuery) WithEnterpriseMemberGroupBindings(opts ...func(*EnterpriseMemberGroupBindingQuery)) *EnterpriseMemberQuery {
	query := (&EnterpriseMemberGroupBindingClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEnterpriseMemberGroupBindings = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EnterpriseMember.Query().
//		GroupBy(enterprisemember.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *EnterpriseMemberQuery) GroupBy(field string, fields ...string) *EnterpriseMemberGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EnterpriseMemberGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = enterprisemember.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.EnterpriseMember.Query().
//		Select(enterprisemember.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *EnterpriseMemberQuery) Select(fields ...string) *EnterpriseMemberSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &EnterpriseMemberSelect{EnterpriseMemberQuery: _q}
	sbuild.label = enterprisemember.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EnterpriseMemberSelect configured with the given aggregations.
func (_q *EnterpriseMemberQuery) Aggregate(fns ...AggregateFunc) *EnterpriseMemberSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *EnterpriseMemberQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !enterprisemember.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *EnterpriseMemberQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EnterpriseMember, error) {
	var (
		nodes       = []*EnterpriseMember{}
		_spec       = _q.querySpec()
		loadedTypes = [8]bool{
			_q.withEnterpriseUser != nil,
			_q.withAPIKeys != nil,
			_q.withUsageLogs != nil,
			_q.withGroups != nil,
			_q.withBudgetPeriods != nil,
			_q.withBudgetReservations != nil,
			_q.withBudgetEntries != nil,
			_q.withEnterpriseMemberGroupBindings != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EnterpriseMember).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EnterpriseMember{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withEnterpriseUser; query != nil {
		if err := _q.loadEnterpriseUser(ctx, query, nodes, nil,
			func(n *EnterpriseMember, e *User) { n.Edges.EnterpriseUser = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAPIKeys; query != nil {
		if err := _q.loadAPIKeys(ctx, query, nodes,
			func(n *EnterpriseMember) { n.Edges.APIKeys = []*APIKey{} },
			func(n *EnterpriseMember, e *APIKey) { n.Edges.APIKeys = append(n.Edges.APIKeys, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUsageLogs; query != nil {
		if err := _q.loadUsageLogs(ctx, query, nodes,
			func(n *EnterpriseMember) { n.Edges.UsageLogs = []*UsageLog{} },
			func(n *EnterpriseMember, e *UsageLog) { n.Edges.UsageLogs = append(n.Edges.UsageLogs, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGroups; query != nil {
		if err := _q.loadGroups(ctx, query, nodes,
			func(n *EnterpriseMember) { n.Edges.Groups = []*Group{} },
			func(n *EnterpriseMember, e *Group) { n.Edges.Groups = append(n.Edges.Groups, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withBudgetPeriods; query != nil {
		if err := _q.loadBudgetPeriods(ctx, query, nodes,
			func(n *EnterpriseMember) { n.Edges.BudgetPeriods = []*EnterpriseMemberBudgetPeriod{} },
			func(n *EnterpriseMember, e *EnterpriseMemberBudgetPeriod) {
				n.Edges.BudgetPeriods = append(n.Edges.BudgetPeriods, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withBudgetReservations; query != nil {
		if err := _q.loadBudgetReservations(ctx, query, nodes,
			func(n *EnterpriseMember) { n.Edges.BudgetReservations = []*EnterpriseMemberBudgetReservation{} },
			func(n *EnterpriseMember, e *EnterpriseMemberBudgetReservation) {
				n.Edges.BudgetReservations = append(n.Edges.BudgetReservations, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withBudgetEntries; query != nil {
		if err := _q.loadBudgetEntries(ctx, query, nodes,
			func(n *EnterpriseMember) { n.Edges.BudgetEntries = []*EnterpriseMemberBudgetEntry{} },
			func(n *EnterpriseMember, e *EnterpriseMemberBudgetEntry) {
				n.Edges.BudgetEntries = append(n.Edges.BudgetEntries, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withEnterpriseMemberGroupBindings; query != nil {
		if err := _q.loadEnterpriseMemberGroupBindings(ctx, query, nodes,
			func(n *EnterpriseMember) { n.Edges.EnterpriseMemberGroupBindings = []*EnterpriseMemberGroupBinding{} },
			func(n *EnterpriseMember, e *EnterpriseMemberGroupBinding) {
				n.Edges.EnterpriseMemberGroupBindings = append(n.Edges.EnterpriseMemberGroupBindings, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *EnterpriseMemberQuery) loadEnterpriseUser(ctx context.Context, query *UserQuery, nodes []*EnterpriseMember, init func(*EnterpriseMember), assign func(*EnterpriseMember, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*EnterpriseMember)
	for i := range nodes {
		fk := nodes[i].EnterpriseUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "enterprise_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *EnterpriseMemberQuery) loadAPIKeys(ctx context.Context, query *APIKeyQuery, nodes []*EnterpriseMember, init func(*EnterpriseMember), assign func(*EnterpriseMember, *APIKey)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*EnterpriseMember)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(apikey.FieldMemberID)
	}
	query.Where(predicate.APIKey(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(enterprisemember.APIKeysColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.MemberID
		if fk == nil {
			return fmt.Errorf(`foreign-key "member_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "member_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *EnterpriseMemberQuery) loadUsageLogs(ctx context.Context, query *UsageLogQuery, nodes []*EnterpriseMember, init func(*EnterpriseMember), assign func(*EnterpriseMember, *UsageLog)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*EnterpriseMember)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(usagelog.FieldMemberID)
	}
	query.Where(predicate.UsageLog(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(enterprisemember.UsageLogsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.MemberID
		if fk == nil {
			return fmt.Errorf(`foreign-key "member_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "member_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *EnterpriseMemberQuery) loadGroups(ctx context.Context, query *GroupQuery, nodes []*EnterpriseMember, init func(*EnterpriseMember), assign func(*EnterpriseMember, *Group)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int64]*EnterpriseMember)
	nids := make(map[int64]map[*EnterpriseMember]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(enterprisemember.GroupsTable)
		s.Join(joinT).On(s.C(group.FieldID), joinT.C(enterprisemember.GroupsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(enterprisemember.GroupsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(enterprisemember.GroupsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := values[0].(*sql.NullInt64).Int64
				inValue := values[1].(*sql.NullInt64).Int64
				if nids[inValue] == nil {
					nids[inValue] = map[*EnterpriseMember]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Group](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "groups" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *EnterpriseMemberQuery) loadBudgetPeriods(ctx context.Context, query *EnterpriseMemberBudgetPeriodQuery, nodes []*EnterpriseMember, init func(*EnterpriseMember), assign func(*EnterpriseMember, *EnterpriseMemberBudgetPeriod)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*EnterpriseMember)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(enterprisememberbudgetperiod.FieldMemberID)
	}
	query.Where(predicate.EnterpriseMemberBudgetPeriod(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(enterprisemember.BudgetPeriodsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.MemberID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "member_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *EnterpriseMemberQuery) loadBudgetReservations(ctx context.Context, query *EnterpriseMemberBudgetReservationQuery, nodes []*EnterpriseMember, init func(*EnterpriseMember), assign func(*EnterpriseMember, *EnterpriseMemberBudgetReservation)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*EnterpriseMember)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(enterprisememberbudgetreservation.FieldMemberID)
	}
	query.Where(predicate.EnterpriseMemberBudgetReservation(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(enterprisemember.BudgetReservationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.MemberID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "member_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *EnterpriseMemberQuery) loadBudgetEntries(ctx context.Context, query *EnterpriseMemberBudgetEntryQuery, nodes []*EnterpriseMember, init func(*EnterpriseMember), assign func(*EnterpriseMember, *EnterpriseMemberBudgetEntry)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*EnterpriseMember)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(enterprisememberbudgetentry.FieldMemberID)
	}
	query.Where(predicate.EnterpriseMemberBudgetEntry(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(enterprisemember.BudgetEntriesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.MemberID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "member_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *EnterpriseMemberQuery) loadEnterpriseMemberGroupBindings(ctx context.Context, query *EnterpriseMemberGroupBindingQuery, nodes []*EnterpriseMember, init func(*EnterpriseMember), assign func(*EnterpriseMember, *EnterpriseMemberGroupBinding)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*EnterpriseMember)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(enterprisemembergroupbinding.FieldMemberID)
	}
	query.Where(predicate.EnterpriseMemberGroupBinding(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(enterprisemember.EnterpriseMemberGroupBindingsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.MemberID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "member_id" returned %v for node %v`, fk, n)
		}
		assign(node, n)
	}
	return nil
}

func (_q *EnterpriseMemberQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *EnterpriseMemberQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(enterprisemember.Table, enterprisemember.Columns, sqlgraph.NewFieldSpec(enterprisemember.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, enterprisemember.FieldID)
		for i := range fields {
			if fields[i] != enterprisemember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withEnterpriseUser != nil {
			_spec.Node.AddColumnOnce(enterprisemember.FieldEnterpriseUserID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *EnterpriseMemberQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(enterprisemember.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = enterprisemember.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *EnterpriseMemberQuery) ForUpdate(opts ...sql.LockOption) *EnterpriseMemberQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *EnterpriseMemberQuery) ForShare(opts ...sql.LockOption) *EnterpriseMemberQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// EnterpriseMemberGroupBy is the group-by builder for EnterpriseMember entities.
type EnterpriseMemberGroupBy struct {
	selector
	build *EnterpriseMemberQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *EnterpriseMemberGroupBy) Aggregate(fns ...AggregateFunc) *EnterpriseMemberGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *EnterpriseMemberGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EnterpriseMemberQuery, *EnterpriseMemberGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *EnterpriseMemberGroupBy) sqlScan(ctx context.Context, root *EnterpriseMemberQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EnterpriseMemberSelect is the builder for selecting fields of EnterpriseMember entities.
type EnterpriseMemberSelect struct {
	*EnterpriseMemberQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *EnterpriseMemberSelect) Aggregate(fns ...AggregateFunc) *EnterpriseMemberSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *EnterpriseMemberSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EnterpriseMemberQuery, *EnterpriseMemberSelect](ctx, _s.EnterpriseMemberQuery, _s, _s.inters, v)
}

func (_s *EnterpriseMemberSelect) sqlScan(ctx context.Context, root *EnterpriseMemberQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
