// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/enterprisemember"
	"github.com/Wei-Shaw/sub2api/ent/enterprisemembergroupbinding"
	"github.com/Wei-Shaw/sub2api/ent/group"
)

// EnterpriseMemberGroupBindingCreate is the builder for creating a EnterpriseMemberGroupBinding entity.
type EnterpriseMemberGroupBindingCreate struct {
	config
	mutation *EnterpriseMemberGroupBindingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetMemberID sets the "member_id" field.
func (_c *EnterpriseMemberGroupBindingCreate) SetMemberID(v int64) *EnterpriseMemberGroupBindingCreate {
	_c.mutation.SetMemberID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *EnterpriseMemberGroupBindingCreate) SetGroupID(v int64) *EnterpriseMemberGroupBindingCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *EnterpriseMemberGroupBindingCreate) SetSortOrder(v int) *EnterpriseMemberGroupBindingCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EnterpriseMemberGroupBindingCreate) SetCreatedAt(v time.Time) *EnterpriseMemberGroupBindingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EnterpriseMemberGroupBindingCreate) SetNillableCreatedAt(v *time.Time) *EnterpriseMemberGroupBindingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EnterpriseMemberGroupBindingCreate) SetUpdatedAt(v time.Time) *EnterpriseMemberGroupBindingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EnterpriseMemberGroupBindingCreate) SetNillableUpdatedAt(v *time.Time) *EnterpriseMemberGroupBindingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetMember sets the "member" edge to the EnterpriseMember entity.
func (_c *EnterpriseMemberGroupBindingCreate) SetMember(v *EnterpriseMember) *EnterpriseMemberGroupBindingCreate {
	return _c.SetMemberID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *EnterpriseMemberGroupBindingCreate) SetGroup(v *Group) *EnterpriseMemberGroupBindingCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the EnterpriseMemberGroupBindingMutation object of the builder.
func (_c *EnterpriseMemberGroupBindingCreate) Mutation() *EnterpriseMemberGroupBindingMutation {
	return _c.mutation
}

// Save creates the EnterpriseMemberGroupBinding in the database.
func (_c *EnterpriseMemberGroupBindingCreate) Save(ctx context.Context) (*EnterpriseMemberGroupBinding, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EnterpriseMemberGroupBindingCreate) SaveX(ctx context.Context) *EnterpriseMemberGroupBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnterpriseMemberGroupBindingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnterpriseMemberGroupBindingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EnterpriseMemberGroupBindingCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := enterprisemembergroupbinding.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := enterprisemembergroupbinding.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EnterpriseMemberGroupBindingCreate) check() error {
	if _, ok := _c.mutation.MemberID(); !ok {
		return &ValidationError{Name: "member_id", err: errors.New(`ent: missing required field "EnterpriseMemberGroupBinding.member_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "EnterpriseMemberGroupBinding.group_id"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "EnterpriseMemberGroupBinding.sort_order"`)}
	}
	if v, ok := _c.mutation.SortOrder(); ok {
		if err := enterprisemembergroupbinding.SortOrderValidator(v); err != nil {
			return &ValidationError{Name: "sort_order", err: fmt.Errorf(`ent: validator failed for field "EnterpriseMemberGroupBinding.sort_order": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EnterpriseMemberGroupBinding.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EnterpriseMemberGroupBinding.updated_at"`)}
	}
	if len(_c.mutation.MemberIDs()) == 0 {
		return &ValidationError{Name: "member", err: errors.New(`ent: missing required edge "EnterpriseMemberGroupBinding.member"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "EnterpriseMemberGroupBinding.group"`)}
	}
	return nil
}

func (_c *EnterpriseMemberGroupBindingCreate) sqlSave(ctx context.Context) (*EnterpriseMemberGroupBinding, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *EnterpriseMemberGroupBindingCreate) createSpec() (*EnterpriseMemberGroupBinding, *sqlgraph.CreateSpec) {
	var (
		_node = &EnterpriseMemberGroupBinding{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(enterprisemembergroupbinding.Table, nil)
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(enterprisemembergroupbinding.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(enterprisemembergroupbinding.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(enterprisemembergroupbinding.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enterprisemembergroupbinding.MemberTable,
			Columns: []string{enterprisemembergroupbinding.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisemember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MemberID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enterprisemembergroupbinding.GroupTable,
			Columns: []string{enterprisemembergroupbinding.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EnterpriseMemberGroupBinding.Create().
//		SetMemberID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EnterpriseMemberGroupBindingUpsert) {
//			SetMemberID(v+v).
//		}).
//		Exec(ctx)
func (_c *EnterpriseMemberGroupBindingCreate) OnConflict(opts ...sql.ConflictOption) *EnterpriseMemberGroupBindingUpsertOne {
	_c.conflict = opts
	return &EnterpriseMemberGroupBindingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EnterpriseMemberGroupBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EnterpriseMemberGroupBindingCreate) OnConflictColumns(columns ...string) *EnterpriseMemberGroupBindingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EnterpriseMemberGroupBindingUpsertOne{
		create: _c,
	}
}

type (
	// EnterpriseMemberGroupBindingUpsertOne is the builder for "upsert"-ing
	//  one EnterpriseMemberGroupBinding node.
	EnterpriseMemberGroupBindingUpsertOne struct {
		create *EnterpriseMemberGroupBindingCreate
	}

	// EnterpriseMemberGroupBindingUpsert is the "OnConflict" setter.
	EnterpriseMemberGroupBindingUpsert struct {
		*sql.UpdateSet
	}
)

// SetMemberID sets the "member_id" field.
func (u *EnterpriseMemberGroupBindingUpsert) SetMemberID(v int64) *EnterpriseMemberGroupBindingUpsert {
	u.Set(enterprisemembergroupbinding.FieldMemberID, v)
	return u
}

// UpdateMemberID sets the "member_id" field to the value that was provided on create.
func (u *EnterpriseMemberGroupBindingUpsert) UpdateMemberID() *EnterpriseMemberGroupBindingUpsert {
	u.SetExcluded(enterprisemembergroupbinding.FieldMemberID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *EnterpriseMemberGroupBindingUpsert) SetGroupID(v int64) *EnterpriseMemberGroupBindingUpsert {
	u.Set(enterprisemembergroupbinding.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *EnterpriseMemberGroupBindingUpsert) UpdateGroupID() *EnterpriseMemberGroupBindingUpsert {
	u.SetExcluded(enterprisemembergroupbinding.FieldGroupID)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *EnterpriseMemberGroupBindingUpsert) SetSortOrder(v int) *EnterpriseMemberGroupBindingUpsert {
	u.Set(enterprisemembergroupbinding.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *EnterpriseMemberGroupBindingUpsert) UpdateSortOrder() *EnterpriseMemberGroupBindingUpsert {
	u.SetExcluded(enterprisemembergroupbinding.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *EnterpriseMemberGroupBindingUpsert) AddSortOrder(v int) *EnterpriseMemberGroupBindingUpsert {
	u.Add(enterprisemembergroupbinding.FieldSortOrder, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EnterpriseMemberGroupBindingUpsert) SetUpdatedAt(v time.Time) *EnterpriseMemberGroupBindingUpsert {
	u.Set(enterprisemembergroupbinding.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnterpriseMemberGroupBindingUpsert) UpdateUpdatedAt() *EnterpriseMemberGroupBindingUpsert {
	u.SetExcluded(enterprisemembergroupbinding.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.EnterpriseMemberGroupBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EnterpriseMemberGroupBindingUpsertOne) UpdateNewValues() *EnterpriseMemberGroupBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(enterprisemembergroupbinding.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EnterpriseMemberGroupBinding.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EnterpriseMemberGroupBindingUpsertOne) Ignore() *EnterpriseMemberGroupBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EnterpriseMemberGroupBindingUpsertOne) DoNothing() *EnterpriseMemberGroupBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EnterpriseMemberGroupBindingCreate.OnConflict
// documentation for more info.
func (u *EnterpriseMemberGroupBindingUpsertOne) Update(set func(*EnterpriseMemberGroupBindingUpsert)) *EnterpriseMemberGroupBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EnterpriseMemberGroupBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetMemberID sets the "member_id" field.
func (u *EnterpriseMemberGroupBindingUpsertOne) SetMemberID(v int64) *EnterpriseMemberGroupBindingUpsertOne {
	return u.Update(func(s *EnterpriseMemberGroupBindingUpsert) {
		s.SetMemberID(v)
	})
}

// UpdateMemberID sets the "member_id" field to the value that was provided on create.
func (u *EnterpriseMemberGroupBindingUpsertOne) UpdateMemberID() *EnterpriseMemberGroupBindingUpsertOne {
	return u.Update(func(s *EnterpriseMemberGroupBindingUpsert) {
		s.UpdateMemberID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *EnterpriseMemberGroupBindingUpsertOne) SetGroupID(v int64) *EnterpriseMemberGroupBindingUpsertOne {
	return u.Update(func(s *EnterpriseMemberGroupBindingUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *EnterpriseMemberGroupBindingUpsertOne) UpdateGroupID() *EnterpriseMemberGroupBindingUpsertOne {
	return u.Update(func(s *EnterpriseMemberGroupBindingUpsert) {
		s.UpdateGroupID()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *EnterpriseMemberGroupBindingUpsertOne) SetSortOrder(v int) *EnterpriseMemberGroupBindingUpsertOne {
	return u.Update(func(s *EnterpriseMemberGroupBindingUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *EnterpriseMemberGroupBindingUpsertOne) AddSortOrder(v int) *EnterpriseMemberGroupBindingUpsertOne {
	return u.Update(func(s *EnterpriseMemberGroupBindingUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *EnterpriseMemberGroupBindingUpsertOne) UpdateSortOrder() *EnterpriseMemberGroupBindingUpsertOne {
	return u.Update(func(s *EnterpriseMemberGroupBindingUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EnterpriseMemberGroupBindingUpsertOne) SetUpdatedAt(v time.Time) *EnterpriseMemberGroupBindingUpsertOne {
	return u.Update(func(s *EnterpriseMemberGroupBindingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnterpriseMemberGroupBindingUpsertOne) UpdateUpdatedAt() *EnterpriseMemberGroupBindingUpsertOne {
	return u.Update(func(s *EnterpriseMemberGroupBindingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *EnterpriseMemberGroupBindingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EnterpriseMemberGroupBindingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EnterpriseMemberGroupBindingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// EnterpriseMemberGroupBindingCreateBulk is the builder for creating many EnterpriseMemberGroupBinding entities in bulk.
type EnterpriseMemberGroupBindingCreateBulk struct {
	config
	err      error
	builders []*EnterpriseMemberGroupBindingCreate
	conflict []sql.ConflictOption
}

// Save creates the EnterpriseMemberGroupBinding entities in the database.
func (_c *EnterpriseMemberGroupBindingCreateBulk) Save(ctx context.Context) ([]*EnterpriseMemberGroupBinding, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EnterpriseMemberGroupBinding, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EnterpriseMemberGroupBindingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EnterpriseMemberGroupBindingCreateBulk) SaveX(ctx context.Context) []*EnterpriseMemberGroupBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnterpriseMemberGroupBindingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnterpriseMemberGroupBindingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EnterpriseMemberGroupBinding.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EnterpriseMemberGroupBindingUpsert) {
//			SetMemberID(v+v).
//		}).
//		Exec(ctx)
func (_c *EnterpriseMemberGroupBindingCreateBulk) OnConflict(opts ...sql.ConflictOption) *EnterpriseMemberGroupBindingUpsertBulk {
	_c.conflict = opts
	return &EnterpriseMemberGroupBindingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EnterpriseMemberGroupBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EnterpriseMemberGroupBindingCreateBulk) OnConflictColumns(columns ...string) *EnterpriseMemberGroupBindingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EnterpriseMemberGroupBindingUpsertBulk{
		create: _c,
	}
}

// EnterpriseMemberGroupBindingUpsertBulk is the builder for "upsert"-ing
// a bulk of EnterpriseMemberGroupBinding nodes.
type EnterpriseMemberGroupBindingUpsertBulk struct {
	create *EnterpriseMemberGroupBindingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.EnterpriseMemberGroupBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EnterpriseMemberGroupBindingUpsertBulk) UpdateNewValues() *EnterpriseMemberGroupBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(enterprisemembergroupbinding.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EnterpriseMemberGroupBinding.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EnterpriseMemberGroupBindingUpsertBulk) Ignore() *EnterpriseMemberGroupBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EnterpriseMemberGroupBindingUpsertBulk) DoNothing() *EnterpriseMemberGroupBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EnterpriseMemberGroupBindingCreateBulk.OnConflict
// documentation for more info.
func (u *EnterpriseMemberGroupBindingUpsertBulk) Update(set func(*EnterpriseMemberGroupBindingUpsert)) *EnterpriseMemberGroupBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EnterpriseMemberGroupBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetMemberID sets the "member_id" field.
func (u *EnterpriseMemberGroupBindingUpsertBulk) SetMemberID(v int64) *EnterpriseMemberGroupBindingUpsertBulk {
	return u.Update(func(s *EnterpriseMemberGroupBindingUpsert) {
		s.SetMemberID(v)
	})
}

// UpdateMemberID sets the "member_id" field to the value that was provided on create.
func (u *EnterpriseMemberGroupBindingUpsertBulk) UpdateMemberID() *EnterpriseMemberGroupBindingUpsertBulk {
	return u.Update(func(s *EnterpriseMemberGroupBindingUpsert) {
		s.UpdateMemberID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *EnterpriseMemberGroupBindingUpsertBulk) SetGroupID(v int64) *EnterpriseMemberGroupBindingUpsertBulk {
	return u.Update(func(s *EnterpriseMemberGroupBindingUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *EnterpriseMemberGroupBindingUpsertBulk) UpdateGroupID() *EnterpriseMemberGroupBindingUpsertBulk {
	return u.Update(func(s *EnterpriseMemberGroupBindingUpsert) {
		s.UpdateGroupID()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *EnterpriseMemberGroupBindingUpsertBulk) SetSortOrder(v int) *EnterpriseMemberGroupBindingUpsertBulk {
	return u.Update(func(s *EnterpriseMemberGroupBindingUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *EnterpriseMemberGroupBindingUpsertBulk) AddSortOrder(v int) *EnterpriseMemberGroupBindingUpsertBulk {
	return u.Update(func(s *EnterpriseMemberGroupBindingUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *EnterpriseMemberGroupBindingUpsertBulk) UpdateSortOrder() *EnterpriseMemberGroupBindingUpsertBulk {
	return u.Update(func(s *EnterpriseMemberGroupBindingUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EnterpriseMemberGroupBindingUpsertBulk) SetUpdatedAt(v time.Time) *EnterpriseMemberGroupBindingUpsertBulk {
	return u.Update(func(s *EnterpriseMemberGroupBindingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnterpriseMemberGroupBindingUpsertBulk) UpdateUpdatedAt() *EnterpriseMemberGroupBindingUpsertBulk {
	return u.Update(func(s *EnterpriseMemberGroupBindingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *EnterpriseMemberGroupBindingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EnterpriseMemberGroupBindingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EnterpriseMemberGroupBindingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EnterpriseMemberGroupBindingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
