// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/enterprisemember"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// EnterpriseMember is the model entity for the EnterpriseMember schema.
type EnterpriseMember struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// EnterpriseUserID holds the value of the "enterprise_user_id" field.
	EnterpriseUserID int64 `json:"enterprise_user_id,omitempty"`
	// MemberCode holds the value of the "member_code" field.
	MemberCode string `json:"member_code,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// MonthlyLimitUsd holds the value of the "monthly_limit_usd" field.
	MonthlyLimitUsd float64 `json:"monthly_limit_usd,omitempty"`
	// RateLimit5h holds the value of the "rate_limit_5h" field.
	RateLimit5h float64 `json:"rate_limit_5h,omitempty"`
	// RateLimit1d holds the value of the "rate_limit_1d" field.
	RateLimit1d float64 `json:"rate_limit_1d,omitempty"`
	// RateLimit7d holds the value of the "rate_limit_7d" field.
	RateLimit7d float64 `json:"rate_limit_7d,omitempty"`
	// Version holds the value of the "version" field.
	Version int64 `json:"version,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EnterpriseMemberQuery when eager-loading is set.
	Edges        EnterpriseMemberEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EnterpriseMemberEdges holds the relations/edges for other nodes in the graph.
type EnterpriseMemberEdges struct {
	// EnterpriseUser holds the value of the enterprise_user edge.
	EnterpriseUser *User `json:"enterprise_user,omitempty"`
	// APIKeys holds the value of the api_keys edge.
	APIKeys []*APIKey `json:"api_keys,omitempty"`
	// UsageLogs holds the value of the usage_logs edge.
	UsageLogs []*UsageLog `json:"usage_logs,omitempty"`
	// Groups holds the value of the groups edge.
	Groups []*Group `json:"groups,omitempty"`
	// BudgetPeriods holds the value of the budget_periods edge.
	BudgetPeriods []*EnterpriseMemberBudgetPeriod `json:"budget_periods,omitempty"`
	// BudgetReservations holds the value of the budget_reservations edge.
	BudgetReservations []*EnterpriseMemberBudgetReservation `json:"budget_reservations,omitempty"`
	// BudgetEntries holds the value of the budget_entries edge.
	BudgetEntries []*EnterpriseMemberBudgetEntry `json:"budget_entries,omitempty"`
	// EnterpriseMemberGroupBindings holds the value of the enterprise_member_group_bindings edge.
	EnterpriseMemberGroupBindings []*EnterpriseMemberGroupBinding `json:"enterprise_member_group_bindings,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [8]bool
}

// EnterpriseUserOrErr returns the EnterpriseUser value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EnterpriseMemberEdges) EnterpriseUserOrErr() (*User, error) {
	if e.EnterpriseUser != nil {
		return e.EnterpriseUser, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "enterprise_user"}
}

// APIKeysOrErr returns the APIKeys value or an error if the edge
// was not loaded in eager-loading.
func (e EnterpriseMemberEdges) APIKeysOrErr() ([]*APIKey, error) {
	if e.loadedTypes[1] {
		return e.APIKeys, nil
	}
	return nil, &NotLoadedError{edge: "api_keys"}
}

// UsageLogsOrErr returns the UsageLogs value or an error if the edge
// was not loaded in eager-loading.
func (e EnterpriseMemberEdges) UsageLogsOrErr() ([]*UsageLog, error) {
	if e.loadedTypes[2] {
		return e.UsageLogs, nil
	}
	return nil, &NotLoadedError{edge: "usage_logs"}
}

// GroupsOrErr returns the Groups value or an error if the edge
// was not loaded in eager-loading.
func (e EnterpriseMemberEdges) GroupsOrErr() ([]*Group, error) {
	if e.loadedTypes[3] {
		return e.Groups, nil
	}
	return nil, &NotLoadedError{edge: "groups"}
}

// BudgetPeriodsOrErr returns the BudgetPeriods value or an error if the edge
// was not loaded in eager-loading.
func (e EnterpriseMemberEdges) BudgetPeriodsOrErr() ([]*EnterpriseMemberBudgetPeriod, error) {
	if e.loadedTypes[4] {
		return e.BudgetPeriods, nil
	}
	return nil, &NotLoadedError{edge: "budget_periods"}
}

// BudgetReservationsOrErr returns the BudgetReservations value or an error if the edge
// was not loaded in eager-loading.
func (e EnterpriseMemberEdges) BudgetReservationsOrErr() ([]*EnterpriseMemberBudgetReservation, error) {
	if e.loadedTypes[5] {
		return e.BudgetReservations, nil
	}
	return nil, &NotLoadedError{edge: "budget_reservations"}
}

// BudgetEntriesOrErr returns the BudgetEntries value or an error if the edge
// was not loaded in eager-loading.
func (e EnterpriseMemberEdges) BudgetEntriesOrErr() ([]*EnterpriseMemberBudgetEntry, error) {
	if e.loadedTypes[6] {
		return e.BudgetEntries, nil
	}
	return nil, &NotLoadedError{edge: "budget_entries"}
}

// EnterpriseMemberGroupBindingsOrErr returns the EnterpriseMemberGroupBindings value or an error if the edge
// was not loaded in eager-loading.
func (e EnterpriseMemberEdges) EnterpriseMemberGroupBindingsOrErr() ([]*EnterpriseMemberGroupBinding, error) {
	if e.loadedTypes[7] {
		return e.EnterpriseMemberGroupBindings, nil
	}
	return nil, &NotLoadedError{edge: "enterprise_member_group_bindings"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EnterpriseMember) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case enterprisemember.FieldMonthlyLimitUsd, enterprisemember.FieldRateLimit5h, enterprisemember.FieldRateLimit1d, enterprisemember.FieldRateLimit7d:
			values[i] = new(sql.NullFloat64)
		case enterprisemember.FieldID, enterprisemember.FieldEnterpriseUserID, enterprisemember.FieldVersion:
			values[i] = new(sql.NullInt64)
		case enterprisemember.FieldMemberCode, enterprisemember.FieldName, enterprisemember.FieldStatus:
			values[i] = new(sql.NullString)
		case enterprisemember.FieldCreatedAt, enterprisemember.FieldUpdatedAt, enterprisemember.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EnterpriseMember fields.
func (_m *EnterpriseMember) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case enterprisemember.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case enterprisemember.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case enterprisemember.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case enterprisemember.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case enterprisemember.FieldEnterpriseUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field enterprise_user_id", values[i])
			} else if value.Valid {
				_m.EnterpriseUserID = value.Int64
			}
		case enterprisemember.FieldMemberCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field member_code", values[i])
			} else if value.Valid {
				_m.MemberCode = value.String
			}
		case enterprisemember.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case enterprisemember.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case enterprisemember.FieldMonthlyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_limit_usd", values[i])
			} else if value.Valid {
				_m.MonthlyLimitUsd = value.Float64
			}
		case enterprisemember.FieldRateLimit5h:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rate_limit_5h", values[i])
			} else if value.Valid {
				_m.RateLimit5h = value.Float64
			}
		case enterprisemember.FieldRateLimit1d:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rate_limit_1d", values[i])
			} else if value.Valid {
				_m.RateLimit1d = value.Float64
			}
		case enterprisemember.FieldRateLimit7d:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rate_limit_7d", values[i])
			} else if value.Valid {
				_m.RateLimit7d = value.Float64
			}
		case enterprisemember.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EnterpriseMember.
// This includes values selected through modifiers, order, etc.
func (_m *EnterpriseMember) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEnterpriseUser queries the "enterprise_user" edge of the EnterpriseMember entity.
func (_m *EnterpriseMember) QueryEnterpriseUser() *UserQuery {
	return NewEnterpriseMemberClient(_m.config).QueryEnterpriseUser(_m)
}

// QueryAPIKeys queries the "api_keys" edge of the EnterpriseMember entity.
func (_m *EnterpriseMember) QueryAPIKeys() *APIKeyQuery {
	return NewEnterpriseMemberClient(_m.config).QueryAPIKeys(_m)
}

// QueryUsageLogs queries the "usage_logs" edge of the EnterpriseMember entity.
func (_m *EnterpriseMember) QueryUsageLogs() *UsageLogQuery {
	return NewEnterpriseMemberClient(_m.config).QueryUsageLogs(_m)
}

// QueryGroups queries the "groups" edge of the EnterpriseMember entity.
func (_m *EnterpriseMember) QueryGroups() *GroupQuery {
	return NewEnterpriseMemberClient(_m.config).QueryGroups(_m)
}

// QueryBudgetPeriods queries the "budget_periods" edge of the EnterpriseMember entity.
func (_m *EnterpriseMember) QueryBudgetPeriods() *EnterpriseMemberBudgetPeriodQuery {
	return NewEnterpriseMemberClient(_m.config).QueryBudgetPeriods(_m)
}

// QueryBudgetReservations queries the "budget_reservations" edge of the EnterpriseMember entity.
func (_m *EnterpriseMember) QueryBudgetReservations() *EnterpriseMemberBudgetReservationQuery {
	return NewEnterpriseMemberClient(_m.config).QueryBudgetReservations(_m)
}

// QueryBudgetEntries queries the "budget_entries" edge of the EnterpriseMember entity.
func (_m *EnterpriseMember) QueryBudgetEntries() *EnterpriseMemberBudgetEntryQuery {
	return NewEnterpriseMemberClient(_m.config).QueryBudgetEntries(_m)
}

// QueryEnterpriseMemberGroupBindings queries the "enterprise_member_group_bindings" edge of the EnterpriseMember entity.
func (_m *EnterpriseMember) QueryEnterpriseMemberGroupBindings() *EnterpriseMemberGroupBindingQuery {
	return NewEnterpriseMemberClient(_m.config).QueryEnterpriseMemberGroupBindings(_m)
}

// Update returns a builder for updating this EnterpriseMember.
// Note that you need to call EnterpriseMember.Unwrap() before calling this method if this EnterpriseMember
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EnterpriseMember) Update() *EnterpriseMemberUpdateOne {
	return NewEnterpriseMemberClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EnterpriseMember entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EnterpriseMember) Unwrap() *EnterpriseMember {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EnterpriseMember is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EnterpriseMember) String() string {
	var builder strings.Builder
	builder.WriteString("EnterpriseMember(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("enterprise_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EnterpriseUserID))
	builder.WriteString(", ")
	builder.WriteString("member_code=")
	builder.WriteString(_m.MemberCode)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("monthly_limit_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.MonthlyLimitUsd))
	builder.WriteString(", ")
	builder.WriteString("rate_limit_5h=")
	builder.WriteString(fmt.Sprintf("%v", _m.RateLimit5h))
	builder.WriteString(", ")
	builder.WriteString("rate_limit_1d=")
	builder.WriteString(fmt.Sprintf("%v", _m.RateLimit1d))
	builder.WriteString(", ")
	builder.WriteString("rate_limit_7d=")
	builder.WriteString(fmt.Sprintf("%v", _m.RateLimit7d))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteByte(')')
	return builder.String()
}

// EnterpriseMembers is a parsable slice of EnterpriseMember.
type EnterpriseMembers []*EnterpriseMember
