// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/enterprisemember"
	"github.com/Wei-Shaw/sub2api/ent/enterprisememberbudgetperiod"
)

// EnterpriseMemberBudgetPeriodCreate is the builder for creating a EnterpriseMemberBudgetPeriod entity.
type EnterpriseMemberBudgetPeriodCreate struct {
	config
	mutation *EnterpriseMemberBudgetPeriodMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetMemberID sets the "member_id" field.
func (_c *EnterpriseMemberBudgetPeriodCreate) SetMemberID(v int64) *EnterpriseMemberBudgetPeriodCreate {
	_c.mutation.SetMemberID(v)
	return _c
}

// SetPeriodStart sets the "period_start" field.
func (_c *EnterpriseMemberBudgetPeriodCreate) SetPeriodStart(v time.Time) *EnterpriseMemberBudgetPeriodCreate {
	_c.mutation.SetPeriodStart(v)
	return _c
}

// SetTimezone sets the "timezone" field.
func (_c *EnterpriseMemberBudgetPeriodCreate) SetTimezone(v string) *EnterpriseMemberBudgetPeriodCreate {
	_c.mutation.SetTimezone(v)
	return _c
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_c *EnterpriseMemberBudgetPeriodCreate) SetNillableTimezone(v *string) *EnterpriseMemberBudgetPeriodCreate {
	if v != nil {
		_c.SetTimezone(*v)
	}
	return _c
}

// SetUsedUsd sets the "used_usd" field.
func (_c *EnterpriseMemberBudgetPeriodCreate) SetUsedUsd(v float64) *EnterpriseMemberBudgetPeriodCreate {
	_c.mutation.SetUsedUsd(v)
	return _c
}

// SetNillableUsedUsd sets the "used_usd" field if the given value is not nil.
func (_c *EnterpriseMemberBudgetPeriodCreate) SetNillableUsedUsd(v *float64) *EnterpriseMemberBudgetPeriodCreate {
	if v != nil {
		_c.SetUsedUsd(*v)
	}
	return _c
}

// SetReservedUsd sets the "reserved_usd" field.
func (_c *EnterpriseMemberBudgetPeriodCreate) SetReservedUsd(v float64) *EnterpriseMemberBudgetPeriodCreate {
	_c.mutation.SetReservedUsd(v)
	return _c
}

// SetNillableReservedUsd sets the "reserved_usd" field if the given value is not nil.
func (_c *EnterpriseMemberBudgetPeriodCreate) SetNillableReservedUsd(v *float64) *EnterpriseMemberBudgetPeriodCreate {
	if v != nil {
		_c.SetReservedUsd(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *EnterpriseMemberBudgetPeriodCreate) SetVersion(v int64) *EnterpriseMemberBudgetPeriodCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *EnterpriseMemberBudgetPeriodCreate) SetNillableVersion(v *int64) *EnterpriseMemberBudgetPeriodCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EnterpriseMemberBudgetPeriodCreate) SetCreatedAt(v time.Time) *EnterpriseMemberBudgetPeriodCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EnterpriseMemberBudgetPeriodCreate) SetNillableCreatedAt(v *time.Time) *EnterpriseMemberBudgetPeriodCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EnterpriseMemberBudgetPeriodCreate) SetUpdatedAt(v time.Time) *EnterpriseMemberBudgetPeriodCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EnterpriseMemberBudgetPeriodCreate) SetNillableUpdatedAt(v *time.Time) *EnterpriseMemberBudgetPeriodCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetMember sets the "member" edge to the EnterpriseMember entity.
func (_c *EnterpriseMemberBudgetPeriodCreate) SetMember(v *EnterpriseMember) *EnterpriseMemberBudgetPeriodCreate {
	return _c.SetMemberID(v.ID)
}

// Mutation returns the EnterpriseMemberBudgetPeriodMutation object of the builder.
func (_c *EnterpriseMemberBudgetPeriodCreate) Mutation() *EnterpriseMemberBudgetPeriodMutation {
	return _c.mutation
}

// Save creates the EnterpriseMemberBudgetPeriod in the database.
func (_c *EnterpriseMemberBudgetPeriodCreate) Save(ctx context.Context) (*EnterpriseMemberBudgetPeriod, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EnterpriseMemberBudgetPeriodCreate) SaveX(ctx context.Context) *EnterpriseMemberBudgetPeriod {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnterpriseMemberBudgetPeriodCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnterpriseMemberBudgetPeriodCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EnterpriseMemberBudgetPeriodCreate) defaults() {
	if _, ok := _c.mutation.Timezone(); !ok {
		v := enterprisememberbudgetperiod.DefaultTimezone
		_c.mutation.SetTimezone(v)
	}
	if _, ok := _c.mutation.UsedUsd(); !ok {
		v := enterprisememberbudgetperiod.DefaultUsedUsd
		_c.mutation.SetUsedUsd(v)
	}
	if _, ok := _c.mutation.ReservedUsd(); !ok {
		v := enterprisememberbudgetperiod.DefaultReservedUsd
		_c.mutation.SetReservedUsd(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := enterprisememberbudgetperiod.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := enterprisememberbudgetperiod.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := enterprisememberbudgetperiod.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EnterpriseMemberBudgetPeriodCreate) check() error {
	if _, ok := _c.mutation.MemberID(); !ok {
		return &ValidationError{Name: "member_id", err: errors.New(`ent: missing required field "EnterpriseMemberBudgetPeriod.member_id"`)}
	}
	if _, ok := _c.mutation.PeriodStart(); !ok {
		return &ValidationError{Name: "period_start", err: errors.New(`ent: missing required field "EnterpriseMemberBudgetPeriod.period_start"`)}
	}
	if _, ok := _c.mutation.Timezone(); !ok {
		return &ValidationError{Name: "timezone", err: errors.New(`ent: missing required field "EnterpriseMemberBudgetPeriod.timezone"`)}
	}
	if v, ok := _c.mutation.Timezone(); ok {
		if err := enterprisememberbudgetperiod.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "EnterpriseMemberBudgetPeriod.timezone": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UsedUsd(); !ok {
		return &ValidationError{Name: "used_usd", err: errors.New(`ent: missing required field "EnterpriseMemberBudgetPeriod.used_usd"`)}
	}
	if _, ok := _c.mutation.ReservedUsd(); !ok {
		return &ValidationError{Name: "reserved_usd", err: errors.New(`ent: missing required field "EnterpriseMemberBudgetPeriod.reserved_usd"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "EnterpriseMemberBudgetPeriod.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := enterprisememberbudgetperiod.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "EnterpriseMemberBudgetPeriod.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EnterpriseMemberBudgetPeriod.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EnterpriseMemberBudgetPeriod.updated_at"`)}
	}
	if len(_c.mutation.MemberIDs()) == 0 {
		return &ValidationError{Name: "member", err: errors.New(`ent: missing required edge "EnterpriseMemberBudgetPeriod.member"`)}
	}
	return nil
}

func (_c *EnterpriseMemberBudgetPeriodCreate) sqlSave(ctx context.Context) (*EnterpriseMemberBudgetPeriod, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EnterpriseMemberBudgetPeriodCreate) createSpec() (*EnterpriseMemberBudgetPeriod, *sqlgraph.CreateSpec) {
	var (
		_node = &EnterpriseMemberBudgetPeriod{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(enterprisememberbudgetperiod.Table, sqlgraph.NewFieldSpec(enterprisememberbudgetperiod.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.PeriodStart(); ok {
		_spec.SetField(enterprisememberbudgetperiod.FieldPeriodStart, field.TypeTime, value)
		_node.PeriodStart = value
	}
	if value, ok := _c.mutation.Timezone(); ok {
		_spec.SetField(enterprisememberbudgetperiod.FieldTimezone, field.TypeString, value)
		_node.Timezone = value
	}
	if value, ok := _c.mutation.UsedUsd(); ok {
		_spec.SetField(enterprisememberbudgetperiod.FieldUsedUsd, field.TypeFloat64, value)
		_node.UsedUsd = value
	}
	if value, ok := _c.mutation.ReservedUsd(); ok {
		_spec.SetField(enterprisememberbudgetperiod.FieldReservedUsd, field.TypeFloat64, value)
		_node.ReservedUsd = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(enterprisememberbudgetperiod.FieldVersion, field.TypeInt64, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(enterprisememberbudgetperiod.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(enterprisememberbudgetperiod.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enterprisememberbudgetperiod.MemberTable,
			Columns: []string{enterprisememberbudgetperiod.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisemember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MemberID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EnterpriseMemberBudgetPeriod.Create().
//		SetMemberID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EnterpriseMemberBudgetPeriodUpsert) {
//			SetMemberID(v+v).
//		}).
//		Exec(ctx)
func (_c *EnterpriseMemberBudgetPeriodCreate) OnConflict(opts ...sql.ConflictOption) *EnterpriseMemberBudgetPeriodUpsertOne {
	_c.conflict = opts
	return &EnterpriseMemberBudgetPeriodUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EnterpriseMemberBudgetPeriod.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EnterpriseMemberBudgetPeriodCreate) OnConflictColumns(columns ...string) *EnterpriseMemberBudgetPeriodUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EnterpriseMemberBudgetPeriodUpsertOne{
		create: _c,
	}
}

type (
	// EnterpriseMemberBudgetPeriodUpsertOne is the builder for "upsert"-ing
	//  one EnterpriseMemberBudgetPeriod node.
	EnterpriseMemberBudgetPeriodUpsertOne struct {
		create *EnterpriseMemberBudgetPeriodCreate
	}

	// EnterpriseMemberBudgetPeriodUpsert is the "OnConflict" setter.
	EnterpriseMemberBudgetPeriodUpsert struct {
		*sql.UpdateSet
	}
)

// SetMemberID sets the "member_id" field.
func (u *EnterpriseMemberBudgetPeriodUpsert) SetMemberID(v int64) *EnterpriseMemberBudgetPeriodUpsert {
	u.Set(enterprisememberbudgetperiod.FieldMemberID, v)
	return u
}

// UpdateMemberID sets the "member_id" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetPeriodUpsert) UpdateMemberID() *EnterpriseMemberBudgetPeriodUpsert {
	u.SetExcluded(enterprisememberbudgetperiod.FieldMemberID)
	return u
}

// SetPeriodStart sets the "period_start" field.
func (u *EnterpriseMemberBudgetPeriodUpsert) SetPeriodStart(v time.Time) *EnterpriseMemberBudgetPeriodUpsert {
	u.Set(enterprisememberbudgetperiod.FieldPeriodStart, v)
	return u
}

// UpdatePeriodStart sets the "period_start" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetPeriodUpsert) UpdatePeriodStart() *EnterpriseMemberBudgetPeriodUpsert {
	u.SetExcluded(enterprisememberbudgetperiod.FieldPeriodStart)
	return u
}

// SetTimezone sets the "timezone" field.
func (u *EnterpriseMemberBudgetPeriodUpsert) SetTimezone(v string) *EnterpriseMemberBudgetPeriodUpsert {
	u.Set(enterprisememberbudgetperiod.FieldTimezone, v)
	return u
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetPeriodUpsert) UpdateTimezone() *EnterpriseMemberBudgetPeriodUpsert {
	u.SetExcluded(enterprisememberbudgetperiod.FieldTimezone)
	return u
}

// SetUsedUsd sets the "used_usd" field.
func (u *EnterpriseMemberBudgetPeriodUpsert) SetUsedUsd(v float64) *EnterpriseMemberBudgetPeriodUpsert {
	u.Set(enterprisememberbudgetperiod.FieldUsedUsd, v)
	return u
}

// UpdateUsedUsd sets the "used_usd" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetPeriodUpsert) UpdateUsedUsd() *EnterpriseMemberBudgetPeriodUpsert {
	u.SetExcluded(enterprisememberbudgetperiod.FieldUsedUsd)
	return u
}

// AddUsedUsd adds v to the "used_usd" field.
func (u *EnterpriseMemberBudgetPeriodUpsert) AddUsedUsd(v float64) *EnterpriseMemberBudgetPeriodUpsert {
	u.Add(enterprisememberbudgetperiod.FieldUsedUsd, v)
	return u
}

// SetReservedUsd sets the "reserved_usd" field.
func (u *EnterpriseMemberBudgetPeriodUpsert) SetReservedUsd(v float64) *EnterpriseMemberBudgetPeriodUpsert {
	u.Set(enterprisememberbudgetperiod.FieldReservedUsd, v)
	return u
}

// UpdateReservedUsd sets the "reserved_usd" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetPeriodUpsert) UpdateReservedUsd() *EnterpriseMemberBudgetPeriodUpsert {
	u.SetExcluded(enterprisememberbudgetperiod.FieldReservedUsd)
	return u
}

// AddReservedUsd adds v to the "reserved_usd" field.
func (u *EnterpriseMemberBudgetPeriodUpsert) AddReservedUsd(v float64) *EnterpriseMemberBudgetPeriodUpsert {
	u.Add(enterprisememberbudgetperiod.FieldReservedUsd, v)
	return u
}

// SetVersion sets the "version" field.
func (u *EnterpriseMemberBudgetPeriodUpsert) SetVersion(v int64) *EnterpriseMemberBudgetPeriodUpsert {
	u.Set(enterprisememberbudgetperiod.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetPeriodUpsert) UpdateVersion() *EnterpriseMemberBudgetPeriodUpsert {
	u.SetExcluded(enterprisememberbudgetperiod.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *EnterpriseMemberBudgetPeriodUpsert) AddVersion(v int64) *EnterpriseMemberBudgetPeriodUpsert {
	u.Add(enterprisememberbudgetperiod.FieldVersion, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EnterpriseMemberBudgetPeriodUpsert) SetUpdatedAt(v time.Time) *EnterpriseMemberBudgetPeriodUpsert {
	u.Set(enterprisememberbudgetperiod.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetPeriodUpsert) UpdateUpdatedAt() *EnterpriseMemberBudgetPeriodUpsert {
	u.SetExcluded(enterprisememberbudgetperiod.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.EnterpriseMemberBudgetPeriod.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EnterpriseMemberBudgetPeriodUpsertOne) UpdateNewValues() *EnterpriseMemberBudgetPeriodUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(enterprisememberbudgetperiod.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EnterpriseMemberBudgetPeriod.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EnterpriseMemberBudgetPeriodUpsertOne) Ignore() *EnterpriseMemberBudgetPeriodUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EnterpriseMemberBudgetPeriodUpsertOne) DoNothing() *EnterpriseMemberBudgetPeriodUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EnterpriseMemberBudgetPeriodCreate.OnConflict
// documentation for more info.
func (u *EnterpriseMemberBudgetPeriodUpsertOne) Update(set func(*EnterpriseMemberBudgetPeriodUpsert)) *EnterpriseMemberBudgetPeriodUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EnterpriseMemberBudgetPeriodUpsert{UpdateSet: update})
	}))
	return u
}

// SetMemberID sets the "member_id" field.
func (u *EnterpriseMemberBudgetPeriodUpsertOne) SetMemberID(v int64) *EnterpriseMemberBudgetPeriodUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.SetMemberID(v)
	})
}

// UpdateMemberID sets the "member_id" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetPeriodUpsertOne) UpdateMemberID() *EnterpriseMemberBudgetPeriodUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.UpdateMemberID()
	})
}

// SetPeriodStart sets the "period_start" field.
func (u *EnterpriseMemberBudgetPeriodUpsertOne) SetPeriodStart(v time.Time) *EnterpriseMemberBudgetPeriodUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.SetPeriodStart(v)
	})
}

// UpdatePeriodStart sets the "period_start" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetPeriodUpsertOne) UpdatePeriodStart() *EnterpriseMemberBudgetPeriodUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.UpdatePeriodStart()
	})
}

// SetTimezone sets the "timezone" field.
func (u *EnterpriseMemberBudgetPeriodUpsertOne) SetTimezone(v string) *EnterpriseMemberBudgetPeriodUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.SetTimezone(v)
	})
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetPeriodUpsertOne) UpdateTimezone() *EnterpriseMemberBudgetPeriodUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.UpdateTimezone()
	})
}

// SetUsedUsd sets the "used_usd" field.
func (u *EnterpriseMemberBudgetPeriodUpsertOne) SetUsedUsd(v float64) *EnterpriseMemberBudgetPeriodUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.SetUsedUsd(v)
	})
}

// AddUsedUsd adds v to the "used_usd" field.
func (u *EnterpriseMemberBudgetPeriodUpsertOne) AddUsedUsd(v float64) *EnterpriseMemberBudgetPeriodUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.AddUsedUsd(v)
	})
}

// UpdateUsedUsd sets the "used_usd" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetPeriodUpsertOne) UpdateUsedUsd() *EnterpriseMemberBudgetPeriodUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.UpdateUsedUsd()
	})
}

// SetReservedUsd sets the "reserved_usd" field.
func (u *EnterpriseMemberBudgetPeriodUpsertOne) SetReservedUsd(v float64) *EnterpriseMemberBudgetPeriodUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.SetReservedUsd(v)
	})
}

// AddReservedUsd adds v to the "reserved_usd" field.
func (u *EnterpriseMemberBudgetPeriodUpsertOne) AddReservedUsd(v float64) *EnterpriseMemberBudgetPeriodUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.AddReservedUsd(v)
	})
}

// UpdateReservedUsd sets the "reserved_usd" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetPeriodUpsertOne) UpdateReservedUsd() *EnterpriseMemberBudgetPeriodUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.UpdateReservedUsd()
	})
}

// SetVersion sets the "version" field.
func (u *EnterpriseMemberBudgetPeriodUpsertOne) SetVersion(v int64) *EnterpriseMemberBudgetPeriodUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *EnterpriseMemberBudgetPeriodUpsertOne) AddVersion(v int64) *EnterpriseMemberBudgetPeriodUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetPeriodUpsertOne) UpdateVersion() *EnterpriseMemberBudgetPeriodUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.UpdateVersion()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EnterpriseMemberBudgetPeriodUpsertOne) SetUpdatedAt(v time.Time) *EnterpriseMemberBudgetPeriodUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetPeriodUpsertOne) UpdateUpdatedAt() *EnterpriseMemberBudgetPeriodUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *EnterpriseMemberBudgetPeriodUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EnterpriseMemberBudgetPeriodCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EnterpriseMemberBudgetPeriodUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EnterpriseMemberBudgetPeriodUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EnterpriseMemberBudgetPeriodUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EnterpriseMemberBudgetPeriodCreateBulk is the builder for creating many EnterpriseMemberBudgetPeriod entities in bulk.
type EnterpriseMemberBudgetPeriodCreateBulk struct {
	config
	err      error
	builders []*EnterpriseMemberBudgetPeriodCreate
	conflict []sql.ConflictOption
}

// Save creates the EnterpriseMemberBudgetPeriod entities in the database.
func (_c *EnterpriseMemberBudgetPeriodCreateBulk) Save(ctx context.Context) ([]*EnterpriseMemberBudgetPeriod, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EnterpriseMemberBudgetPeriod, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EnterpriseMemberBudgetPeriodMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EnterpriseMemberBudgetPeriodCreateBulk) SaveX(ctx context.Context) []*EnterpriseMemberBudgetPeriod {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnterpriseMemberBudgetPeriodCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnterpriseMemberBudgetPeriodCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EnterpriseMemberBudgetPeriod.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EnterpriseMemberBudgetPeriodUpsert) {
//			SetMemberID(v+v).
//		}).
//		Exec(ctx)
func (_c *EnterpriseMemberBudgetPeriodCreateBulk) OnConflict(opts ...sql.ConflictOption) *EnterpriseMemberBudgetPeriodUpsertBulk {
	_c.conflict = opts
	return &EnterpriseMemberBudgetPeriodUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EnterpriseMemberBudgetPeriod.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EnterpriseMemberBudgetPeriodCreateBulk) OnConflictColumns(columns ...string) *EnterpriseMemberBudgetPeriodUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EnterpriseMemberBudgetPeriodUpsertBulk{
		create: _c,
	}
}

// EnterpriseMemberBudgetPeriodUpsertBulk is the builder for "upsert"-ing
// a bulk of EnterpriseMemberBudgetPeriod nodes.
type EnterpriseMemberBudgetPeriodUpsertBulk struct {
	create *EnterpriseMemberBudgetPeriodCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.EnterpriseMemberBudgetPeriod.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EnterpriseMemberBudgetPeriodUpsertBulk) UpdateNewValues() *EnterpriseMemberBudgetPeriodUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(enterprisememberbudgetperiod.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EnterpriseMemberBudgetPeriod.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EnterpriseMemberBudgetPeriodUpsertBulk) Ignore() *EnterpriseMemberBudgetPeriodUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EnterpriseMemberBudgetPeriodUpsertBulk) DoNothing() *EnterpriseMemberBudgetPeriodUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EnterpriseMemberBudgetPeriodCreateBulk.OnConflict
// documentation for more info.
func (u *EnterpriseMemberBudgetPeriodUpsertBulk) Update(set func(*EnterpriseMemberBudgetPeriodUpsert)) *EnterpriseMemberBudgetPeriodUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EnterpriseMemberBudgetPeriodUpsert{UpdateSet: update})
	}))
	return u
}

// SetMemberID sets the "member_id" field.
func (u *EnterpriseMemberBudgetPeriodUpsertBulk) SetMemberID(v int64) *EnterpriseMemberBudgetPeriodUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.SetMemberID(v)
	})
}

// UpdateMemberID sets the "member_id" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetPeriodUpsertBulk) UpdateMemberID() *EnterpriseMemberBudgetPeriodUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.UpdateMemberID()
	})
}

// SetPeriodStart sets the "period_start" field.
func (u *EnterpriseMemberBudgetPeriodUpsertBulk) SetPeriodStart(v time.Time) *EnterpriseMemberBudgetPeriodUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.SetPeriodStart(v)
	})
}

// UpdatePeriodStart sets the "period_start" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetPeriodUpsertBulk) UpdatePeriodStart() *EnterpriseMemberBudgetPeriodUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.UpdatePeriodStart()
	})
}

// SetTimezone sets the "timezone" field.
func (u *EnterpriseMemberBudgetPeriodUpsertBulk) SetTimezone(v string) *EnterpriseMemberBudgetPeriodUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.SetTimezone(v)
	})
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetPeriodUpsertBulk) UpdateTimezone() *EnterpriseMemberBudgetPeriodUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.UpdateTimezone()
	})
}

// SetUsedUsd sets the "used_usd" field.
func (u *EnterpriseMemberBudgetPeriodUpsertBulk) SetUsedUsd(v float64) *EnterpriseMemberBudgetPeriodUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.SetUsedUsd(v)
	})
}

// AddUsedUsd adds v to the "used_usd" field.
func (u *EnterpriseMemberBudgetPeriodUpsertBulk) AddUsedUsd(v float64) *EnterpriseMemberBudgetPeriodUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.AddUsedUsd(v)
	})
}

// UpdateUsedUsd sets the "used_usd" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetPeriodUpsertBulk) UpdateUsedUsd() *EnterpriseMemberBudgetPeriodUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.UpdateUsedUsd()
	})
}

// SetReservedUsd sets the "reserved_usd" field.
func (u *EnterpriseMemberBudgetPeriodUpsertBulk) SetReservedUsd(v float64) *EnterpriseMemberBudgetPeriodUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.SetReservedUsd(v)
	})
}

// AddReservedUsd adds v to the "reserved_usd" field.
func (u *EnterpriseMemberBudgetPeriodUpsertBulk) AddReservedUsd(v float64) *EnterpriseMemberBudgetPeriodUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.AddReservedUsd(v)
	})
}

// UpdateReservedUsd sets the "reserved_usd" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetPeriodUpsertBulk) UpdateReservedUsd() *EnterpriseMemberBudgetPeriodUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.UpdateReservedUsd()
	})
}

// SetVersion sets the "version" field.
func (u *EnterpriseMemberBudgetPeriodUpsertBulk) SetVersion(v int64) *EnterpriseMemberBudgetPeriodUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *EnterpriseMemberBudgetPeriodUpsertBulk) AddVersion(v int64) *EnterpriseMemberBudgetPeriodUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetPeriodUpsertBulk) UpdateVersion() *EnterpriseMemberBudgetPeriodUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.UpdateVersion()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EnterpriseMemberBudgetPeriodUpsertBulk) SetUpdatedAt(v time.Time) *EnterpriseMemberBudgetPeriodUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetPeriodUpsertBulk) UpdateUpdatedAt() *EnterpriseMemberBudgetPeriodUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetPeriodUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *EnterpriseMemberBudgetPeriodUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EnterpriseMemberBudgetPeriodCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EnterpriseMemberBudgetPeriodCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EnterpriseMemberBudgetPeriodUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
