// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/enterprisemember"
	"github.com/Wei-Shaw/sub2api/ent/enterprisememberbudgetentry"
	"github.com/Wei-Shaw/sub2api/ent/enterprisememberbudgetperiod"
	"github.com/Wei-Shaw/sub2api/ent/enterprisememberbudgetreservation"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// EnterpriseMemberUpdate is the builder for updating EnterpriseMember entities.
type EnterpriseMemberUpdate struct {
	config
	hooks    []Hook
	mutation *EnterpriseMemberMutation
}

// Where appends a list predicates to the EnterpriseMemberUpdate builder.
func (_u *EnterpriseMemberUpdate) Where(ps ...predicate.EnterpriseMember) *EnterpriseMemberUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnterpriseMemberUpdate) SetUpdatedAt(v time.Time) *EnterpriseMemberUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *EnterpriseMemberUpdate) SetDeletedAt(v time.Time) *EnterpriseMemberUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *EnterpriseMemberUpdate) SetNillableDeletedAt(v *time.Time) *EnterpriseMemberUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *EnterpriseMemberUpdate) ClearDeletedAt() *EnterpriseMemberUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetEnterpriseUserID sets the "enterprise_user_id" field.
func (_u *EnterpriseMemberUpdate) SetEnterpriseUserID(v int64) *EnterpriseMemberUpdate {
	_u.mutation.SetEnterpriseUserID(v)
	return _u
}

// SetNillableEnterpriseUserID sets the "enterprise_user_id" field if the given value is not nil.
func (_u *EnterpriseMemberUpdate) SetNillableEnterpriseUserID(v *int64) *EnterpriseMemberUpdate {
	if v != nil {
		_u.SetEnterpriseUserID(*v)
	}
	return _u
}

// SetMemberCode sets the "member_code" field.
func (_u *EnterpriseMemberUpdate) SetMemberCode(v string) *EnterpriseMemberUpdate {
	_u.mutation.SetMemberCode(v)
	return _u
}

// SetNillableMemberCode sets the "member_code" field if the given value is not nil.
func (_u *EnterpriseMemberUpdate) SetNillableMemberCode(v *string) *EnterpriseMemberUpdate {
	if v != nil {
		_u.SetMemberCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *EnterpriseMemberUpdate) SetName(v string) *EnterpriseMemberUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EnterpriseMemberUpdate) SetNillableName(v *string) *EnterpriseMemberUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *EnterpriseMemberUpdate) SetStatus(v string) *EnterpriseMemberUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EnterpriseMemberUpdate) SetNillableStatus(v *string) *EnterpriseMemberUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (_u *EnterpriseMemberUpdate) SetMonthlyLimitUsd(v float64) *EnterpriseMemberUpdate {
	_u.mutation.ResetMonthlyLimitUsd()
	_u.mutation.SetMonthlyLimitUsd(v)
	return _u
}

// SetNillableMonthlyLimitUsd sets the "monthly_limit_usd" field if the given value is not nil.
func (_u *EnterpriseMemberUpdate) SetNillableMonthlyLimitUsd(v *float64) *EnterpriseMemberUpdate {
	if v != nil {
		_u.SetMonthlyLimitUsd(*v)
	}
	return _u
}

// AddMonthlyLimitUsd adds value to the "monthly_limit_usd" field.
func (_u *EnterpriseMemberUpdate) AddMonthlyLimitUsd(v float64) *EnterpriseMemberUpdate {
	_u.mutation.AddMonthlyLimitUsd(v)
	return _u
}

// SetRateLimit5h sets the "rate_limit_5h" field.
func (_u *EnterpriseMemberUpdate) SetRateLimit5h(v float64) *EnterpriseMemberUpdate {
	_u.mutation.ResetRateLimit5h()
	_u.mutation.SetRateLimit5h(v)
	return _u
}

// SetNillableRateLimit5h sets the "rate_limit_5h" field if the given value is not nil.
func (_u *EnterpriseMemberUpdate) SetNillableRateLimit5h(v *float64) *EnterpriseMemberUpdate {
	if v != nil {
		_u.SetRateLimit5h(*v)
	}
	return _u
}

// AddRateLimit5h adds value to the "rate_limit_5h" field.
func (_u *EnterpriseMemberUpdate) AddRateLimit5h(v float64) *EnterpriseMemberUpdate {
	_u.mutation.AddRateLimit5h(v)
	return _u
}

// SetRateLimit1d sets the "rate_limit_1d" field.
func (_u *EnterpriseMemberUpdate) SetRateLimit1d(v float64) *EnterpriseMemberUpdate {
	_u.mutation.ResetRateLimit1d()
	_u.mutation.SetRateLimit1d(v)
	return _u
}

// SetNillableRateLimit1d sets the "rate_limit_1d" field if the given value is not nil.
func (_u *EnterpriseMemberUpdate) SetNillableRateLimit1d(v *float64) *EnterpriseMemberUpdate {
	if v != nil {
		_u.SetRateLimit1d(*v)
	}
	return _u
}

// AddRateLimit1d adds value to the "rate_limit_1d" field.
func (_u *EnterpriseMemberUpdate) AddRateLimit1d(v float64) *EnterpriseMemberUpdate {
	_u.mutation.AddRateLimit1d(v)
	return _u
}

// SetRateLimit7d sets the "rate_limit_7d" field.
func (_u *EnterpriseMemberUpdate) SetRateLimit7d(v float64) *EnterpriseMemberUpdate {
	_u.mutation.ResetRateLimit7d()
	_u.mutation.SetRateLimit7d(v)
	return _u
}

// SetNillableRateLimit7d sets the "rate_limit_7d" field if the given value is not nil.
func (_u *EnterpriseMemberUpdate) SetNillableRateLimit7d(v *float64) *EnterpriseMemberUpdate {
	if v != nil {
		_u.SetRateLimit7d(*v)
	}
	return _u
}

// AddRateLimit7d adds value to the "rate_limit_7d" field.
func (_u *EnterpriseMemberUpdate) AddRateLimit7d(v float64) *EnterpriseMemberUpdate {
	_u.mutation.AddRateLimit7d(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *EnterpriseMemberUpdate) SetVersion(v int64) *EnterpriseMemberUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *EnterpriseMemberUpdate) SetNillableVersion(v *int64) *EnterpriseMemberUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *EnterpriseMemberUpdate) AddVersion(v int64) *EnterpriseMemberUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetRemovedAt sets the "removed_at" field.
func (_u *EnterpriseMemberUpdate) SetRemovedAt(v time.Time) *EnterpriseMemberUpdate {
	_u.mutation.SetRemovedAt(v)
	return _u
}

// SetNillableRemovedAt sets the "removed_at" field if the given value is not nil.
func (_u *EnterpriseMemberUpdate) SetNillableRemovedAt(v *time.Time) *EnterpriseMemberUpdate {
	if v != nil {
		_u.SetRemovedAt(*v)
	}
	return _u
}

// ClearRemovedAt clears the value of the "removed_at" field.
func (_u *EnterpriseMemberUpdate) ClearRemovedAt() *EnterpriseMemberUpdate {
	_u.mutation.ClearRemovedAt()
	return _u
}

// SetEnterpriseUser sets the "enterprise_user" edge to the User entity.
func (_u *EnterpriseMemberUpdate) SetEnterpriseUser(v *User) *EnterpriseMemberUpdate {
	return _u.SetEnterpriseUserID(v.ID)
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_u *EnterpriseMemberUpdate) AddAPIKeyIDs(ids ...int64) *EnterpriseMemberUpdate {
	_u.mutation.AddAPIKeyIDs(ids...)
	return _u
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_u *EnterpriseMemberUpdate) AddAPIKeys(v ...*APIKey) *EnterpriseMemberUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPIKeyIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *EnterpriseMemberUpdate) AddUsageLogIDs(ids ...int64) *EnterpriseMemberUpdate {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *EnterpriseMemberUpdate) AddUsageLogs(v ...*UsageLog) *EnterpriseMemberUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_u *EnterpriseMemberUpdate) AddGroupIDs(ids ...int64) *EnterpriseMemberUpdate {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the Group entity.
func (_u *EnterpriseMemberUpdate) AddGroups(v ...*Group) *EnterpriseMemberUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// AddBudgetPeriodIDs adds the "budget_periods" edge to the EnterpriseMemberBudgetPeriod entity by IDs.
func (_u *EnterpriseMemberUpdate) AddBudgetPeriodIDs(ids ...int64) *EnterpriseMemberUpdate {
	_u.mutation.AddBudgetPeriodIDs(ids...)
	return _u
}

// AddBudgetPeriods adds the "budget_periods" edges to the EnterpriseMemberBudgetPeriod entity.
func (_u *EnterpriseMemberUpdate) AddBudgetPeriods(v ...*EnterpriseMemberBudgetPeriod) *EnterpriseMemberUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBudgetPeriodIDs(ids...)
}

// AddBudgetReservationIDs adds the "budget_reservations" edge to the EnterpriseMemberBudgetReservation entity by IDs.
func (_u *EnterpriseMemberUpdate) AddBudgetReservationIDs(ids ...int64) *EnterpriseMemberUpdate {
	_u.mutation.AddBudgetReservationIDs(ids...)
	return _u
}

// AddBudgetReservations adds the "budget_reservations" edges to the EnterpriseMemberBudgetReservation entity.
func (_u *EnterpriseMemberUpdate) AddBudgetReservations(v ...*EnterpriseMemberBudgetReservation) *EnterpriseMemberUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBudgetReservationIDs(ids...)
}

// AddBudgetEntryIDs adds the "budget_entries" edge to the EnterpriseMemberBudgetEntry entity by IDs.
func (_u *EnterpriseMemberUpdate) AddBudgetEntryIDs(ids ...int64) *EnterpriseMemberUpdate {
	_u.mutation.AddBudgetEntryIDs(ids...)
	return _u
}

// AddBudgetEntries adds the "budget_entries" edges to the EnterpriseMemberBudgetEntry entity.
func (_u *EnterpriseMemberUpdate) AddBudgetEntries(v ...*EnterpriseMemberBudgetEntry) *EnterpriseMemberUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBudgetEntryIDs(ids...)
}

// Mutation returns the EnterpriseMemberMutation object of the builder.
func (_u *EnterpriseMemberUpdate) Mutation() *EnterpriseMemberMutation {
	return _u.mutation
}

// ClearEnterpriseUser clears the "enterprise_user" edge to the User entity.
func (_u *EnterpriseMemberUpdate) ClearEnterpriseUser() *EnterpriseMemberUpdate {
	_u.mutation.ClearEnterpriseUser()
	return _u
}

// ClearAPIKeys clears all "api_keys" edges to the APIKey entity.
func (_u *EnterpriseMemberUpdate) ClearAPIKeys() *EnterpriseMemberUpdate {
	_u.mutation.ClearAPIKeys()
	return _u
}

// RemoveAPIKeyIDs removes the "api_keys" edge to APIKey entities by IDs.
func (_u *EnterpriseMemberUpdate) RemoveAPIKeyIDs(ids ...int64) *EnterpriseMemberUpdate {
	_u.mutation.RemoveAPIKeyIDs(ids...)
	return _u
}

// RemoveAPIKeys removes "api_keys" edges to APIKey entities.
func (_u *EnterpriseMemberUpdate) RemoveAPIKeys(v ...*APIKey) *EnterpriseMemberUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPIKeyIDs(ids...)
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *EnterpriseMemberUpdate) ClearUsageLogs() *EnterpriseMemberUpdate {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *EnterpriseMemberUpdate) RemoveUsageLogIDs(ids ...int64) *EnterpriseMemberUpdate {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *EnterpriseMemberUpdate) RemoveUsageLogs(v ...*UsageLog) *EnterpriseMemberUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// ClearGroups clears all "groups" edges to the Group entity.
func (_u *EnterpriseMemberUpdate) ClearGroups() *EnterpriseMemberUpdate {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to Group entities by IDs.
func (_u *EnterpriseMemberUpdate) RemoveGroupIDs(ids ...int64) *EnterpriseMemberUpdate {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to Group entities.
func (_u *EnterpriseMemberUpdate) RemoveGroups(v ...*Group) *EnterpriseMemberUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// ClearBudgetPeriods clears all "budget_periods" edges to the EnterpriseMemberBudgetPeriod entity.
func (_u *EnterpriseMemberUpdate) ClearBudgetPeriods() *EnterpriseMemberUpdate {
	_u.mutation.ClearBudgetPeriods()
	return _u
}

// RemoveBudgetPeriodIDs removes the "budget_periods" edge to EnterpriseMemberBudgetPeriod entities by IDs.
func (_u *EnterpriseMemberUpdate) RemoveBudgetPeriodIDs(ids ...int64) *EnterpriseMemberUpdate {
	_u.mutation.RemoveBudgetPeriodIDs(ids...)
	return _u
}

// RemoveBudgetPeriods removes "budget_periods" edges to EnterpriseMemberBudgetPeriod entities.
func (_u *EnterpriseMemberUpdate) RemoveBudgetPeriods(v ...*EnterpriseMemberBudgetPeriod) *EnterpriseMemberUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBudgetPeriodIDs(ids...)
}

// ClearBudgetReservations clears all "budget_reservations" edges to the EnterpriseMemberBudgetReservation entity.
func (_u *EnterpriseMemberUpdate) ClearBudgetReservations() *EnterpriseMemberUpdate {
	_u.mutation.ClearBudgetReservations()
	return _u
}

// RemoveBudgetReservationIDs removes the "budget_reservations" edge to EnterpriseMemberBudgetReservation entities by IDs.
func (_u *EnterpriseMemberUpdate) RemoveBudgetReservationIDs(ids ...int64) *EnterpriseMemberUpdate {
	_u.mutation.RemoveBudgetReservationIDs(ids...)
	return _u
}

// RemoveBudgetReservations removes "budget_reservations" edges to EnterpriseMemberBudgetReservation entities.
func (_u *EnterpriseMemberUpdate) RemoveBudgetReservations(v ...*EnterpriseMemberBudgetReservation) *EnterpriseMemberUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBudgetReservationIDs(ids...)
}

// ClearBudgetEntries clears all "budget_entries" edges to the EnterpriseMemberBudgetEntry entity.
func (_u *EnterpriseMemberUpdate) ClearBudgetEntries() *EnterpriseMemberUpdate {
	_u.mutation.ClearBudgetEntries()
	return _u
}

// RemoveBudgetEntryIDs removes the "budget_entries" edge to EnterpriseMemberBudgetEntry entities by IDs.
func (_u *EnterpriseMemberUpdate) RemoveBudgetEntryIDs(ids ...int64) *EnterpriseMemberUpdate {
	_u.mutation.RemoveBudgetEntryIDs(ids...)
	return _u
}

// RemoveBudgetEntries removes "budget_entries" edges to EnterpriseMemberBudgetEntry entities.
func (_u *EnterpriseMemberUpdate) RemoveBudgetEntries(v ...*EnterpriseMemberBudgetEntry) *EnterpriseMemberUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBudgetEntryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EnterpriseMemberUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnterpriseMemberUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EnterpriseMemberUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnterpriseMemberUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnterpriseMemberUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if enterprisemember.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized enterprisemember.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := enterprisemember.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnterpriseMemberUpdate) check() error {
	if v, ok := _u.mutation.MemberCode(); ok {
		if err := enterprisemember.MemberCodeValidator(v); err != nil {
			return &ValidationError{Name: "member_code", err: fmt.Errorf(`ent: validator failed for field "EnterpriseMember.member_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := enterprisemember.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "EnterpriseMember.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := enterprisemember.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EnterpriseMember.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := enterprisemember.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "EnterpriseMember.version": %w`, err)}
		}
	}
	if _u.mutation.EnterpriseUserCleared() && len(_u.mutation.EnterpriseUserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EnterpriseMember.enterprise_user"`)
	}
	return nil
}

func (_u *EnterpriseMemberUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(enterprisemember.Table, enterprisemember.Columns, sqlgraph.NewFieldSpec(enterprisemember.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(enterprisemember.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(enterprisemember.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(enterprisemember.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.MemberCode(); ok {
		_spec.SetField(enterprisemember.FieldMemberCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(enterprisemember.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(enterprisemember.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.MonthlyLimitUsd(); ok {
		_spec.SetField(enterprisemember.FieldMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyLimitUsd(); ok {
		_spec.AddField(enterprisemember.FieldMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RateLimit5h(); ok {
		_spec.SetField(enterprisemember.FieldRateLimit5h, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateLimit5h(); ok {
		_spec.AddField(enterprisemember.FieldRateLimit5h, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RateLimit1d(); ok {
		_spec.SetField(enterprisemember.FieldRateLimit1d, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateLimit1d(); ok {
		_spec.AddField(enterprisemember.FieldRateLimit1d, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RateLimit7d(); ok {
		_spec.SetField(enterprisemember.FieldRateLimit7d, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateLimit7d(); ok {
		_spec.AddField(enterprisemember.FieldRateLimit7d, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(enterprisemember.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(enterprisemember.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RemovedAt(); ok {
		_spec.SetField(enterprisemember.FieldRemovedAt, field.TypeTime, value)
	}
	if _u.mutation.RemovedAtCleared() {
		_spec.ClearField(enterprisemember.FieldRemovedAt, field.TypeTime)
	}
	if _u.mutation.EnterpriseUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enterprisemember.EnterpriseUserTable,
			Columns: []string{enterprisemember.EnterpriseUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EnterpriseUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enterprisemember.EnterpriseUserTable,
			Columns: []string{enterprisemember.EnterpriseUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.APIKeysTable,
			Columns: []string{enterprisemember.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPIKeysIDs(); len(nodes) > 0 && !_u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.APIKeysTable,
			Columns: []string{enterprisemember.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.APIKeysTable,
			Columns: []string{enterprisemember.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.UsageLogsTable,
			Columns: []string{enterprisemember.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.UsageLogsTable,
			Columns: []string{enterprisemember.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.UsageLogsTable,
			Columns: []string{enterprisemember.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   enterprisemember.GroupsTable,
			Columns: enterprisemember.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		createE := &EnterpriseMemberGroupBindingCreate{config: _u.config, mutation: newEnterpriseMemberGroupBindingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   enterprisemember.GroupsTable,
			Columns: enterprisemember.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &EnterpriseMemberGroupBindingCreate{config: _u.config, mutation: newEnterpriseMemberGroupBindingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   enterprisemember.GroupsTable,
			Columns: enterprisemember.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &EnterpriseMemberGroupBindingCreate{config: _u.config, mutation: newEnterpriseMemberGroupBindingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BudgetPeriodsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.BudgetPeriodsTable,
			Columns: []string{enterprisemember.BudgetPeriodsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisememberbudgetperiod.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBudgetPeriodsIDs(); len(nodes) > 0 && !_u.mutation.BudgetPeriodsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.BudgetPeriodsTable,
			Columns: []string{enterprisemember.BudgetPeriodsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisememberbudgetperiod.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BudgetPeriodsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.BudgetPeriodsTable,
			Columns: []string{enterprisemember.BudgetPeriodsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisememberbudgetperiod.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BudgetReservationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.BudgetReservationsTable,
			Columns: []string{enterprisemember.BudgetReservationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisememberbudgetreservation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBudgetReservationsIDs(); len(nodes) > 0 && !_u.mutation.BudgetReservationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.BudgetReservationsTable,
			Columns: []string{enterprisemember.BudgetReservationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisememberbudgetreservation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BudgetReservationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.BudgetReservationsTable,
			Columns: []string{enterprisemember.BudgetReservationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisememberbudgetreservation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BudgetEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.BudgetEntriesTable,
			Columns: []string{enterprisemember.BudgetEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisememberbudgetentry.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBudgetEntriesIDs(); len(nodes) > 0 && !_u.mutation.BudgetEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.BudgetEntriesTable,
			Columns: []string{enterprisemember.BudgetEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisememberbudgetentry.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BudgetEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.BudgetEntriesTable,
			Columns: []string{enterprisemember.BudgetEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisememberbudgetentry.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{enterprisemember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EnterpriseMemberUpdateOne is the builder for updating a single EnterpriseMember entity.
type EnterpriseMemberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EnterpriseMemberMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnterpriseMemberUpdateOne) SetUpdatedAt(v time.Time) *EnterpriseMemberUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *EnterpriseMemberUpdateOne) SetDeletedAt(v time.Time) *EnterpriseMemberUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *EnterpriseMemberUpdateOne) SetNillableDeletedAt(v *time.Time) *EnterpriseMemberUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *EnterpriseMemberUpdateOne) ClearDeletedAt() *EnterpriseMemberUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetEnterpriseUserID sets the "enterprise_user_id" field.
func (_u *EnterpriseMemberUpdateOne) SetEnterpriseUserID(v int64) *EnterpriseMemberUpdateOne {
	_u.mutation.SetEnterpriseUserID(v)
	return _u
}

// SetNillableEnterpriseUserID sets the "enterprise_user_id" field if the given value is not nil.
func (_u *EnterpriseMemberUpdateOne) SetNillableEnterpriseUserID(v *int64) *EnterpriseMemberUpdateOne {
	if v != nil {
		_u.SetEnterpriseUserID(*v)
	}
	return _u
}

// SetMemberCode sets the "member_code" field.
func (_u *EnterpriseMemberUpdateOne) SetMemberCode(v string) *EnterpriseMemberUpdateOne {
	_u.mutation.SetMemberCode(v)
	return _u
}

// SetNillableMemberCode sets the "member_code" field if the given value is not nil.
func (_u *EnterpriseMemberUpdateOne) SetNillableMemberCode(v *string) *EnterpriseMemberUpdateOne {
	if v != nil {
		_u.SetMemberCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *EnterpriseMemberUpdateOne) SetName(v string) *EnterpriseMemberUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EnterpriseMemberUpdateOne) SetNillableName(v *string) *EnterpriseMemberUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *EnterpriseMemberUpdateOne) SetStatus(v string) *EnterpriseMemberUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EnterpriseMemberUpdateOne) SetNillableStatus(v *string) *EnterpriseMemberUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (_u *EnterpriseMemberUpdateOne) SetMonthlyLimitUsd(v float64) *EnterpriseMemberUpdateOne {
	_u.mutation.ResetMonthlyLimitUsd()
	_u.mutation.SetMonthlyLimitUsd(v)
	return _u
}

// SetNillableMonthlyLimitUsd sets the "monthly_limit_usd" field if the given value is not nil.
func (_u *EnterpriseMemberUpdateOne) SetNillableMonthlyLimitUsd(v *float64) *EnterpriseMemberUpdateOne {
	if v != nil {
		_u.SetMonthlyLimitUsd(*v)
	}
	return _u
}

// AddMonthlyLimitUsd adds value to the "monthly_limit_usd" field.
func (_u *EnterpriseMemberUpdateOne) AddMonthlyLimitUsd(v float64) *EnterpriseMemberUpdateOne {
	_u.mutation.AddMonthlyLimitUsd(v)
	return _u
}

// SetRateLimit5h sets the "rate_limit_5h" field.
func (_u *EnterpriseMemberUpdateOne) SetRateLimit5h(v float64) *EnterpriseMemberUpdateOne {
	_u.mutation.ResetRateLimit5h()
	_u.mutation.SetRateLimit5h(v)
	return _u
}

// SetNillableRateLimit5h sets the "rate_limit_5h" field if the given value is not nil.
func (_u *EnterpriseMemberUpdateOne) SetNillableRateLimit5h(v *float64) *EnterpriseMemberUpdateOne {
	if v != nil {
		_u.SetRateLimit5h(*v)
	}
	return _u
}

// AddRateLimit5h adds value to the "rate_limit_5h" field.
func (_u *EnterpriseMemberUpdateOne) AddRateLimit5h(v float64) *EnterpriseMemberUpdateOne {
	_u.mutation.AddRateLimit5h(v)
	return _u
}

// SetRateLimit1d sets the "rate_limit_1d" field.
func (_u *EnterpriseMemberUpdateOne) SetRateLimit1d(v float64) *EnterpriseMemberUpdateOne {
	_u.mutation.ResetRateLimit1d()
	_u.mutation.SetRateLimit1d(v)
	return _u
}

// SetNillableRateLimit1d sets the "rate_limit_1d" field if the given value is not nil.
func (_u *EnterpriseMemberUpdateOne) SetNillableRateLimit1d(v *float64) *EnterpriseMemberUpdateOne {
	if v != nil {
		_u.SetRateLimit1d(*v)
	}
	return _u
}

// AddRateLimit1d adds value to the "rate_limit_1d" field.
func (_u *EnterpriseMemberUpdateOne) AddRateLimit1d(v float64) *EnterpriseMemberUpdateOne {
	_u.mutation.AddRateLimit1d(v)
	return _u
}

// SetRateLimit7d sets the "rate_limit_7d" field.
func (_u *EnterpriseMemberUpdateOne) SetRateLimit7d(v float64) *EnterpriseMemberUpdateOne {
	_u.mutation.ResetRateLimit7d()
	_u.mutation.SetRateLimit7d(v)
	return _u
}

// SetNillableRateLimit7d sets the "rate_limit_7d" field if the given value is not nil.
func (_u *EnterpriseMemberUpdateOne) SetNillableRateLimit7d(v *float64) *EnterpriseMemberUpdateOne {
	if v != nil {
		_u.SetRateLimit7d(*v)
	}
	return _u
}

// AddRateLimit7d adds value to the "rate_limit_7d" field.
func (_u *EnterpriseMemberUpdateOne) AddRateLimit7d(v float64) *EnterpriseMemberUpdateOne {
	_u.mutation.AddRateLimit7d(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *EnterpriseMemberUpdateOne) SetVersion(v int64) *EnterpriseMemberUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *EnterpriseMemberUpdateOne) SetNillableVersion(v *int64) *EnterpriseMemberUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *EnterpriseMemberUpdateOne) AddVersion(v int64) *EnterpriseMemberUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetRemovedAt sets the "removed_at" field.
func (_u *EnterpriseMemberUpdateOne) SetRemovedAt(v time.Time) *EnterpriseMemberUpdateOne {
	_u.mutation.SetRemovedAt(v)
	return _u
}

// SetNillableRemovedAt sets the "removed_at" field if the given value is not nil.
func (_u *EnterpriseMemberUpdateOne) SetNillableRemovedAt(v *time.Time) *EnterpriseMemberUpdateOne {
	if v != nil {
		_u.SetRemovedAt(*v)
	}
	return _u
}

// ClearRemovedAt clears the value of the "removed_at" field.
func (_u *EnterpriseMemberUpdateOne) ClearRemovedAt() *EnterpriseMemberUpdateOne {
	_u.mutation.ClearRemovedAt()
	return _u
}

// SetEnterpriseUser sets the "enterprise_user" edge to the User entity.
func (_u *EnterpriseMemberUpdateOne) SetEnterpriseUser(v *User) *EnterpriseMemberUpdateOne {
	return _u.SetEnterpriseUserID(v.ID)
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_u *EnterpriseMemberUpdateOne) AddAPIKeyIDs(ids ...int64) *EnterpriseMemberUpdateOne {
	_u.mutation.AddAPIKeyIDs(ids...)
	return _u
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_u *EnterpriseMemberUpdateOne) AddAPIKeys(v ...*APIKey) *EnterpriseMemberUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPIKeyIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *EnterpriseMemberUpdateOne) AddUsageLogIDs(ids ...int64) *EnterpriseMemberUpdateOne {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *EnterpriseMemberUpdateOne) AddUsageLogs(v ...*UsageLog) *EnterpriseMemberUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_u *EnterpriseMemberUpdateOne) AddGroupIDs(ids ...int64) *EnterpriseMemberUpdateOne {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the Group entity.
func (_u *EnterpriseMemberUpdateOne) AddGroups(v ...*Group) *EnterpriseMemberUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// AddBudgetPeriodIDs adds the "budget_periods" edge to the EnterpriseMemberBudgetPeriod entity by IDs.
func (_u *EnterpriseMemberUpdateOne) AddBudgetPeriodIDs(ids ...int64) *EnterpriseMemberUpdateOne {
	_u.mutation.AddBudgetPeriodIDs(ids...)
	return _u
}

// AddBudgetPeriods adds the "budget_periods" edges to the EnterpriseMemberBudgetPeriod entity.
func (_u *EnterpriseMemberUpdateOne) AddBudgetPeriods(v ...*EnterpriseMemberBudgetPeriod) *EnterpriseMemberUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBudgetPeriodIDs(ids...)
}

// AddBudgetReservationIDs adds the "budget_reservations" edge to the EnterpriseMemberBudgetReservation entity by IDs.
func (_u *EnterpriseMemberUpdateOne) AddBudgetReservationIDs(ids ...int64) *EnterpriseMemberUpdateOne {
	_u.mutation.AddBudgetReservationIDs(ids...)
	return _u
}

// AddBudgetReservations adds the "budget_reservations" edges to the EnterpriseMemberBudgetReservation entity.
func (_u *EnterpriseMemberUpdateOne) AddBudgetReservations(v ...*EnterpriseMemberBudgetReservation) *EnterpriseMemberUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBudgetReservationIDs(ids...)
}

// AddBudgetEntryIDs adds the "budget_entries" edge to the EnterpriseMemberBudgetEntry entity by IDs.
func (_u *EnterpriseMemberUpdateOne) AddBudgetEntryIDs(ids ...int64) *EnterpriseMemberUpdateOne {
	_u.mutation.AddBudgetEntryIDs(ids...)
	return _u
}

// AddBudgetEntries adds the "budget_entries" edges to the EnterpriseMemberBudgetEntry entity.
func (_u *EnterpriseMemberUpdateOne) AddBudgetEntries(v ...*EnterpriseMemberBudgetEntry) *EnterpriseMemberUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBudgetEntryIDs(ids...)
}

// Mutation returns the EnterpriseMemberMutation object of the builder.
func (_u *EnterpriseMemberUpdateOne) Mutation() *EnterpriseMemberMutation {
	return _u.mutation
}

// ClearEnterpriseUser clears the "enterprise_user" edge to the User entity.
func (_u *EnterpriseMemberUpdateOne) ClearEnterpriseUser() *EnterpriseMemberUpdateOne {
	_u.mutation.ClearEnterpriseUser()
	return _u
}

// ClearAPIKeys clears all "api_keys" edges to the APIKey entity.
func (_u *EnterpriseMemberUpdateOne) ClearAPIKeys() *EnterpriseMemberUpdateOne {
	_u.mutation.ClearAPIKeys()
	return _u
}

// RemoveAPIKeyIDs removes the "api_keys" edge to APIKey entities by IDs.
func (_u *EnterpriseMemberUpdateOne) RemoveAPIKeyIDs(ids ...int64) *EnterpriseMemberUpdateOne {
	_u.mutation.RemoveAPIKeyIDs(ids...)
	return _u
}

// RemoveAPIKeys removes "api_keys" edges to APIKey entities.
func (_u *EnterpriseMemberUpdateOne) RemoveAPIKeys(v ...*APIKey) *EnterpriseMemberUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPIKeyIDs(ids...)
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *EnterpriseMemberUpdateOne) ClearUsageLogs() *EnterpriseMemberUpdateOne {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *EnterpriseMemberUpdateOne) RemoveUsageLogIDs(ids ...int64) *EnterpriseMemberUpdateOne {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *EnterpriseMemberUpdateOne) RemoveUsageLogs(v ...*UsageLog) *EnterpriseMemberUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// ClearGroups clears all "groups" edges to the Group entity.
func (_u *EnterpriseMemberUpdateOne) ClearGroups() *EnterpriseMemberUpdateOne {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to Group entities by IDs.
func (_u *EnterpriseMemberUpdateOne) RemoveGroupIDs(ids ...int64) *EnterpriseMemberUpdateOne {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to Group entities.
func (_u *EnterpriseMemberUpdateOne) RemoveGroups(v ...*Group) *EnterpriseMemberUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// ClearBudgetPeriods clears all "budget_periods" edges to the EnterpriseMemberBudgetPeriod entity.
func (_u *EnterpriseMemberUpdateOne) ClearBudgetPeriods() *EnterpriseMemberUpdateOne {
	_u.mutation.ClearBudgetPeriods()
	return _u
}

// RemoveBudgetPeriodIDs removes the "budget_periods" edge to EnterpriseMemberBudgetPeriod entities by IDs.
func (_u *EnterpriseMemberUpdateOne) RemoveBudgetPeriodIDs(ids ...int64) *EnterpriseMemberUpdateOne {
	_u.mutation.RemoveBudgetPeriodIDs(ids...)
	return _u
}

// RemoveBudgetPeriods removes "budget_periods" edges to EnterpriseMemberBudgetPeriod entities.
func (_u *EnterpriseMemberUpdateOne) RemoveBudgetPeriods(v ...*EnterpriseMemberBudgetPeriod) *EnterpriseMemberUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBudgetPeriodIDs(ids...)
}

// ClearBudgetReservations clears all "budget_reservations" edges to the EnterpriseMemberBudgetReservation entity.
func (_u *EnterpriseMemberUpdateOne) ClearBudgetReservations() *EnterpriseMemberUpdateOne {
	_u.mutation.ClearBudgetReservations()
	return _u
}

// RemoveBudgetReservationIDs removes the "budget_reservations" edge to EnterpriseMemberBudgetReservation entities by IDs.
func (_u *EnterpriseMemberUpdateOne) RemoveBudgetReservationIDs(ids ...int64) *EnterpriseMemberUpdateOne {
	_u.mutation.RemoveBudgetReservationIDs(ids...)
	return _u
}

// RemoveBudgetReservations removes "budget_reservations" edges to EnterpriseMemberBudgetReservation entities.
func (_u *EnterpriseMemberUpdateOne) RemoveBudgetReservations(v ...*EnterpriseMemberBudgetReservation) *EnterpriseMemberUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBudgetReservationIDs(ids...)
}

// ClearBudgetEntries clears all "budget_entries" edges to the EnterpriseMemberBudgetEntry entity.
func (_u *EnterpriseMemberUpdateOne) ClearBudgetEntries() *EnterpriseMemberUpdateOne {
	_u.mutation.ClearBudgetEntries()
	return _u
}

// RemoveBudgetEntryIDs removes the "budget_entries" edge to EnterpriseMemberBudgetEntry entities by IDs.
func (_u *EnterpriseMemberUpdateOne) RemoveBudgetEntryIDs(ids ...int64) *EnterpriseMemberUpdateOne {
	_u.mutation.RemoveBudgetEntryIDs(ids...)
	return _u
}

// RemoveBudgetEntries removes "budget_entries" edges to EnterpriseMemberBudgetEntry entities.
func (_u *EnterpriseMemberUpdateOne) RemoveBudgetEntries(v ...*EnterpriseMemberBudgetEntry) *EnterpriseMemberUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBudgetEntryIDs(ids...)
}

// Where appends a list predicates to the EnterpriseMemberUpdate builder.
func (_u *EnterpriseMemberUpdateOne) Where(ps ...predicate.EnterpriseMember) *EnterpriseMemberUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EnterpriseMemberUpdateOne) Select(field string, fields ...string) *EnterpriseMemberUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EnterpriseMember entity.
func (_u *EnterpriseMemberUpdateOne) Save(ctx context.Context) (*EnterpriseMember, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnterpriseMemberUpdateOne) SaveX(ctx context.Context) *EnterpriseMember {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EnterpriseMemberUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnterpriseMemberUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnterpriseMemberUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if enterprisemember.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized enterprisemember.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := enterprisemember.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnterpriseMemberUpdateOne) check() error {
	if v, ok := _u.mutation.MemberCode(); ok {
		if err := enterprisemember.MemberCodeValidator(v); err != nil {
			return &ValidationError{Name: "member_code", err: fmt.Errorf(`ent: validator failed for field "EnterpriseMember.member_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := enterprisemember.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "EnterpriseMember.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := enterprisemember.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EnterpriseMember.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := enterprisemember.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "EnterpriseMember.version": %w`, err)}
		}
	}
	if _u.mutation.EnterpriseUserCleared() && len(_u.mutation.EnterpriseUserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EnterpriseMember.enterprise_user"`)
	}
	return nil
}

func (_u *EnterpriseMemberUpdateOne) sqlSave(ctx context.Context) (_node *EnterpriseMember, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(enterprisemember.Table, enterprisemember.Columns, sqlgraph.NewFieldSpec(enterprisemember.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EnterpriseMember.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, enterprisemember.FieldID)
		for _, f := range fields {
			if !enterprisemember.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != enterprisemember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(enterprisemember.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(enterprisemember.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(enterprisemember.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.MemberCode(); ok {
		_spec.SetField(enterprisemember.FieldMemberCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(enterprisemember.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(enterprisemember.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.MonthlyLimitUsd(); ok {
		_spec.SetField(enterprisemember.FieldMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyLimitUsd(); ok {
		_spec.AddField(enterprisemember.FieldMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RateLimit5h(); ok {
		_spec.SetField(enterprisemember.FieldRateLimit5h, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateLimit5h(); ok {
		_spec.AddField(enterprisemember.FieldRateLimit5h, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RateLimit1d(); ok {
		_spec.SetField(enterprisemember.FieldRateLimit1d, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateLimit1d(); ok {
		_spec.AddField(enterprisemember.FieldRateLimit1d, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RateLimit7d(); ok {
		_spec.SetField(enterprisemember.FieldRateLimit7d, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateLimit7d(); ok {
		_spec.AddField(enterprisemember.FieldRateLimit7d, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(enterprisemember.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(enterprisemember.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RemovedAt(); ok {
		_spec.SetField(enterprisemember.FieldRemovedAt, field.TypeTime, value)
	}
	if _u.mutation.RemovedAtCleared() {
		_spec.ClearField(enterprisemember.FieldRemovedAt, field.TypeTime)
	}
	if _u.mutation.EnterpriseUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enterprisemember.EnterpriseUserTable,
			Columns: []string{enterprisemember.EnterpriseUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EnterpriseUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enterprisemember.EnterpriseUserTable,
			Columns: []string{enterprisemember.EnterpriseUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.APIKeysTable,
			Columns: []string{enterprisemember.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPIKeysIDs(); len(nodes) > 0 && !_u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.APIKeysTable,
			Columns: []string{enterprisemember.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.APIKeysTable,
			Columns: []string{enterprisemember.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.UsageLogsTable,
			Columns: []string{enterprisemember.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.UsageLogsTable,
			Columns: []string{enterprisemember.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.UsageLogsTable,
			Columns: []string{enterprisemember.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   enterprisemember.GroupsTable,
			Columns: enterprisemember.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		createE := &EnterpriseMemberGroupBindingCreate{config: _u.config, mutation: newEnterpriseMemberGroupBindingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   enterprisemember.GroupsTable,
			Columns: enterprisemember.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &EnterpriseMemberGroupBindingCreate{config: _u.config, mutation: newEnterpriseMemberGroupBindingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   enterprisemember.GroupsTable,
			Columns: enterprisemember.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &EnterpriseMemberGroupBindingCreate{config: _u.config, mutation: newEnterpriseMemberGroupBindingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BudgetPeriodsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.BudgetPeriodsTable,
			Columns: []string{enterprisemember.BudgetPeriodsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisememberbudgetperiod.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBudgetPeriodsIDs(); len(nodes) > 0 && !_u.mutation.BudgetPeriodsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.BudgetPeriodsTable,
			Columns: []string{enterprisemember.BudgetPeriodsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisememberbudgetperiod.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BudgetPeriodsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.BudgetPeriodsTable,
			Columns: []string{enterprisemember.BudgetPeriodsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisememberbudgetperiod.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BudgetReservationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.BudgetReservationsTable,
			Columns: []string{enterprisemember.BudgetReservationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisememberbudgetreservation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBudgetReservationsIDs(); len(nodes) > 0 && !_u.mutation.BudgetReservationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.BudgetReservationsTable,
			Columns: []string{enterprisemember.BudgetReservationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisememberbudgetreservation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BudgetReservationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.BudgetReservationsTable,
			Columns: []string{enterprisemember.BudgetReservationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisememberbudgetreservation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BudgetEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.BudgetEntriesTable,
			Columns: []string{enterprisemember.BudgetEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisememberbudgetentry.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBudgetEntriesIDs(); len(nodes) > 0 && !_u.mutation.BudgetEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.BudgetEntriesTable,
			Columns: []string{enterprisemember.BudgetEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisememberbudgetentry.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BudgetEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   enterprisemember.BudgetEntriesTable,
			Columns: []string{enterprisemember.BudgetEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisememberbudgetentry.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EnterpriseMember{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{enterprisemember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
