// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/enterprisemember"
	"github.com/Wei-Shaw/sub2api/ent/enterprisememberbudgetreservation"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// EnterpriseMemberBudgetReservationUpdate is the builder for updating EnterpriseMemberBudgetReservation entities.
type EnterpriseMemberBudgetReservationUpdate struct {
	config
	hooks    []Hook
	mutation *EnterpriseMemberBudgetReservationMutation
}

// Where appends a list predicates to the EnterpriseMemberBudgetReservationUpdate builder.
func (_u *EnterpriseMemberBudgetReservationUpdate) Where(ps ...predicate.EnterpriseMemberBudgetReservation) *EnterpriseMemberBudgetReservationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *EnterpriseMemberBudgetReservationUpdate) SetRequestID(v string) *EnterpriseMemberBudgetReservationUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *EnterpriseMemberBudgetReservationUpdate) SetNillableRequestID(v *string) *EnterpriseMemberBudgetReservationUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetMemberID sets the "member_id" field.
func (_u *EnterpriseMemberBudgetReservationUpdate) SetMemberID(v int64) *EnterpriseMemberBudgetReservationUpdate {
	_u.mutation.SetMemberID(v)
	return _u
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (_u *EnterpriseMemberBudgetReservationUpdate) SetNillableMemberID(v *int64) *EnterpriseMemberBudgetReservationUpdate {
	if v != nil {
		_u.SetMemberID(*v)
	}
	return _u
}

// SetPeriodStart sets the "period_start" field.
func (_u *EnterpriseMemberBudgetReservationUpdate) SetPeriodStart(v time.Time) *EnterpriseMemberBudgetReservationUpdate {
	_u.mutation.SetPeriodStart(v)
	return _u
}

// SetNillablePeriodStart sets the "period_start" field if the given value is not nil.
func (_u *EnterpriseMemberBudgetReservationUpdate) SetNillablePeriodStart(v *time.Time) *EnterpriseMemberBudgetReservationUpdate {
	if v != nil {
		_u.SetPeriodStart(*v)
	}
	return _u
}

// SetReservedUsd sets the "reserved_usd" field.
func (_u *EnterpriseMemberBudgetReservationUpdate) SetReservedUsd(v float64) *EnterpriseMemberBudgetReservationUpdate {
	_u.mutation.ResetReservedUsd()
	_u.mutation.SetReservedUsd(v)
	return _u
}

// SetNillableReservedUsd sets the "reserved_usd" field if the given value is not nil.
func (_u *EnterpriseMemberBudgetReservationUpdate) SetNillableReservedUsd(v *float64) *EnterpriseMemberBudgetReservationUpdate {
	if v != nil {
		_u.SetReservedUsd(*v)
	}
	return _u
}

// AddReservedUsd adds value to the "reserved_usd" field.
func (_u *EnterpriseMemberBudgetReservationUpdate) AddReservedUsd(v float64) *EnterpriseMemberBudgetReservationUpdate {
	_u.mutation.AddReservedUsd(v)
	return _u
}

// SetActualUsd sets the "actual_usd" field.
func (_u *EnterpriseMemberBudgetReservationUpdate) SetActualUsd(v float64) *EnterpriseMemberBudgetReservationUpdate {
	_u.mutation.ResetActualUsd()
	_u.mutation.SetActualUsd(v)
	return _u
}

// SetNillableActualUsd sets the "actual_usd" field if the given value is not nil.
func (_u *EnterpriseMemberBudgetReservationUpdate) SetNillableActualUsd(v *float64) *EnterpriseMemberBudgetReservationUpdate {
	if v != nil {
		_u.SetActualUsd(*v)
	}
	return _u
}

// AddActualUsd adds value to the "actual_usd" field.
func (_u *EnterpriseMemberBudgetReservationUpdate) AddActualUsd(v float64) *EnterpriseMemberBudgetReservationUpdate {
	_u.mutation.AddActualUsd(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *EnterpriseMemberBudgetReservationUpdate) SetStatus(v string) *EnterpriseMemberBudgetReservationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EnterpriseMemberBudgetReservationUpdate) SetNillableStatus(v *string) *EnterpriseMemberBudgetReservationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *EnterpriseMemberBudgetReservationUpdate) SetUsageLogID(v int64) *EnterpriseMemberBudgetReservationUpdate {
	_u.mutation.ResetUsageLogID()
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *EnterpriseMemberBudgetReservationUpdate) SetNillableUsageLogID(v *int64) *EnterpriseMemberBudgetReservationUpdate {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// AddUsageLogID adds value to the "usage_log_id" field.
func (_u *EnterpriseMemberBudgetReservationUpdate) AddUsageLogID(v int64) *EnterpriseMemberBudgetReservationUpdate {
	_u.mutation.AddUsageLogID(v)
	return _u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (_u *EnterpriseMemberBudgetReservationUpdate) ClearUsageLogID() *EnterpriseMemberBudgetReservationUpdate {
	_u.mutation.ClearUsageLogID()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *EnterpriseMemberBudgetReservationUpdate) SetExpiresAt(v time.Time) *EnterpriseMemberBudgetReservationUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *EnterpriseMemberBudgetReservationUpdate) SetNillableExpiresAt(v *time.Time) *EnterpriseMemberBudgetReservationUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnterpriseMemberBudgetReservationUpdate) SetUpdatedAt(v time.Time) *EnterpriseMemberBudgetReservationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMember sets the "member" edge to the EnterpriseMember entity.
func (_u *EnterpriseMemberBudgetReservationUpdate) SetMember(v *EnterpriseMember) *EnterpriseMemberBudgetReservationUpdate {
	return _u.SetMemberID(v.ID)
}

// Mutation returns the EnterpriseMemberBudgetReservationMutation object of the builder.
func (_u *EnterpriseMemberBudgetReservationUpdate) Mutation() *EnterpriseMemberBudgetReservationMutation {
	return _u.mutation
}

// ClearMember clears the "member" edge to the EnterpriseMember entity.
func (_u *EnterpriseMemberBudgetReservationUpdate) ClearMember() *EnterpriseMemberBudgetReservationUpdate {
	_u.mutation.ClearMember()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EnterpriseMemberBudgetReservationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnterpriseMemberBudgetReservationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EnterpriseMemberBudgetReservationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnterpriseMemberBudgetReservationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnterpriseMemberBudgetReservationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := enterprisememberbudgetreservation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnterpriseMemberBudgetReservationUpdate) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := enterprisememberbudgetreservation.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "EnterpriseMemberBudgetReservation.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := enterprisememberbudgetreservation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EnterpriseMemberBudgetReservation.status": %w`, err)}
		}
	}
	if _u.mutation.MemberCleared() && len(_u.mutation.MemberIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EnterpriseMemberBudgetReservation.member"`)
	}
	return nil
}

func (_u *EnterpriseMemberBudgetReservationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(enterprisememberbudgetreservation.Table, enterprisememberbudgetreservation.Columns, sqlgraph.NewFieldSpec(enterprisememberbudgetreservation.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(enterprisememberbudgetreservation.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PeriodStart(); ok {
		_spec.SetField(enterprisememberbudgetreservation.FieldPeriodStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReservedUsd(); ok {
		_spec.SetField(enterprisememberbudgetreservation.FieldReservedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedReservedUsd(); ok {
		_spec.AddField(enterprisememberbudgetreservation.FieldReservedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ActualUsd(); ok {
		_spec.SetField(enterprisememberbudgetreservation.FieldActualUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualUsd(); ok {
		_spec.AddField(enterprisememberbudgetreservation.FieldActualUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(enterprisememberbudgetreservation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UsageLogID(); ok {
		_spec.SetField(enterprisememberbudgetreservation.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLogID(); ok {
		_spec.AddField(enterprisememberbudgetreservation.FieldUsageLogID, field.TypeInt64, value)
	}
	if _u.mutation.UsageLogIDCleared() {
		_spec.ClearField(enterprisememberbudgetreservation.FieldUsageLogID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(enterprisememberbudgetreservation.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(enterprisememberbudgetreservation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MemberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enterprisememberbudgetreservation.MemberTable,
			Columns: []string{enterprisememberbudgetreservation.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisemember.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enterprisememberbudgetreservation.MemberTable,
			Columns: []string{enterprisememberbudgetreservation.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisemember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{enterprisememberbudgetreservation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EnterpriseMemberBudgetReservationUpdateOne is the builder for updating a single EnterpriseMemberBudgetReservation entity.
type EnterpriseMemberBudgetReservationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EnterpriseMemberBudgetReservationMutation
}

// SetRequestID sets the "request_id" field.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) SetRequestID(v string) *EnterpriseMemberBudgetReservationUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) SetNillableRequestID(v *string) *EnterpriseMemberBudgetReservationUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetMemberID sets the "member_id" field.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) SetMemberID(v int64) *EnterpriseMemberBudgetReservationUpdateOne {
	_u.mutation.SetMemberID(v)
	return _u
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) SetNillableMemberID(v *int64) *EnterpriseMemberBudgetReservationUpdateOne {
	if v != nil {
		_u.SetMemberID(*v)
	}
	return _u
}

// SetPeriodStart sets the "period_start" field.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) SetPeriodStart(v time.Time) *EnterpriseMemberBudgetReservationUpdateOne {
	_u.mutation.SetPeriodStart(v)
	return _u
}

// SetNillablePeriodStart sets the "period_start" field if the given value is not nil.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) SetNillablePeriodStart(v *time.Time) *EnterpriseMemberBudgetReservationUpdateOne {
	if v != nil {
		_u.SetPeriodStart(*v)
	}
	return _u
}

// SetReservedUsd sets the "reserved_usd" field.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) SetReservedUsd(v float64) *EnterpriseMemberBudgetReservationUpdateOne {
	_u.mutation.ResetReservedUsd()
	_u.mutation.SetReservedUsd(v)
	return _u
}

// SetNillableReservedUsd sets the "reserved_usd" field if the given value is not nil.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) SetNillableReservedUsd(v *float64) *EnterpriseMemberBudgetReservationUpdateOne {
	if v != nil {
		_u.SetReservedUsd(*v)
	}
	return _u
}

// AddReservedUsd adds value to the "reserved_usd" field.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) AddReservedUsd(v float64) *EnterpriseMemberBudgetReservationUpdateOne {
	_u.mutation.AddReservedUsd(v)
	return _u
}

// SetActualUsd sets the "actual_usd" field.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) SetActualUsd(v float64) *EnterpriseMemberBudgetReservationUpdateOne {
	_u.mutation.ResetActualUsd()
	_u.mutation.SetActualUsd(v)
	return _u
}

// SetNillableActualUsd sets the "actual_usd" field if the given value is not nil.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) SetNillableActualUsd(v *float64) *EnterpriseMemberBudgetReservationUpdateOne {
	if v != nil {
		_u.SetActualUsd(*v)
	}
	return _u
}

// AddActualUsd adds value to the "actual_usd" field.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) AddActualUsd(v float64) *EnterpriseMemberBudgetReservationUpdateOne {
	_u.mutation.AddActualUsd(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) SetStatus(v string) *EnterpriseMemberBudgetReservationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) SetNillableStatus(v *string) *EnterpriseMemberBudgetReservationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) SetUsageLogID(v int64) *EnterpriseMemberBudgetReservationUpdateOne {
	_u.mutation.ResetUsageLogID()
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) SetNillableUsageLogID(v *int64) *EnterpriseMemberBudgetReservationUpdateOne {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// AddUsageLogID adds value to the "usage_log_id" field.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) AddUsageLogID(v int64) *EnterpriseMemberBudgetReservationUpdateOne {
	_u.mutation.AddUsageLogID(v)
	return _u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) ClearUsageLogID() *EnterpriseMemberBudgetReservationUpdateOne {
	_u.mutation.ClearUsageLogID()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) SetExpiresAt(v time.Time) *EnterpriseMemberBudgetReservationUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) SetNillableExpiresAt(v *time.Time) *EnterpriseMemberBudgetReservationUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) SetUpdatedAt(v time.Time) *EnterpriseMemberBudgetReservationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMember sets the "member" edge to the EnterpriseMember entity.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) SetMember(v *EnterpriseMember) *EnterpriseMemberBudgetReservationUpdateOne {
	return _u.SetMemberID(v.ID)
}

// Mutation returns the EnterpriseMemberBudgetReservationMutation object of the builder.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) Mutation() *EnterpriseMemberBudgetReservationMutation {
	return _u.mutation
}

// ClearMember clears the "member" edge to the EnterpriseMember entity.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) ClearMember() *EnterpriseMemberBudgetReservationUpdateOne {
	_u.mutation.ClearMember()
	return _u
}

// Where appends a list predicates to the EnterpriseMemberBudgetReservationUpdate builder.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) Where(ps ...predicate.EnterpriseMemberBudgetReservation) *EnterpriseMemberBudgetReservationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) Select(field string, fields ...string) *EnterpriseMemberBudgetReservationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EnterpriseMemberBudgetReservation entity.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) Save(ctx context.Context) (*EnterpriseMemberBudgetReservation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) SaveX(ctx context.Context) *EnterpriseMemberBudgetReservation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := enterprisememberbudgetreservation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnterpriseMemberBudgetReservationUpdateOne) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := enterprisememberbudgetreservation.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "EnterpriseMemberBudgetReservation.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := enterprisememberbudgetreservation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "EnterpriseMemberBudgetReservation.status": %w`, err)}
		}
	}
	if _u.mutation.MemberCleared() && len(_u.mutation.MemberIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EnterpriseMemberBudgetReservation.member"`)
	}
	return nil
}

func (_u *EnterpriseMemberBudgetReservationUpdateOne) sqlSave(ctx context.Context) (_node *EnterpriseMemberBudgetReservation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(enterprisememberbudgetreservation.Table, enterprisememberbudgetreservation.Columns, sqlgraph.NewFieldSpec(enterprisememberbudgetreservation.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EnterpriseMemberBudgetReservation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, enterprisememberbudgetreservation.FieldID)
		for _, f := range fields {
			if !enterprisememberbudgetreservation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != enterprisememberbudgetreservation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(enterprisememberbudgetreservation.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PeriodStart(); ok {
		_spec.SetField(enterprisememberbudgetreservation.FieldPeriodStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReservedUsd(); ok {
		_spec.SetField(enterprisememberbudgetreservation.FieldReservedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedReservedUsd(); ok {
		_spec.AddField(enterprisememberbudgetreservation.FieldReservedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ActualUsd(); ok {
		_spec.SetField(enterprisememberbudgetreservation.FieldActualUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualUsd(); ok {
		_spec.AddField(enterprisememberbudgetreservation.FieldActualUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(enterprisememberbudgetreservation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UsageLogID(); ok {
		_spec.SetField(enterprisememberbudgetreservation.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLogID(); ok {
		_spec.AddField(enterprisememberbudgetreservation.FieldUsageLogID, field.TypeInt64, value)
	}
	if _u.mutation.UsageLogIDCleared() {
		_spec.ClearField(enterprisememberbudgetreservation.FieldUsageLogID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(enterprisememberbudgetreservation.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(enterprisememberbudgetreservation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MemberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enterprisememberbudgetreservation.MemberTable,
			Columns: []string{enterprisememberbudgetreservation.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisemember.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enterprisememberbudgetreservation.MemberTable,
			Columns: []string{enterprisememberbudgetreservation.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisemember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EnterpriseMemberBudgetReservation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{enterprisememberbudgetreservation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
