// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/enterprisemember"
	"github.com/Wei-Shaw/sub2api/ent/enterprisememberbudgetentry"
)

// EnterpriseMemberBudgetEntryCreate is the builder for creating a EnterpriseMemberBudgetEntry entity.
type EnterpriseMemberBudgetEntryCreate struct {
	config
	mutation *EnterpriseMemberBudgetEntryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetMemberID sets the "member_id" field.
func (_c *EnterpriseMemberBudgetEntryCreate) SetMemberID(v int64) *EnterpriseMemberBudgetEntryCreate {
	_c.mutation.SetMemberID(v)
	return _c
}

// SetPeriodStart sets the "period_start" field.
func (_c *EnterpriseMemberBudgetEntryCreate) SetPeriodStart(v time.Time) *EnterpriseMemberBudgetEntryCreate {
	_c.mutation.SetPeriodStart(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *EnterpriseMemberBudgetEntryCreate) SetKind(v string) *EnterpriseMemberBudgetEntryCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *EnterpriseMemberBudgetEntryCreate) SetRequestID(v string) *EnterpriseMemberBudgetEntryCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *EnterpriseMemberBudgetEntryCreate) SetNillableRequestID(v *string) *EnterpriseMemberBudgetEntryCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetAmountUsd sets the "amount_usd" field.
func (_c *EnterpriseMemberBudgetEntryCreate) SetAmountUsd(v float64) *EnterpriseMemberBudgetEntryCreate {
	_c.mutation.SetAmountUsd(v)
	return _c
}

// SetUsageLogID sets the "usage_log_id" field.
func (_c *EnterpriseMemberBudgetEntryCreate) SetUsageLogID(v int64) *EnterpriseMemberBudgetEntryCreate {
	_c.mutation.SetUsageLogID(v)
	return _c
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_c *EnterpriseMemberBudgetEntryCreate) SetNillableUsageLogID(v *int64) *EnterpriseMemberBudgetEntryCreate {
	if v != nil {
		_c.SetUsageLogID(*v)
	}
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *EnterpriseMemberBudgetEntryCreate) SetIdempotencyKey(v string) *EnterpriseMemberBudgetEntryCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetActorUserID sets the "actor_user_id" field.
func (_c *EnterpriseMemberBudgetEntryCreate) SetActorUserID(v int64) *EnterpriseMemberBudgetEntryCreate {
	_c.mutation.SetActorUserID(v)
	return _c
}

// SetNillableActorUserID sets the "actor_user_id" field if the given value is not nil.
func (_c *EnterpriseMemberBudgetEntryCreate) SetNillableActorUserID(v *int64) *EnterpriseMemberBudgetEntryCreate {
	if v != nil {
		_c.SetActorUserID(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *EnterpriseMemberBudgetEntryCreate) SetNote(v string) *EnterpriseMemberBudgetEntryCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *EnterpriseMemberBudgetEntryCreate) SetNillableNote(v *string) *EnterpriseMemberBudgetEntryCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EnterpriseMemberBudgetEntryCreate) SetCreatedAt(v time.Time) *EnterpriseMemberBudgetEntryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EnterpriseMemberBudgetEntryCreate) SetNillableCreatedAt(v *time.Time) *EnterpriseMemberBudgetEntryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetMember sets the "member" edge to the EnterpriseMember entity.
func (_c *EnterpriseMemberBudgetEntryCreate) SetMember(v *EnterpriseMember) *EnterpriseMemberBudgetEntryCreate {
	return _c.SetMemberID(v.ID)
}

// Mutation returns the EnterpriseMemberBudgetEntryMutation object of the builder.
func (_c *EnterpriseMemberBudgetEntryCreate) Mutation() *EnterpriseMemberBudgetEntryMutation {
	return _c.mutation
}

// Save creates the EnterpriseMemberBudgetEntry in the database.
func (_c *EnterpriseMemberBudgetEntryCreate) Save(ctx context.Context) (*EnterpriseMemberBudgetEntry, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EnterpriseMemberBudgetEntryCreate) SaveX(ctx context.Context) *EnterpriseMemberBudgetEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnterpriseMemberBudgetEntryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnterpriseMemberBudgetEntryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EnterpriseMemberBudgetEntryCreate) defaults() {
	if _, ok := _c.mutation.Note(); !ok {
		v := enterprisememberbudgetentry.DefaultNote
		_c.mutation.SetNote(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := enterprisememberbudgetentry.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EnterpriseMemberBudgetEntryCreate) check() error {
	if _, ok := _c.mutation.MemberID(); !ok {
		return &ValidationError{Name: "member_id", err: errors.New(`ent: missing required field "EnterpriseMemberBudgetEntry.member_id"`)}
	}
	if _, ok := _c.mutation.PeriodStart(); !ok {
		return &ValidationError{Name: "period_start", err: errors.New(`ent: missing required field "EnterpriseMemberBudgetEntry.period_start"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "EnterpriseMemberBudgetEntry.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := enterprisememberbudgetentry.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "EnterpriseMemberBudgetEntry.kind": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := enterprisememberbudgetentry.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "EnterpriseMemberBudgetEntry.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AmountUsd(); !ok {
		return &ValidationError{Name: "amount_usd", err: errors.New(`ent: missing required field "EnterpriseMemberBudgetEntry.amount_usd"`)}
	}
	if _, ok := _c.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotency_key", err: errors.New(`ent: missing required field "EnterpriseMemberBudgetEntry.idempotency_key"`)}
	}
	if v, ok := _c.mutation.IdempotencyKey(); ok {
		if err := enterprisememberbudgetentry.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "EnterpriseMemberBudgetEntry.idempotency_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Note(); !ok {
		return &ValidationError{Name: "note", err: errors.New(`ent: missing required field "EnterpriseMemberBudgetEntry.note"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EnterpriseMemberBudgetEntry.created_at"`)}
	}
	if len(_c.mutation.MemberIDs()) == 0 {
		return &ValidationError{Name: "member", err: errors.New(`ent: missing required edge "EnterpriseMemberBudgetEntry.member"`)}
	}
	return nil
}

func (_c *EnterpriseMemberBudgetEntryCreate) sqlSave(ctx context.Context) (*EnterpriseMemberBudgetEntry, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EnterpriseMemberBudgetEntryCreate) createSpec() (*EnterpriseMemberBudgetEntry, *sqlgraph.CreateSpec) {
	var (
		_node = &EnterpriseMemberBudgetEntry{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(enterprisememberbudgetentry.Table, sqlgraph.NewFieldSpec(enterprisememberbudgetentry.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.PeriodStart(); ok {
		_spec.SetField(enterprisememberbudgetentry.FieldPeriodStart, field.TypeTime, value)
		_node.PeriodStart = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(enterprisememberbudgetentry.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(enterprisememberbudgetentry.FieldRequestID, field.TypeString, value)
		_node.RequestID = &value
	}
	if value, ok := _c.mutation.AmountUsd(); ok {
		_spec.SetField(enterprisememberbudgetentry.FieldAmountUsd, field.TypeFloat64, value)
		_node.AmountUsd = value
	}
	if value, ok := _c.mutation.UsageLogID(); ok {
		_spec.SetField(enterprisememberbudgetentry.FieldUsageLogID, field.TypeInt64, value)
		_node.UsageLogID = &value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(enterprisememberbudgetentry.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = value
	}
	if value, ok := _c.mutation.ActorUserID(); ok {
		_spec.SetField(enterprisememberbudgetentry.FieldActorUserID, field.TypeInt64, value)
		_node.ActorUserID = &value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(enterprisememberbudgetentry.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(enterprisememberbudgetentry.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   enterprisememberbudgetentry.MemberTable,
			Columns: []string{enterprisememberbudgetentry.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(enterprisemember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MemberID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EnterpriseMemberBudgetEntry.Create().
//		SetMemberID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EnterpriseMemberBudgetEntryUpsert) {
//			SetMemberID(v+v).
//		}).
//		Exec(ctx)
func (_c *EnterpriseMemberBudgetEntryCreate) OnConflict(opts ...sql.ConflictOption) *EnterpriseMemberBudgetEntryUpsertOne {
	_c.conflict = opts
	return &EnterpriseMemberBudgetEntryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EnterpriseMemberBudgetEntry.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EnterpriseMemberBudgetEntryCreate) OnConflictColumns(columns ...string) *EnterpriseMemberBudgetEntryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EnterpriseMemberBudgetEntryUpsertOne{
		create: _c,
	}
}

type (
	// EnterpriseMemberBudgetEntryUpsertOne is the builder for "upsert"-ing
	//  one EnterpriseMemberBudgetEntry node.
	EnterpriseMemberBudgetEntryUpsertOne struct {
		create *EnterpriseMemberBudgetEntryCreate
	}

	// EnterpriseMemberBudgetEntryUpsert is the "OnConflict" setter.
	EnterpriseMemberBudgetEntryUpsert struct {
		*sql.UpdateSet
	}
)

// SetMemberID sets the "member_id" field.
func (u *EnterpriseMemberBudgetEntryUpsert) SetMemberID(v int64) *EnterpriseMemberBudgetEntryUpsert {
	u.Set(enterprisememberbudgetentry.FieldMemberID, v)
	return u
}

// UpdateMemberID sets the "member_id" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetEntryUpsert) UpdateMemberID() *EnterpriseMemberBudgetEntryUpsert {
	u.SetExcluded(enterprisememberbudgetentry.FieldMemberID)
	return u
}

// SetPeriodStart sets the "period_start" field.
func (u *EnterpriseMemberBudgetEntryUpsert) SetPeriodStart(v time.Time) *EnterpriseMemberBudgetEntryUpsert {
	u.Set(enterprisememberbudgetentry.FieldPeriodStart, v)
	return u
}

// UpdatePeriodStart sets the "period_start" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetEntryUpsert) UpdatePeriodStart() *EnterpriseMemberBudgetEntryUpsert {
	u.SetExcluded(enterprisememberbudgetentry.FieldPeriodStart)
	return u
}

// SetKind sets the "kind" field.
func (u *EnterpriseMemberBudgetEntryUpsert) SetKind(v string) *EnterpriseMemberBudgetEntryUpsert {
	u.Set(enterprisememberbudgetentry.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetEntryUpsert) UpdateKind() *EnterpriseMemberBudgetEntryUpsert {
	u.SetExcluded(enterprisememberbudgetentry.FieldKind)
	return u
}

// SetRequestID sets the "request_id" field.
func (u *EnterpriseMemberBudgetEntryUpsert) SetRequestID(v string) *EnterpriseMemberBudgetEntryUpsert {
	u.Set(enterprisememberbudgetentry.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetEntryUpsert) UpdateRequestID() *EnterpriseMemberBudgetEntryUpsert {
	u.SetExcluded(enterprisememberbudgetentry.FieldRequestID)
	return u
}

// ClearRequestID clears the value of the "request_id" field.
func (u *EnterpriseMemberBudgetEntryUpsert) ClearRequestID() *EnterpriseMemberBudgetEntryUpsert {
	u.SetNull(enterprisememberbudgetentry.FieldRequestID)
	return u
}

// SetAmountUsd sets the "amount_usd" field.
func (u *EnterpriseMemberBudgetEntryUpsert) SetAmountUsd(v float64) *EnterpriseMemberBudgetEntryUpsert {
	u.Set(enterprisememberbudgetentry.FieldAmountUsd, v)
	return u
}

// UpdateAmountUsd sets the "amount_usd" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetEntryUpsert) UpdateAmountUsd() *EnterpriseMemberBudgetEntryUpsert {
	u.SetExcluded(enterprisememberbudgetentry.FieldAmountUsd)
	return u
}

// AddAmountUsd adds v to the "amount_usd" field.
func (u *EnterpriseMemberBudgetEntryUpsert) AddAmountUsd(v float64) *EnterpriseMemberBudgetEntryUpsert {
	u.Add(enterprisememberbudgetentry.FieldAmountUsd, v)
	return u
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *EnterpriseMemberBudgetEntryUpsert) SetUsageLogID(v int64) *EnterpriseMemberBudgetEntryUpsert {
	u.Set(enterprisememberbudgetentry.FieldUsageLogID, v)
	return u
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetEntryUpsert) UpdateUsageLogID() *EnterpriseMemberBudgetEntryUpsert {
	u.SetExcluded(enterprisememberbudgetentry.FieldUsageLogID)
	return u
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *EnterpriseMemberBudgetEntryUpsert) AddUsageLogID(v int64) *EnterpriseMemberBudgetEntryUpsert {
	u.Add(enterprisememberbudgetentry.FieldUsageLogID, v)
	return u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *EnterpriseMemberBudgetEntryUpsert) ClearUsageLogID() *EnterpriseMemberBudgetEntryUpsert {
	u.SetNull(enterprisememberbudgetentry.FieldUsageLogID)
	return u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *EnterpriseMemberBudgetEntryUpsert) SetIdempotencyKey(v string) *EnterpriseMemberBudgetEntryUpsert {
	u.Set(enterprisememberbudgetentry.FieldIdempotencyKey, v)
	return u
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetEntryUpsert) UpdateIdempotencyKey() *EnterpriseMemberBudgetEntryUpsert {
	u.SetExcluded(enterprisememberbudgetentry.FieldIdempotencyKey)
	return u
}

// SetActorUserID sets the "actor_user_id" field.
func (u *EnterpriseMemberBudgetEntryUpsert) SetActorUserID(v int64) *EnterpriseMemberBudgetEntryUpsert {
	u.Set(enterprisememberbudgetentry.FieldActorUserID, v)
	return u
}

// UpdateActorUserID sets the "actor_user_id" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetEntryUpsert) UpdateActorUserID() *EnterpriseMemberBudgetEntryUpsert {
	u.SetExcluded(enterprisememberbudgetentry.FieldActorUserID)
	return u
}

// AddActorUserID adds v to the "actor_user_id" field.
func (u *EnterpriseMemberBudgetEntryUpsert) AddActorUserID(v int64) *EnterpriseMemberBudgetEntryUpsert {
	u.Add(enterprisememberbudgetentry.FieldActorUserID, v)
	return u
}

// ClearActorUserID clears the value of the "actor_user_id" field.
func (u *EnterpriseMemberBudgetEntryUpsert) ClearActorUserID() *EnterpriseMemberBudgetEntryUpsert {
	u.SetNull(enterprisememberbudgetentry.FieldActorUserID)
	return u
}

// SetNote sets the "note" field.
func (u *EnterpriseMemberBudgetEntryUpsert) SetNote(v string) *EnterpriseMemberBudgetEntryUpsert {
	u.Set(enterprisememberbudgetentry.FieldNote, v)
	return u
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetEntryUpsert) UpdateNote() *EnterpriseMemberBudgetEntryUpsert {
	u.SetExcluded(enterprisememberbudgetentry.FieldNote)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.EnterpriseMemberBudgetEntry.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EnterpriseMemberBudgetEntryUpsertOne) UpdateNewValues() *EnterpriseMemberBudgetEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(enterprisememberbudgetentry.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EnterpriseMemberBudgetEntry.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EnterpriseMemberBudgetEntryUpsertOne) Ignore() *EnterpriseMemberBudgetEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EnterpriseMemberBudgetEntryUpsertOne) DoNothing() *EnterpriseMemberBudgetEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EnterpriseMemberBudgetEntryCreate.OnConflict
// documentation for more info.
func (u *EnterpriseMemberBudgetEntryUpsertOne) Update(set func(*EnterpriseMemberBudgetEntryUpsert)) *EnterpriseMemberBudgetEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EnterpriseMemberBudgetEntryUpsert{UpdateSet: update})
	}))
	return u
}

// SetMemberID sets the "member_id" field.
func (u *EnterpriseMemberBudgetEntryUpsertOne) SetMemberID(v int64) *EnterpriseMemberBudgetEntryUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.SetMemberID(v)
	})
}

// UpdateMemberID sets the "member_id" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetEntryUpsertOne) UpdateMemberID() *EnterpriseMemberBudgetEntryUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.UpdateMemberID()
	})
}

// SetPeriodStart sets the "period_start" field.
func (u *EnterpriseMemberBudgetEntryUpsertOne) SetPeriodStart(v time.Time) *EnterpriseMemberBudgetEntryUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.SetPeriodStart(v)
	})
}

// UpdatePeriodStart sets the "period_start" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetEntryUpsertOne) UpdatePeriodStart() *EnterpriseMemberBudgetEntryUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.UpdatePeriodStart()
	})
}

// SetKind sets the "kind" field.
func (u *EnterpriseMemberBudgetEntryUpsertOne) SetKind(v string) *EnterpriseMemberBudgetEntryUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetEntryUpsertOne) UpdateKind() *EnterpriseMemberBudgetEntryUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.UpdateKind()
	})
}

// SetRequestID sets the "request_id" field.
func (u *EnterpriseMemberBudgetEntryUpsertOne) SetRequestID(v string) *EnterpriseMemberBudgetEntryUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetEntryUpsertOne) UpdateRequestID() *EnterpriseMemberBudgetEntryUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *EnterpriseMemberBudgetEntryUpsertOne) ClearRequestID() *EnterpriseMemberBudgetEntryUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.ClearRequestID()
	})
}

// SetAmountUsd sets the "amount_usd" field.
func (u *EnterpriseMemberBudgetEntryUpsertOne) SetAmountUsd(v float64) *EnterpriseMemberBudgetEntryUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.SetAmountUsd(v)
	})
}

// AddAmountUsd adds v to the "amount_usd" field.
func (u *EnterpriseMemberBudgetEntryUpsertOne) AddAmountUsd(v float64) *EnterpriseMemberBudgetEntryUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.AddAmountUsd(v)
	})
}

// UpdateAmountUsd sets the "amount_usd" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetEntryUpsertOne) UpdateAmountUsd() *EnterpriseMemberBudgetEntryUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.UpdateAmountUsd()
	})
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *EnterpriseMemberBudgetEntryUpsertOne) SetUsageLogID(v int64) *EnterpriseMemberBudgetEntryUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.SetUsageLogID(v)
	})
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *EnterpriseMemberBudgetEntryUpsertOne) AddUsageLogID(v int64) *EnterpriseMemberBudgetEntryUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.AddUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetEntryUpsertOne) UpdateUsageLogID() *EnterpriseMemberBudgetEntryUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.UpdateUsageLogID()
	})
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *EnterpriseMemberBudgetEntryUpsertOne) ClearUsageLogID() *EnterpriseMemberBudgetEntryUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.ClearUsageLogID()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *EnterpriseMemberBudgetEntryUpsertOne) SetIdempotencyKey(v string) *EnterpriseMemberBudgetEntryUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetEntryUpsertOne) UpdateIdempotencyKey() *EnterpriseMemberBudgetEntryUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// SetActorUserID sets the "actor_user_id" field.
func (u *EnterpriseMemberBudgetEntryUpsertOne) SetActorUserID(v int64) *EnterpriseMemberBudgetEntryUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.SetActorUserID(v)
	})
}

// AddActorUserID adds v to the "actor_user_id" field.
func (u *EnterpriseMemberBudgetEntryUpsertOne) AddActorUserID(v int64) *EnterpriseMemberBudgetEntryUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.AddActorUserID(v)
	})
}

// UpdateActorUserID sets the "actor_user_id" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetEntryUpsertOne) UpdateActorUserID() *EnterpriseMemberBudgetEntryUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.UpdateActorUserID()
	})
}

// ClearActorUserID clears the value of the "actor_user_id" field.
func (u *EnterpriseMemberBudgetEntryUpsertOne) ClearActorUserID() *EnterpriseMemberBudgetEntryUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.ClearActorUserID()
	})
}

// SetNote sets the "note" field.
func (u *EnterpriseMemberBudgetEntryUpsertOne) SetNote(v string) *EnterpriseMemberBudgetEntryUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetEntryUpsertOne) UpdateNote() *EnterpriseMemberBudgetEntryUpsertOne {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.UpdateNote()
	})
}

// Exec executes the query.
func (u *EnterpriseMemberBudgetEntryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EnterpriseMemberBudgetEntryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EnterpriseMemberBudgetEntryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EnterpriseMemberBudgetEntryUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EnterpriseMemberBudgetEntryUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EnterpriseMemberBudgetEntryCreateBulk is the builder for creating many EnterpriseMemberBudgetEntry entities in bulk.
type EnterpriseMemberBudgetEntryCreateBulk struct {
	config
	err      error
	builders []*EnterpriseMemberBudgetEntryCreate
	conflict []sql.ConflictOption
}

// Save creates the EnterpriseMemberBudgetEntry entities in the database.
func (_c *EnterpriseMemberBudgetEntryCreateBulk) Save(ctx context.Context) ([]*EnterpriseMemberBudgetEntry, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EnterpriseMemberBudgetEntry, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EnterpriseMemberBudgetEntryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EnterpriseMemberBudgetEntryCreateBulk) SaveX(ctx context.Context) []*EnterpriseMemberBudgetEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnterpriseMemberBudgetEntryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnterpriseMemberBudgetEntryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EnterpriseMemberBudgetEntry.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EnterpriseMemberBudgetEntryUpsert) {
//			SetMemberID(v+v).
//		}).
//		Exec(ctx)
func (_c *EnterpriseMemberBudgetEntryCreateBulk) OnConflict(opts ...sql.ConflictOption) *EnterpriseMemberBudgetEntryUpsertBulk {
	_c.conflict = opts
	return &EnterpriseMemberBudgetEntryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EnterpriseMemberBudgetEntry.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EnterpriseMemberBudgetEntryCreateBulk) OnConflictColumns(columns ...string) *EnterpriseMemberBudgetEntryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EnterpriseMemberBudgetEntryUpsertBulk{
		create: _c,
	}
}

// EnterpriseMemberBudgetEntryUpsertBulk is the builder for "upsert"-ing
// a bulk of EnterpriseMemberBudgetEntry nodes.
type EnterpriseMemberBudgetEntryUpsertBulk struct {
	create *EnterpriseMemberBudgetEntryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.EnterpriseMemberBudgetEntry.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EnterpriseMemberBudgetEntryUpsertBulk) UpdateNewValues() *EnterpriseMemberBudgetEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(enterprisememberbudgetentry.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EnterpriseMemberBudgetEntry.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EnterpriseMemberBudgetEntryUpsertBulk) Ignore() *EnterpriseMemberBudgetEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EnterpriseMemberBudgetEntryUpsertBulk) DoNothing() *EnterpriseMemberBudgetEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EnterpriseMemberBudgetEntryCreateBulk.OnConflict
// documentation for more info.
func (u *EnterpriseMemberBudgetEntryUpsertBulk) Update(set func(*EnterpriseMemberBudgetEntryUpsert)) *EnterpriseMemberBudgetEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EnterpriseMemberBudgetEntryUpsert{UpdateSet: update})
	}))
	return u
}

// SetMemberID sets the "member_id" field.
func (u *EnterpriseMemberBudgetEntryUpsertBulk) SetMemberID(v int64) *EnterpriseMemberBudgetEntryUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.SetMemberID(v)
	})
}

// UpdateMemberID sets the "member_id" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetEntryUpsertBulk) UpdateMemberID() *EnterpriseMemberBudgetEntryUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.UpdateMemberID()
	})
}

// SetPeriodStart sets the "period_start" field.
func (u *EnterpriseMemberBudgetEntryUpsertBulk) SetPeriodStart(v time.Time) *EnterpriseMemberBudgetEntryUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.SetPeriodStart(v)
	})
}

// UpdatePeriodStart sets the "period_start" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetEntryUpsertBulk) UpdatePeriodStart() *EnterpriseMemberBudgetEntryUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.UpdatePeriodStart()
	})
}

// SetKind sets the "kind" field.
func (u *EnterpriseMemberBudgetEntryUpsertBulk) SetKind(v string) *EnterpriseMemberBudgetEntryUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetEntryUpsertBulk) UpdateKind() *EnterpriseMemberBudgetEntryUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.UpdateKind()
	})
}

// SetRequestID sets the "request_id" field.
func (u *EnterpriseMemberBudgetEntryUpsertBulk) SetRequestID(v string) *EnterpriseMemberBudgetEntryUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetEntryUpsertBulk) UpdateRequestID() *EnterpriseMemberBudgetEntryUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *EnterpriseMemberBudgetEntryUpsertBulk) ClearRequestID() *EnterpriseMemberBudgetEntryUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.ClearRequestID()
	})
}

// SetAmountUsd sets the "amount_usd" field.
func (u *EnterpriseMemberBudgetEntryUpsertBulk) SetAmountUsd(v float64) *EnterpriseMemberBudgetEntryUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.SetAmountUsd(v)
	})
}

// AddAmountUsd adds v to the "amount_usd" field.
func (u *EnterpriseMemberBudgetEntryUpsertBulk) AddAmountUsd(v float64) *EnterpriseMemberBudgetEntryUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.AddAmountUsd(v)
	})
}

// UpdateAmountUsd sets the "amount_usd" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetEntryUpsertBulk) UpdateAmountUsd() *EnterpriseMemberBudgetEntryUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.UpdateAmountUsd()
	})
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *EnterpriseMemberBudgetEntryUpsertBulk) SetUsageLogID(v int64) *EnterpriseMemberBudgetEntryUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.SetUsageLogID(v)
	})
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *EnterpriseMemberBudgetEntryUpsertBulk) AddUsageLogID(v int64) *EnterpriseMemberBudgetEntryUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.AddUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetEntryUpsertBulk) UpdateUsageLogID() *EnterpriseMemberBudgetEntryUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.UpdateUsageLogID()
	})
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *EnterpriseMemberBudgetEntryUpsertBulk) ClearUsageLogID() *EnterpriseMemberBudgetEntryUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.ClearUsageLogID()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *EnterpriseMemberBudgetEntryUpsertBulk) SetIdempotencyKey(v string) *EnterpriseMemberBudgetEntryUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetEntryUpsertBulk) UpdateIdempotencyKey() *EnterpriseMemberBudgetEntryUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// SetActorUserID sets the "actor_user_id" field.
func (u *EnterpriseMemberBudgetEntryUpsertBulk) SetActorUserID(v int64) *EnterpriseMemberBudgetEntryUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.SetActorUserID(v)
	})
}

// AddActorUserID adds v to the "actor_user_id" field.
func (u *EnterpriseMemberBudgetEntryUpsertBulk) AddActorUserID(v int64) *EnterpriseMemberBudgetEntryUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.AddActorUserID(v)
	})
}

// UpdateActorUserID sets the "actor_user_id" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetEntryUpsertBulk) UpdateActorUserID() *EnterpriseMemberBudgetEntryUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.UpdateActorUserID()
	})
}

// ClearActorUserID clears the value of the "actor_user_id" field.
func (u *EnterpriseMemberBudgetEntryUpsertBulk) ClearActorUserID() *EnterpriseMemberBudgetEntryUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.ClearActorUserID()
	})
}

// SetNote sets the "note" field.
func (u *EnterpriseMemberBudgetEntryUpsertBulk) SetNote(v string) *EnterpriseMemberBudgetEntryUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *EnterpriseMemberBudgetEntryUpsertBulk) UpdateNote() *EnterpriseMemberBudgetEntryUpsertBulk {
	return u.Update(func(s *EnterpriseMemberBudgetEntryUpsert) {
		s.UpdateNote()
	})
}

// Exec executes the query.
func (u *EnterpriseMemberBudgetEntryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EnterpriseMemberBudgetEntryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EnterpriseMemberBudgetEntryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EnterpriseMemberBudgetEntryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
