// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/enterprisemember"
	"github.com/Wei-Shaw/sub2api/ent/enterprisemembergroupbinding"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// EnterpriseMemberGroupBindingQuery is the builder for querying EnterpriseMemberGroupBinding entities.
type EnterpriseMemberGroupBindingQuery struct {
	config
	ctx        *QueryContext
	order      []enterprisemembergroupbinding.OrderOption
	inters     []Interceptor
	predicates []predicate.EnterpriseMemberGroupBinding
	withMember *EnterpriseMemberQuery
	withGroup  *GroupQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EnterpriseMemberGroupBindingQuery builder.
func (_q *EnterpriseMemberGroupBindingQuery) Where(ps ...predicate.EnterpriseMemberGroupBinding) *EnterpriseMemberGroupBindingQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *EnterpriseMemberGroupBindingQuery) Limit(limit int) *EnterpriseMemberGroupBindingQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *EnterpriseMemberGroupBindingQuery) Offset(offset int) *EnterpriseMemberGroupBindingQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *EnterpriseMemberGroupBindingQuery) Unique(unique bool) *EnterpriseMemberGroupBindingQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *EnterpriseMemberGroupBindingQuery) Order(o ...enterprisemembergroupbinding.OrderOption) *EnterpriseMemberGroupBindingQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryMember chains the current query on the "member" edge.
func (_q *EnterpriseMemberGroupBindingQuery) QueryMember() *EnterpriseMemberQuery {
	query := (&EnterpriseMemberClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(enterprisemembergroupbinding.Table, enterprisemembergroupbinding.MemberColumn, selector),
			sqlgraph.To(enterprisemember.Table, enterprisemember.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, enterprisemembergroupbinding.MemberTable, enterprisemembergroupbinding.MemberColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGroup chains the current query on the "group" edge.
func (_q *EnterpriseMemberGroupBindingQuery) QueryGroup() *GroupQuery {
	query := (&GroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(enterprisemembergroupbinding.Table, enterprisemembergroupbinding.GroupColumn, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, enterprisemembergroupbinding.GroupTable, enterprisemembergroupbinding.GroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first EnterpriseMemberGroupBinding entity from the query.
// Returns a *NotFoundError when no EnterpriseMemberGroupBinding was found.
func (_q *EnterpriseMemberGroupBindingQuery) First(ctx context.Context) (*EnterpriseMemberGroupBinding, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{enterprisemembergroupbinding.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *EnterpriseMemberGroupBindingQuery) FirstX(ctx context.Context) *EnterpriseMemberGroupBinding {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// Only returns a single EnterpriseMemberGroupBinding entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EnterpriseMemberGroupBinding entity is found.
// Returns a *NotFoundError when no EnterpriseMemberGroupBinding entities are found.
func (_q *EnterpriseMemberGroupBindingQuery) Only(ctx context.Context) (*EnterpriseMemberGroupBinding, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{enterprisemembergroupbinding.Label}
	default:
		return nil, &NotSingularError{enterprisemembergroupbinding.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *EnterpriseMemberGroupBindingQuery) OnlyX(ctx context.Context) *EnterpriseMemberGroupBinding {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// All executes the query and returns a list of EnterpriseMemberGroupBindings.
func (_q *EnterpriseMemberGroupBindingQuery) All(ctx context.Context) ([]*EnterpriseMemberGroupBinding, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EnterpriseMemberGroupBinding, *EnterpriseMemberGroupBindingQuery]()
	return withInterceptors[[]*EnterpriseMemberGroupBinding](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *EnterpriseMemberGroupBindingQuery) AllX(ctx context.Context) []*EnterpriseMemberGroupBinding {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// Count returns the count of the given query.
func (_q *EnterpriseMemberGroupBindingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*EnterpriseMemberGroupBindingQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *EnterpriseMemberGroupBindingQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *EnterpriseMemberGroupBindingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.First(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *EnterpriseMemberGroupBindingQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EnterpriseMemberGroupBindingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *EnterpriseMemberGroupBindingQuery) Clone() *EnterpriseMemberGroupBindingQuery {
	if _q == nil {
		return nil
	}
	return &EnterpriseMemberGroupBindingQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]enterprisemembergroupbinding.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.EnterpriseMemberGroupBinding{}, _q.predicates...),
		withMember: _q.withMember.Clone(),
		withGroup:  _q.withGroup.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithMember tells the query-builder to eager-load the nodes that are connected to
// the "member" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EnterpriseMemberGroupBindingQuery) WithMember(opts ...func(*EnterpriseMemberQuery)) *EnterpriseMemberGroupBindingQuery {
	query := (&EnterpriseMemberClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMember = query
	return _q
}

// WithGroup tells the query-builder to eager-load the nodes that are connected to
// the "group" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *EnterpriseMemberGroupBindingQuery) WithGroup(opts ...func(*GroupQuery)) *EnterpriseMemberGroupBindingQuery {
	query := (&GroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGroup = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MemberID int64 `json:"member_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EnterpriseMemberGroupBinding.Query().
//		GroupBy(enterprisemembergroupbinding.FieldMemberID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *EnterpriseMemberGroupBindingQuery) GroupBy(field string, fields ...string) *EnterpriseMemberGroupBindingGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EnterpriseMemberGroupBindingGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = enterprisemembergroupbinding.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MemberID int64 `json:"member_id,omitempty"`
//	}
//
//	client.EnterpriseMemberGroupBinding.Query().
//		Select(enterprisemembergroupbinding.FieldMemberID).
//		Scan(ctx, &v)
func (_q *EnterpriseMemberGroupBindingQuery) Select(fields ...string) *EnterpriseMemberGroupBindingSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &EnterpriseMemberGroupBindingSelect{EnterpriseMemberGroupBindingQuery: _q}
	sbuild.label = enterprisemembergroupbinding.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EnterpriseMemberGroupBindingSelect configured with the given aggregations.
func (_q *EnterpriseMemberGroupBindingQuery) Aggregate(fns ...AggregateFunc) *EnterpriseMemberGroupBindingSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *EnterpriseMemberGroupBindingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !enterprisemembergroupbinding.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *EnterpriseMemberGroupBindingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EnterpriseMemberGroupBinding, error) {
	var (
		nodes       = []*EnterpriseMemberGroupBinding{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withMember != nil,
			_q.withGroup != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EnterpriseMemberGroupBinding).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EnterpriseMemberGroupBinding{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withMember; query != nil {
		if err := _q.loadMember(ctx, query, nodes, nil,
			func(n *EnterpriseMemberGroupBinding, e *EnterpriseMember) { n.Edges.Member = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGroup; query != nil {
		if err := _q.loadGroup(ctx, query, nodes, nil,
			func(n *EnterpriseMemberGroupBinding, e *Group) { n.Edges.Group = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *EnterpriseMemberGroupBindingQuery) loadMember(ctx context.Context, query *EnterpriseMemberQuery, nodes []*EnterpriseMemberGroupBinding, init func(*EnterpriseMemberGroupBinding), assign func(*EnterpriseMemberGroupBinding, *EnterpriseMember)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*EnterpriseMemberGroupBinding)
	for i := range nodes {
		fk := nodes[i].MemberID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(enterprisemember.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "member_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *EnterpriseMemberGroupBindingQuery) loadGroup(ctx context.Context, query *GroupQuery, nodes []*EnterpriseMemberGroupBinding, init func(*EnterpriseMemberGroupBinding), assign func(*EnterpriseMemberGroupBinding, *Group)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*EnterpriseMemberGroupBinding)
	for i := range nodes {
		fk := nodes[i].GroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(group.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *EnterpriseMemberGroupBindingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Unique = false
	_spec.Node.Columns = nil
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *EnterpriseMemberGroupBindingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(enterprisemembergroupbinding.Table, enterprisemembergroupbinding.Columns, nil)
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		for i := range fields {
			_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
		}
		if _q.withMember != nil {
			_spec.Node.AddColumnOnce(enterprisemembergroupbinding.FieldMemberID)
		}
		if _q.withGroup != nil {
			_spec.Node.AddColumnOnce(enterprisemembergroupbinding.FieldGroupID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *EnterpriseMemberGroupBindingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(enterprisemembergroupbinding.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = enterprisemembergroupbinding.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *EnterpriseMemberGroupBindingQuery) ForUpdate(opts ...sql.LockOption) *EnterpriseMemberGroupBindingQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *EnterpriseMemberGroupBindingQuery) ForShare(opts ...sql.LockOption) *EnterpriseMemberGroupBindingQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// EnterpriseMemberGroupBindingGroupBy is the group-by builder for EnterpriseMemberGroupBinding entities.
type EnterpriseMemberGroupBindingGroupBy struct {
	selector
	build *EnterpriseMemberGroupBindingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *EnterpriseMemberGroupBindingGroupBy) Aggregate(fns ...AggregateFunc) *EnterpriseMemberGroupBindingGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *EnterpriseMemberGroupBindingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EnterpriseMemberGroupBindingQuery, *EnterpriseMemberGroupBindingGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *EnterpriseMemberGroupBindingGroupBy) sqlScan(ctx context.Context, root *EnterpriseMemberGroupBindingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EnterpriseMemberGroupBindingSelect is the builder for selecting fields of EnterpriseMemberGroupBinding entities.
type EnterpriseMemberGroupBindingSelect struct {
	*EnterpriseMemberGroupBindingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *EnterpriseMemberGroupBindingSelect) Aggregate(fns ...AggregateFunc) *EnterpriseMemberGroupBindingSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *EnterpriseMemberGroupBindingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EnterpriseMemberGroupBindingQuery, *EnterpriseMemberGroupBindingSelect](ctx, _s.EnterpriseMemberGroupBindingQuery, _s, _s.inters, v)
}

func (_s *EnterpriseMemberGroupBindingSelect) sqlScan(ctx context.Context, root *EnterpriseMemberGroupBindingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
