// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/enterprisememberbudgetreservation"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// EnterpriseMemberBudgetReservationDelete is the builder for deleting a EnterpriseMemberBudgetReservation entity.
type EnterpriseMemberBudgetReservationDelete struct {
	config
	hooks    []Hook
	mutation *EnterpriseMemberBudgetReservationMutation
}

// Where appends a list predicates to the EnterpriseMemberBudgetReservationDelete builder.
func (_d *EnterpriseMemberBudgetReservationDelete) Where(ps ...predicate.EnterpriseMemberBudgetReservation) *EnterpriseMemberBudgetReservationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *EnterpriseMemberBudgetReservationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EnterpriseMemberBudgetReservationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *EnterpriseMemberBudgetReservationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(enterprisememberbudgetreservation.Table, sqlgraph.NewFieldSpec(enterprisememberbudgetreservation.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// EnterpriseMemberBudgetReservationDeleteOne is the builder for deleting a single EnterpriseMemberBudgetReservation entity.
type EnterpriseMemberBudgetReservationDeleteOne struct {
	_d *EnterpriseMemberBudgetReservationDelete
}

// Where appends a list predicates to the EnterpriseMemberBudgetReservationDelete builder.
func (_d *EnterpriseMemberBudgetReservationDeleteOne) Where(ps ...predicate.EnterpriseMemberBudgetReservation) *EnterpriseMemberBudgetReservationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *EnterpriseMemberBudgetReservationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{enterprisememberbudgetreservation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EnterpriseMemberBudgetReservationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
