import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const viewPath = resolve(dirname(fileURLToPath(import.meta.url)), '../EnterpriseMembersView.vue')
const source = readFileSync(viewPath, 'utf8')

describe('EnterpriseMembersView layout contract', () => {
  it('stays inside the authenticated application shell', () => {
    expect(source).toContain('<AppLayout>')
    expect(source).toContain("import AppLayout from '@/components/layout/AppLayout.vue'")
  })

  it('uses the existing console visual language instead of a standalone product hero', () => {
    expect(source).not.toContain('enterprise-hero')
    expect(source).not.toContain('Member control plane')
    expect(source).not.toContain('max-w-[1500px]')
    expect(source).toContain('btn btn-primary')
    expect(source).toContain('<EmptyState')
  })

  it('renders members as a dense management list instead of a card grid', () => {
    expect(source).toContain('data-testid="enterprise-member-table"')
    expect(source).toContain('data-testid="enterprise-member-mobile-list"')
    expect(source).toContain('<table class="w-full min-w-[1680px] table-fixed text-left">')
    expect(source).toContain('data-testid="enterprise-member-name-column"')
    expect(source).toContain('data-testid="enterprise-member-code-column"')
    expect(source).toContain('class="overflow-hidden px-3 py-2 align-middle"')
    expect(source).toContain('class="block w-full truncate font-mono text-xs text-stone-500" :title="member.member_code"')
    expect(source).toContain('data-testid="enterprise-member-keys-column"')
    expect(source).toContain('data-testid="enterprise-member-groups-column"')
    expect(source).toContain('class="w-[560px] px-4 py-2.5 text-right"')
    expect(source).toContain('class="flex flex-nowrap justify-end gap-1.5"')
    expect(source).toContain("t('enterpriseMembers.copy.selectVisibleMembers')")
    expect(source).toContain("import { tableSelectionCheckboxClasses as selectionCheckboxClasses } from '@/utils/tableSelectionCheckbox'")
    expect(source).toContain(':class="selectionCheckboxClasses(allFilteredMembersSelected || someFilteredMembersSelected)"')
    expect(source).toContain(':class="selectionCheckboxClasses(selectedIds.has(member.id))"')
    expect(source).toContain('role="checkbox"')
    expect(source).toContain('name="check" size="xs" :stroke-width="2.5"')
    expect(source).not.toContain('class="grid gap-4 md:grid-cols-2 xl:grid-cols-3"')
    expect(source).not.toContain('min-h-[285px]')
    expect(source).not.toContain('mt-1 truncate text-sm font-semibold')
    expect(source).not.toContain('class="flex flex-wrap justify-end gap-1.5"')
    expect(source).not.toContain("t('enterpriseMembers.copy.keys') }} / {{ t('enterpriseMembers.copy.groups')")
    expect(source).not.toContain('px-3 py-4 align-top')
    expect(source).not.toContain('px-3 py-3 align-top')
    expect(source).not.toContain('class="h-4 w-4 rounded border-stone-300 text-emerald-600 focus:ring-emerald-500"')
    expect(source).not.toContain('manageNonLoginMemberIdentitiesKeysOrderedGroupsAndCalendarMonthBudgetsInOnePlace')
    expect(source).toContain("import Select, { type SelectOption } from '@/components/common/Select.vue'")
    expect(source).toContain('<Select v-model="statusFilter" :options="memberStatusFilterOptions" class="w-full" />')
    expect(source).toContain('<Select v-model="budgetFilter" :options="memberBudgetFilterOptions" class="w-full" />')
    expect(source).toContain('<Select v-model="sortBy" :options="memberSortOptions" class="w-full" />')
    expect(source).toContain('<Select v-model="archiveScope" :options="memberArchiveScopeOptions" class="w-full" @change="handleArchiveScopeChange" />')
    expect(source).toContain("const includeArchived = computed(() => archiveScope.value === 'with_archived')")
    expect(source).toContain("if (!includeArchived.value && statusFilter.value === 'archived') statusFilter.value = 'all'")
    expect(source).toContain("if (includeArchived.value) options.push({ value: 'archived'")
    expect(source).not.toContain('<select v-model="statusFilter"')
    expect(source).not.toContain('<select v-model="budgetFilter"')
    expect(source).not.toContain('<select v-model="sortBy"')
    expect(source).not.toContain(':aria-pressed="includeArchived"')
    expect(source).not.toContain("includeArchived ? 'eyeOff' : 'eye'")
  })

  it('keeps the member audit trail inside the existing member detail workflow', () => {
    expect(source).toContain("enterpriseMembersAPI.listAuditEvents(member.id)")
    expect(source).toContain('enterpriseMembersAPI.listOwnerAuditEvents()')
    expect(source).toContain("t('enterpriseMembers.copy.auditTrail')")
    expect(source).toContain("t('enterpriseMembers.copy.budgetLedger')")
  })

  it('uses durable import jobs instead of holding the commit request open', () => {
    expect(source).toContain('enterpriseMembersAPI.getImportJob(jobId)')
    expect(source).toContain('enterpriseMembersAPI.consumeImportResultSecrets(jobId, resultToken)')
    expect(source).toContain('enterpriseMembersAPI.downloadImportErrorReport(jobId)')
    expect(source).toContain("t('enterpriseMembers.copy.processingInBackground')")
    expect(source).toContain("const importCommitIdempotencyKey = ref('')")
    expect(source).toContain('idempotencyKey: importCommitIdempotencyKey.value')
    expect(source).toContain('reconcileImportCommitAfterError(preview.job_id, preview.token)')
    expect(source).toContain('preview.import_policy_version !== 2')
    expect(source).toContain("t('enterpriseMembers.copy.importPreviewProtocolUnavailable')")
    expect(source).not.toContain('importCommitFailedNoDataWasWritten')
  })

  it('offers explicit server-authoritative CSV and XLSX template downloads', () => {
    expect(source).toContain('data-testid="download-enterprise-member-csv-template"')
    expect(source).toContain('data-testid="download-enterprise-member-xlsx-template"')
    expect(source).toContain("t('enterpriseMembers.copy.downloadCsvTemplate')")
    expect(source).toContain("t('enterpriseMembers.copy.downloadXlsxTemplate')")
    expect(source).toContain("const templateDownloading = ref<'csv' | 'xlsx' | null>(null)")
    expect(source).toContain("enterpriseMembersAPI.downloadImportTemplate(format, t('enterpriseMembers.copy.importTemplateFilename'))")
    expect(source).toContain("t('enterpriseMembers.copy.importTemplateExternalFactsHint')")
    expect(source).toContain('importDefaultGroupIds')
    expect(source).toContain('activateMembers: importActivateMembers.value')
    expect(source).not.toContain("t('enterpriseMembers.copy.orderedGroups')</th><th>{{ t('enterpriseMembers.copy.validation')")
  })

  it('supports an atomic ordered-group batch for pending imports and existing members', () => {
    expect(source).toContain('enterpriseMembersAPI.batchReplaceGroups(targets, batchGroupIds.value, batchGroupMode.value)')
    expect(source).toContain("t('enterpriseMembers.copy.batchSetAccessibleGroups')")
    expect(source).toContain("t('enterpriseMembers.copy.configureImportedMembers')")
    expect(source).toContain('selectedIds.value = new Set(importResult.value.member_ids)')
    expect(source).toContain('version: update.version, group_ids: update.group_ids, status: update.status, updated_at: update.updated_at')
    expect(source).toContain("import ConfirmDialog from '@/components/common/ConfirmDialog.vue'")
    expect(source).toContain(':show="batchClearConfirmOpen"')
    expect(source).toContain("t('enterpriseMembers.dynamic.clearGroupsAndDisableMembersConfirm', { count: batchGroupTargetCount })")
    expect(source).toContain("batchGroupMode.value === 'replace' && batchGroupIds.value.length === 0")
    expect(source).toContain('if (batchClearIsDestructive.value) {')
    expect(source).toContain('batchClearConfirmOpen.value = true')
    expect(source).toContain('async function confirmBatchGroupClear()')
  })

  it('uses user-facing success copy for batch member updates', () => {
    expect(source).toContain('batchPolicySuccessMessage(input, updated.updated_count)')
    expect(source).toContain("'enterpriseMembers.dynamic.batchMembersEnabled'")
    expect(source).toContain("'enterpriseMembers.dynamic.batchMembersDisabled'")
    expect(source).toContain("'enterpriseMembers.dynamic.batchMembersUpdated'")
  })

  it('keeps the frozen import billing period visible in the successful result', () => {
    expect(source).toContain('importResult.period_start')
    expect(source).toContain('importResult.timezone')
    expect(source).toContain("t('enterpriseMembers.dynamic.importPeriod'")
  })

  it('keeps regular keys independent instead of presenting them as migration candidates', () => {
    expect(source).toContain("t('enterpriseMembers.copy.normalKeysRemainIndependent')")
    expect(source).toContain("t('enterpriseMembers.copy.manageRegularKeys')")
    expect(source).toContain("router.push('/keys')")
    expect(source).not.toContain('enterpriseMembersAPI.listAdoptableKeys(member.id)')
    expect(source).not.toContain('enterpriseMembersAPI.adoptKey(member, key.id)')
    expect(source).not.toContain("t('enterpriseMembers.copy.adoptExistingKeys')")
  })

  it('provides compact, localized member-key management with on-demand copy', () => {
    expect(source).not.toContain("import { keysAPI } from '@/api/keys'")
    expect(source).toContain('const detail = await enterpriseMembersAPI.revealKey(requestedMemberId, requestedKeyId)')
    expect(source).toContain('detail.id !== requestedKeyId || detail.member_id !== requestedMemberId')
    expect(source).toContain("clipboardCopy(detail.key, t('enterpriseMembers.copy.keyCopied'))")
    expect(source).toContain("t('enterpriseMembers.copy.copyMemberKey')")
    expect(source).toContain('memberKeyStatusBadgeClasses(key.status)')
    expect(source).toContain('memberKeyStatusLabel(key.status)')
    expect(source).toContain('<Select v-model="keyEditDraft.status" :options="memberKeyEditableStatusOptions"')
    expect(source).toContain('min-w-[960px]')
    expect(source).toContain('grid-cols-[minmax(210px,1.25fr)_160px_105px_155px_250px]')
    expect(source).toContain('<Icon name="trash" size="sm" />')
    expect(source).toContain('w-[76px] shrink-0 whitespace-nowrap')
    expect(source).toContain('class="btn btn-secondary btn-sm shrink-0 whitespace-nowrap" type="button" @click="openKeyEdit(key)"')
    expect(source).toContain('class="inline-flex shrink-0 items-center gap-1.5 whitespace-nowrap rounded-lg')
    expect(source).toContain('disabled:opacity-100')
    expect(source).toContain(':aria-busy="copyingMemberKeyId === key.id"')
    expect(source).toContain('<button v-if="!keyMember?.deleted_at" class="btn btn-secondary btn-sm w-[76px]')
    expect(source).toContain("copyingMemberKeyId === key.id ? 'refresh' : copiedMemberKeyId === key.id ? 'check' : 'clipboard'")
    expect(source).toContain("{{ t('enterpriseMembers.copy.copyMemberKey') }}")
    expect(source).not.toContain('{{ copyingMemberKeyId === key.id ?')
    expect(source).not.toContain('min-w-[920px]')
    expect(source).not.toContain('grid-cols-[minmax(210px,1.25fr)_160px_105px_155px_230px]')
    expect(source).not.toContain('grid-cols-[minmax(240px,1.35fr)_minmax(190px,0.9fr)_130px_185px_300px]')
    expect(source).not.toContain('{{ key.status }}')
  })

  it('keeps archived members read-only while allowing restore or permanent owner-facing removal', () => {
    expect(source).toContain(':show="Boolean(memberRemovalTarget)"')
    expect(source).toContain('@confirm="confirmRemoveMember"')
    expect(source).toContain("extractI18nErrorMessage(error, t, 'enterpriseMembers.errors'")
    expect(source).toContain('v-if="!member.deleted_at" class="btn btn-secondary btn-sm shrink-0 whitespace-nowrap" type="button" @click="openEdit(member)"')
    expect(source).toContain('v-if="keyMember?.deleted_at"')
    expect(source).toContain('v-if="!keyMember?.deleted_at" class="grid gap-3')
    expect(source).toContain('v-if="!budgetMember?.deleted_at" class="overflow-hidden rounded-3xl border border-dashed')
    expect(source).toContain('@click="restoreMember(member)"')
    expect(source).toContain("member.delete_strategy === 'hard_delete'")
    expect(source).toContain("t('enterpriseMembers.copy.deleteHistoricalMemberConfirm')")
    expect(source).not.toContain('member.can_permanently_delete')
    expect(source).not.toContain("t('enterpriseMembers.copy.archivedEvidenceRetained')")
    expect(source).not.toContain('if (!window.confirm(message)) return')
  })

  it('requires the shared confirmation dialog before single or bulk member status changes', () => {
    expect(source).toContain(':show="Boolean(memberStatusChangeRequest)"')
    expect(source).toContain(':danger="memberStatusChangeRequest?.status === \'disabled\'"')
    expect(source).toContain('@confirm="confirmMemberStatusChange"')
    expect(source).toContain('@cancel="cancelMemberStatusChange"')
    expect(source).toContain('memberStatusChangeRequest.value = {')
    expect(source).toContain('async function confirmMemberStatusChange()')
    expect(source).toContain("enterpriseMembersAPI.setStatus(request.members[0], request.status)")
    expect(source).toContain("enterpriseMembersAPI.createEnterpriseMemberOperationIdempotencyKey('member-batch')")
    expect(source).toContain('enterpriseMembersAPI.batchUpdate(operation.members, operation.input, operation.idempotencyKey)')
    expect(source).not.toContain('partialStatusFailures')
  })

  it('reuses the complete usage table for member request records without exposing upstream routing internals', () => {
    expect(source).toContain("import UsageTable from '@/components/admin/usage/UsageTable.vue'")
    expect(source).toContain("import { usageAPI } from '@/api/usage'")
    expect(source).toContain('return usageAPI.query({')
    expect(source).toContain('member_id: memberID')
    expect(source).toContain(':columns="budgetUsageRecordColumns"')
    expect(source).toContain(':show-account-billing="false"')
    expect(source).toContain(':show-upstream-endpoint="false"')
    expect(source).toContain("{ key: 'reasoning_effort', label: t('usage.reasoningEffort')")
    expect(source).toContain("{ key: 'ip_address', label: 'IP'")
    expect(source).toContain("{ key: 'billing_mode', label: t('admin.usage.billingMode')")
    expect(source).toContain("{ key: 'latency', label: t('usage.latency')")
    expect(source).toContain("t('enterpriseMembers.copy.requestRecords')")
    expect(source).toContain("t('enterpriseMembers.copy.showsMemberFacingKeyModelPublicGroupAndBilledCostOnlyUpstreamAccountChannelAndMarginDataRemainPr')")
    expect(source).not.toContain('record.account_id')
    expect(source).not.toContain('record.channel_id')
    expect(source).not.toContain('record.account_cost')
    expect(source).not.toContain('EnterpriseMemberUsageRecordsTable')
  })

  it('presents member budget usage as one monthly summary plus distinct rolling windows', () => {
    expect(source).toContain("t('enterpriseMembers.copy.monthlyBudgetOverview')")
    expect(source).toContain("t('enterpriseMembers.copy.monthlyBudget')")
    expect(source).toContain("t('enterpriseMembers.copy.usedThisMonth')")
    expect(source).toContain("'enterpriseMembers.copy.availableBudget'")
    expect(source).toContain('const budgetUsagePercentLabel = computed')
    expect(source).not.toContain('budgetSummary.reserved_usd')
    expect(source).not.toContain('budgetReservedPercent')
    expect(source).not.toContain("t('enterpriseMembers.copy.reservedAmount')")
    expect(source).toContain("t('enterpriseMembers.copy.budgetOverage')")
    expect(source).toContain("t('enterpriseMembers.copy.budgetRequestsStopped')")
    expect(source).toContain("t('enterpriseMembers.copy.monthlyUsageDetails')")
    expect(source).toContain("t('enterpriseMembers.copy.importedUsageRecord')")
    expect(source).not.toContain('const budgetCommittedUsd = computed')
    expect(source).not.toContain("t('enterpriseMembers.copy.budgetCommitted')")
    expect(source).not.toContain("t('enterpriseMembers.copy.periodActivity')")
    expect(source).toContain('v-if="budgetSummary.limit_usd > 0"')
    expect(source).toContain("t('enterpriseMembers.copy.monthlyLimitNotSet')")
    expect(source).toContain('v-if="hasMemberRateLimits"')
    expect(source).toContain("t('enterpriseMembers.copy.shortWindowLimits')")
    expect(source).toContain("t('enterpriseMembers.copy.limitNotSet')")
    expect(source).toContain("{ key: '5h', label: t('enterpriseMembers.copy.fiveHourWindow')")
    expect(source).toContain("{ key: '1d', label: t('enterpriseMembers.copy.oneDayWindow')")
    expect(source).toContain("{ key: '7d', label: t('enterpriseMembers.copy.sevenDayWindow')")
    expect(source).not.toContain('class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"')
    expect(source).not.toContain("t('enterpriseMembers.copy.currentPeriodStatus')")
  })

  it('keeps manual budget corrections behind an explicit advanced action', () => {
    expect(source).toContain('<details v-if="!budgetMember?.deleted_at"')
    expect(source).toContain("t('enterpriseMembers.copy.adjustUsedAmount')")
    expect(source).toContain("t('enterpriseMembers.copy.adjustUsedAmountHint')")
    expect(source).toContain("t('enterpriseMembers.copy.confirmAdjustment')")
    expect(source).toContain(':show="Boolean(pendingBudgetAdjustment)"')
    expect(source).toContain('@confirm="confirmBudgetAdjustment"')
    expect(source).toContain('const pendingBudgetAdjustment = ref<')
    expect(source).not.toContain("window.confirm(t('enterpriseMembers.copy.thisPostsAnImmutableAuditEntryContinue'))")
  })

  it('fills sparse member trend dates before rendering bounded daily bars', () => {
    expect(source).toContain("import { fillEnterpriseMemberUsageTrend } from '@/utils/enterpriseMemberUsageTrend'")
    expect(source).toContain('const normalizedBudgetTrend = computed')
    expect(source).toContain('v-for="point in normalizedBudgetTrend"')
    expect(source).toContain('width: `max(100%, ${normalizedBudgetTrend.length * 5}px)`')
    expect(source).toContain('gridTemplateColumns: `repeat(${normalizedBudgetTrend.length}, minmax(3px, 1fr))`')
    expect(source).toContain('v-if="point.actual_cost > 0"')
    expect(source).not.toContain('v-for="point in budgetAnalytics.trend"')
    expect(source).not.toContain('class="group relative min-w-[5px] flex-1 rounded-t')
  })

  it('links the member detail workflow to the dedicated member usage page with a durable member filter', () => {
    expect(source).toContain("t('enterpriseMembers.copy.viewFullUsageRecords')")
    expect(source).toContain("router.push({ name: 'EnterpriseMemberUsage', query: { tab: 'usage', member_id: String(member.id) } })")
  })

  it('uses formal locale keys instead of a page-local bilingual helper', () => {
    expect(source).not.toMatch(/\btext\(/)
    expect(source).not.toContain('const text =')
    expect(source).toContain("const { t, locale } = useI18n()")
  })

  it('explains the exact API key validation failure in import previews', () => {
    expect(source).toContain("issue.match(/^api_key_too_short_(\\d+)_(\\d+)$/)")
    expect(source).toContain("issue.match(/^api_key_too_long_(\\d+)_(\\d+)$/)")
    expect(source).toContain("api_key_invalid_characters: t('enterpriseMembers.copy.apiKeyInvalidCharacters')")
    expect(source).toContain("invalid_api_key: t('enterpriseMembers.copy.invalidApiKey')")
  })

  it('treats member identity, aggregate limits, usage adjustments, and accessible groups as durable product concepts', () => {
    expect(source).toContain("t('enterpriseMembers.copy.memberIdentifier')")
    expect(source).toContain(':disabled="Boolean(editingMember)"')
    expect(source).not.toContain("t('enterpriseMembers.copy.stableMemberCode')")
    expect(source).toContain('v-model.number="draft.rate_limit_5h"')
    expect(source).toContain('v-model.number="draft.rate_limit_1d"')
    expect(source).toContain('v-model.number="draft.rate_limit_7d"')
    expect(source).toContain('v-model.number="editorMonthlyUsed"')
    expect(source).toContain('v-model.number="editorUsage5h"')
    expect(source).not.toContain('<label v-if="editingMember" class="mt-3 block"><span class="input-label">{{ t(\'enterpriseMembers.copy.used\') }}</span>')
    expect(source).toContain("editingMember ? t('enterpriseMembers.copy.used') : t('enterpriseMembers.copy.initialUsed')")
    expect(source).toContain('monthly_used_usd: editorMonthlyUsed.value')
    expect(source).not.toContain('usage_opening_note')
    expect(source).not.toContain('editorAdjustmentNote')
    expect(source).not.toContain("t('enterpriseMembers.copy.adjustmentReason')")
    expect(source).toContain('enterpriseMembersAPI.setUsage(updated.id')
    expect(source).toContain("error.response?.data?.message || error.message || t('enterpriseMembers.copy.saveFailedPleaseRefreshAndRetry')")
    expect(source).toContain("t('enterpriseMembers.copy.memberAccessibleGroups')")
    expect(source).not.toContain("t('enterpriseMembers.copy.orderedGroupCandidates')")
  })
})
