// Code generated by ent, DO NOT EDIT.

package enterprisemember

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the enterprisemember type in the database.
	Label = "enterprise_member"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldEnterpriseUserID holds the string denoting the enterprise_user_id field in the database.
	FieldEnterpriseUserID = "enterprise_user_id"
	// FieldMemberCode holds the string denoting the member_code field in the database.
	FieldMemberCode = "member_code"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMonthlyLimitUsd holds the string denoting the monthly_limit_usd field in the database.
	FieldMonthlyLimitUsd = "monthly_limit_usd"
	// FieldRateLimit5h holds the string denoting the rate_limit_5h field in the database.
	FieldRateLimit5h = "rate_limit_5h"
	// FieldRateLimit1d holds the string denoting the rate_limit_1d field in the database.
	FieldRateLimit1d = "rate_limit_1d"
	// FieldRateLimit7d holds the string denoting the rate_limit_7d field in the database.
	FieldRateLimit7d = "rate_limit_7d"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldRemovedAt holds the string denoting the removed_at field in the database.
	FieldRemovedAt = "removed_at"
	// EdgeEnterpriseUser holds the string denoting the enterprise_user edge name in mutations.
	EdgeEnterpriseUser = "enterprise_user"
	// EdgeAPIKeys holds the string denoting the api_keys edge name in mutations.
	EdgeAPIKeys = "api_keys"
	// EdgeUsageLogs holds the string denoting the usage_logs edge name in mutations.
	EdgeUsageLogs = "usage_logs"
	// EdgeGroups holds the string denoting the groups edge name in mutations.
	EdgeGroups = "groups"
	// EdgeBudgetPeriods holds the string denoting the budget_periods edge name in mutations.
	EdgeBudgetPeriods = "budget_periods"
	// EdgeBudgetReservations holds the string denoting the budget_reservations edge name in mutations.
	EdgeBudgetReservations = "budget_reservations"
	// EdgeBudgetEntries holds the string denoting the budget_entries edge name in mutations.
	EdgeBudgetEntries = "budget_entries"
	// EdgeEnterpriseMemberGroupBindings holds the string denoting the enterprise_member_group_bindings edge name in mutations.
	EdgeEnterpriseMemberGroupBindings = "enterprise_member_group_bindings"
	// Table holds the table name of the enterprisemember in the database.
	Table = "enterprise_members"
	// EnterpriseUserTable is the table that holds the enterprise_user relation/edge.
	EnterpriseUserTable = "enterprise_members"
	// EnterpriseUserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	EnterpriseUserInverseTable = "users"
	// EnterpriseUserColumn is the table column denoting the enterprise_user relation/edge.
	EnterpriseUserColumn = "enterprise_user_id"
	// APIKeysTable is the table that holds the api_keys relation/edge.
	APIKeysTable = "api_keys"
	// APIKeysInverseTable is the table name for the APIKey entity.
	// It exists in this package in order to avoid circular dependency with the "apikey" package.
	APIKeysInverseTable = "api_keys"
	// APIKeysColumn is the table column denoting the api_keys relation/edge.
	APIKeysColumn = "member_id"
	// UsageLogsTable is the table that holds the usage_logs relation/edge.
	UsageLogsTable = "usage_logs"
	// UsageLogsInverseTable is the table name for the UsageLog entity.
	// It exists in this package in order to avoid circular dependency with the "usagelog" package.
	UsageLogsInverseTable = "usage_logs"
	// UsageLogsColumn is the table column denoting the usage_logs relation/edge.
	UsageLogsColumn = "member_id"
	// GroupsTable is the table that holds the groups relation/edge. The primary key declared below.
	GroupsTable = "enterprise_member_group_bindings"
	// GroupsInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupsInverseTable = "groups"
	// BudgetPeriodsTable is the table that holds the budget_periods relation/edge.
	BudgetPeriodsTable = "enterprise_member_budget_periods"
	// BudgetPeriodsInverseTable is the table name for the EnterpriseMemberBudgetPeriod entity.
	// It exists in this package in order to avoid circular dependency with the "enterprisememberbudgetperiod" package.
	BudgetPeriodsInverseTable = "enterprise_member_budget_periods"
	// BudgetPeriodsColumn is the table column denoting the budget_periods relation/edge.
	BudgetPeriodsColumn = "member_id"
	// BudgetReservationsTable is the table that holds the budget_reservations relation/edge.
	BudgetReservationsTable = "enterprise_member_budget_reservations"
	// BudgetReservationsInverseTable is the table name for the EnterpriseMemberBudgetReservation entity.
	// It exists in this package in order to avoid circular dependency with the "enterprisememberbudgetreservation" package.
	BudgetReservationsInverseTable = "enterprise_member_budget_reservations"
	// BudgetReservationsColumn is the table column denoting the budget_reservations relation/edge.
	BudgetReservationsColumn = "member_id"
	// BudgetEntriesTable is the table that holds the budget_entries relation/edge.
	BudgetEntriesTable = "enterprise_member_budget_entries"
	// BudgetEntriesInverseTable is the table name for the EnterpriseMemberBudgetEntry entity.
	// It exists in this package in order to avoid circular dependency with the "enterprisememberbudgetentry" package.
	BudgetEntriesInverseTable = "enterprise_member_budget_entries"
	// BudgetEntriesColumn is the table column denoting the budget_entries relation/edge.
	BudgetEntriesColumn = "member_id"
	// EnterpriseMemberGroupBindingsTable is the table that holds the enterprise_member_group_bindings relation/edge.
	EnterpriseMemberGroupBindingsTable = "enterprise_member_group_bindings"
	// EnterpriseMemberGroupBindingsInverseTable is the table name for the EnterpriseMemberGroupBinding entity.
	// It exists in this package in order to avoid circular dependency with the "enterprisemembergroupbinding" package.
	EnterpriseMemberGroupBindingsInverseTable = "enterprise_member_group_bindings"
	// EnterpriseMemberGroupBindingsColumn is the table column denoting the enterprise_member_group_bindings relation/edge.
	EnterpriseMemberGroupBindingsColumn = "member_id"
)

// Columns holds all SQL columns for enterprisemember fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldEnterpriseUserID,
	FieldMemberCode,
	FieldName,
	FieldStatus,
	FieldMonthlyLimitUsd,
	FieldRateLimit5h,
	FieldRateLimit1d,
	FieldRateLimit7d,
	FieldVersion,
	FieldRemovedAt,
}

var (
	// GroupsPrimaryKey and GroupsColumn2 are the table columns denoting the
	// primary key for the groups relation (M2M).
	GroupsPrimaryKey = []string{"member_id", "group_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// MemberCodeValidator is a validator for the "member_code" field. It is called by the builders before save.
	MemberCodeValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultMonthlyLimitUsd holds the default value on creation for the "monthly_limit_usd" field.
	DefaultMonthlyLimitUsd float64
	// DefaultRateLimit5h holds the default value on creation for the "rate_limit_5h" field.
	DefaultRateLimit5h float64
	// DefaultRateLimit1d holds the default value on creation for the "rate_limit_1d" field.
	DefaultRateLimit1d float64
	// DefaultRateLimit7d holds the default value on creation for the "rate_limit_7d" field.
	DefaultRateLimit7d float64
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion int64
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(int64) error
)

// OrderOption defines the ordering options for the EnterpriseMember queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByEnterpriseUserID orders the results by the enterprise_user_id field.
func ByEnterpriseUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnterpriseUserID, opts...).ToFunc()
}

// ByMemberCode orders the results by the member_code field.
func ByMemberCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMemberCode, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByMonthlyLimitUsd orders the results by the monthly_limit_usd field.
func ByMonthlyLimitUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonthlyLimitUsd, opts...).ToFunc()
}

// ByRateLimit5h orders the results by the rate_limit_5h field.
func ByRateLimit5h(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRateLimit5h, opts...).ToFunc()
}

// ByRateLimit1d orders the results by the rate_limit_1d field.
func ByRateLimit1d(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRateLimit1d, opts...).ToFunc()
}

// ByRateLimit7d orders the results by the rate_limit_7d field.
func ByRateLimit7d(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRateLimit7d, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByRemovedAt orders the results by the removed_at field.
func ByRemovedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemovedAt, opts...).ToFunc()
}

// ByEnterpriseUserField orders the results by enterprise_user field.
func ByEnterpriseUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEnterpriseUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByAPIKeysCount orders the results by api_keys count.
func ByAPIKeysCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAPIKeysStep(), opts...)
	}
}

// ByAPIKeys orders the results by api_keys terms.
func ByAPIKeys(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAPIKeysStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUsageLogsCount orders the results by usage_logs count.
func ByUsageLogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUsageLogsStep(), opts...)
	}
}

// ByUsageLogs orders the results by usage_logs terms.
func ByUsageLogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsageLogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByGroupsCount orders the results by groups count.
func ByGroupsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGroupsStep(), opts...)
	}
}

// ByGroups orders the results by groups terms.
func ByGroups(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByBudgetPeriodsCount orders the results by budget_periods count.
func ByBudgetPeriodsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBudgetPeriodsStep(), opts...)
	}
}

// ByBudgetPeriods orders the results by budget_periods terms.
func ByBudgetPeriods(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBudgetPeriodsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByBudgetReservationsCount orders the results by budget_reservations count.
func ByBudgetReservationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBudgetReservationsStep(), opts...)
	}
}

// ByBudgetReservations orders the results by budget_reservations terms.
func ByBudgetReservations(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBudgetReservationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByBudgetEntriesCount orders the results by budget_entries count.
func ByBudgetEntriesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBudgetEntriesStep(), opts...)
	}
}

// ByBudgetEntries orders the results by budget_entries terms.
func ByBudgetEntries(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBudgetEntriesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEnterpriseMemberGroupBindingsCount orders the results by enterprise_member_group_bindings count.
func ByEnterpriseMemberGroupBindingsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEnterpriseMemberGroupBindingsStep(), opts...)
	}
}

// ByEnterpriseMemberGroupBindings orders the results by enterprise_member_group_bindings terms.
func ByEnterpriseMemberGroupBindings(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEnterpriseMemberGroupBindingsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newEnterpriseUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EnterpriseUserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EnterpriseUserTable, EnterpriseUserColumn),
	)
}
func newAPIKeysStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(APIKeysInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, APIKeysTable, APIKeysColumn),
	)
}
func newUsageLogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsageLogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UsageLogsTable, UsageLogsColumn),
	)
}
func newGroupsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, GroupsTable, GroupsPrimaryKey...),
	)
}
func newBudgetPeriodsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BudgetPeriodsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BudgetPeriodsTable, BudgetPeriodsColumn),
	)
}
func newBudgetReservationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BudgetReservationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BudgetReservationsTable, BudgetReservationsColumn),
	)
}
func newBudgetEntriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BudgetEntriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BudgetEntriesTable, BudgetEntriesColumn),
	)
}
func newEnterpriseMemberGroupBindingsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EnterpriseMemberGroupBindingsInverseTable, EnterpriseMemberGroupBindingsColumn),
		sqlgraph.Edge(sqlgraph.O2M, true, EnterpriseMemberGroupBindingsTable, EnterpriseMemberGroupBindingsColumn),
	)
}
