// Code generated by ent, DO NOT EDIT.

package enterprisememberbudgetentry

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldLTE(FieldID, id))
}

// MemberID applies equality check predicate on the "member_id" field. It's identical to MemberIDEQ.
func MemberID(v int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldEQ(FieldMemberID, v))
}

// PeriodStart applies equality check predicate on the "period_start" field. It's identical to PeriodStartEQ.
func PeriodStart(v time.Time) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldEQ(FieldPeriodStart, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldEQ(FieldKind, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldEQ(FieldRequestID, v))
}

// AmountUsd applies equality check predicate on the "amount_usd" field. It's identical to AmountUsdEQ.
func AmountUsd(v float64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldEQ(FieldAmountUsd, v))
}

// UsageLogID applies equality check predicate on the "usage_log_id" field. It's identical to UsageLogIDEQ.
func UsageLogID(v int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldEQ(FieldUsageLogID, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldEQ(FieldIdempotencyKey, v))
}

// ActorUserID applies equality check predicate on the "actor_user_id" field. It's identical to ActorUserIDEQ.
func ActorUserID(v int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldEQ(FieldActorUserID, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldEQ(FieldNote, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// MemberIDEQ applies the EQ predicate on the "member_id" field.
func MemberIDEQ(v int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldEQ(FieldMemberID, v))
}

// MemberIDNEQ applies the NEQ predicate on the "member_id" field.
func MemberIDNEQ(v int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldNEQ(FieldMemberID, v))
}

// MemberIDIn applies the In predicate on the "member_id" field.
func MemberIDIn(vs ...int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldIn(FieldMemberID, vs...))
}

// MemberIDNotIn applies the NotIn predicate on the "member_id" field.
func MemberIDNotIn(vs ...int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldNotIn(FieldMemberID, vs...))
}

// PeriodStartEQ applies the EQ predicate on the "period_start" field.
func PeriodStartEQ(v time.Time) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldEQ(FieldPeriodStart, v))
}

// PeriodStartNEQ applies the NEQ predicate on the "period_start" field.
func PeriodStartNEQ(v time.Time) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldNEQ(FieldPeriodStart, v))
}

// PeriodStartIn applies the In predicate on the "period_start" field.
func PeriodStartIn(vs ...time.Time) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldIn(FieldPeriodStart, vs...))
}

// PeriodStartNotIn applies the NotIn predicate on the "period_start" field.
func PeriodStartNotIn(vs ...time.Time) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldNotIn(FieldPeriodStart, vs...))
}

// PeriodStartGT applies the GT predicate on the "period_start" field.
func PeriodStartGT(v time.Time) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldGT(FieldPeriodStart, v))
}

// PeriodStartGTE applies the GTE predicate on the "period_start" field.
func PeriodStartGTE(v time.Time) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldGTE(FieldPeriodStart, v))
}

// PeriodStartLT applies the LT predicate on the "period_start" field.
func PeriodStartLT(v time.Time) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldLT(FieldPeriodStart, v))
}

// PeriodStartLTE applies the LTE predicate on the "period_start" field.
func PeriodStartLTE(v time.Time) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldLTE(FieldPeriodStart, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldContainsFold(FieldKind, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDIsNil applies the IsNil predicate on the "request_id" field.
func RequestIDIsNil() predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldIsNull(FieldRequestID))
}

// RequestIDNotNil applies the NotNil predicate on the "request_id" field.
func RequestIDNotNil() predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldNotNull(FieldRequestID))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldContainsFold(FieldRequestID, v))
}

// AmountUsdEQ applies the EQ predicate on the "amount_usd" field.
func AmountUsdEQ(v float64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldEQ(FieldAmountUsd, v))
}

// AmountUsdNEQ applies the NEQ predicate on the "amount_usd" field.
func AmountUsdNEQ(v float64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldNEQ(FieldAmountUsd, v))
}

// AmountUsdIn applies the In predicate on the "amount_usd" field.
func AmountUsdIn(vs ...float64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldIn(FieldAmountUsd, vs...))
}

// AmountUsdNotIn applies the NotIn predicate on the "amount_usd" field.
func AmountUsdNotIn(vs ...float64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldNotIn(FieldAmountUsd, vs...))
}

// AmountUsdGT applies the GT predicate on the "amount_usd" field.
func AmountUsdGT(v float64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldGT(FieldAmountUsd, v))
}

// AmountUsdGTE applies the GTE predicate on the "amount_usd" field.
func AmountUsdGTE(v float64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldGTE(FieldAmountUsd, v))
}

// AmountUsdLT applies the LT predicate on the "amount_usd" field.
func AmountUsdLT(v float64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldLT(FieldAmountUsd, v))
}

// AmountUsdLTE applies the LTE predicate on the "amount_usd" field.
func AmountUsdLTE(v float64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldLTE(FieldAmountUsd, v))
}

// UsageLogIDEQ applies the EQ predicate on the "usage_log_id" field.
func UsageLogIDEQ(v int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldEQ(FieldUsageLogID, v))
}

// UsageLogIDNEQ applies the NEQ predicate on the "usage_log_id" field.
func UsageLogIDNEQ(v int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldNEQ(FieldUsageLogID, v))
}

// UsageLogIDIn applies the In predicate on the "usage_log_id" field.
func UsageLogIDIn(vs ...int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldIn(FieldUsageLogID, vs...))
}

// UsageLogIDNotIn applies the NotIn predicate on the "usage_log_id" field.
func UsageLogIDNotIn(vs ...int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldNotIn(FieldUsageLogID, vs...))
}

// UsageLogIDGT applies the GT predicate on the "usage_log_id" field.
func UsageLogIDGT(v int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldGT(FieldUsageLogID, v))
}

// UsageLogIDGTE applies the GTE predicate on the "usage_log_id" field.
func UsageLogIDGTE(v int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldGTE(FieldUsageLogID, v))
}

// UsageLogIDLT applies the LT predicate on the "usage_log_id" field.
func UsageLogIDLT(v int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldLT(FieldUsageLogID, v))
}

// UsageLogIDLTE applies the LTE predicate on the "usage_log_id" field.
func UsageLogIDLTE(v int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldLTE(FieldUsageLogID, v))
}

// UsageLogIDIsNil applies the IsNil predicate on the "usage_log_id" field.
func UsageLogIDIsNil() predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldIsNull(FieldUsageLogID))
}

// UsageLogIDNotNil applies the NotNil predicate on the "usage_log_id" field.
func UsageLogIDNotNil() predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldNotNull(FieldUsageLogID))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// ActorUserIDEQ applies the EQ predicate on the "actor_user_id" field.
func ActorUserIDEQ(v int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldEQ(FieldActorUserID, v))
}

// ActorUserIDNEQ applies the NEQ predicate on the "actor_user_id" field.
func ActorUserIDNEQ(v int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldNEQ(FieldActorUserID, v))
}

// ActorUserIDIn applies the In predicate on the "actor_user_id" field.
func ActorUserIDIn(vs ...int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldIn(FieldActorUserID, vs...))
}

// ActorUserIDNotIn applies the NotIn predicate on the "actor_user_id" field.
func ActorUserIDNotIn(vs ...int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldNotIn(FieldActorUserID, vs...))
}

// ActorUserIDGT applies the GT predicate on the "actor_user_id" field.
func ActorUserIDGT(v int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldGT(FieldActorUserID, v))
}

// ActorUserIDGTE applies the GTE predicate on the "actor_user_id" field.
func ActorUserIDGTE(v int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldGTE(FieldActorUserID, v))
}

// ActorUserIDLT applies the LT predicate on the "actor_user_id" field.
func ActorUserIDLT(v int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldLT(FieldActorUserID, v))
}

// ActorUserIDLTE applies the LTE predicate on the "actor_user_id" field.
func ActorUserIDLTE(v int64) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldLTE(FieldActorUserID, v))
}

// ActorUserIDIsNil applies the IsNil predicate on the "actor_user_id" field.
func ActorUserIDIsNil() predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldIsNull(FieldActorUserID))
}

// ActorUserIDNotNil applies the NotNil predicate on the "actor_user_id" field.
func ActorUserIDNotNil() predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldNotNull(FieldActorUserID))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldHasSuffix(FieldNote, v))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldContainsFold(FieldNote, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.FieldLTE(FieldCreatedAt, v))
}

// HasMember applies the HasEdge predicate on the "member" edge.
func HasMember() predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MemberTable, MemberColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMemberWith applies the HasEdge predicate on the "member" edge with a given conditions (other predicates).
func HasMemberWith(preds ...predicate.EnterpriseMember) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(func(s *sql.Selector) {
		step := newMemberStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EnterpriseMemberBudgetEntry) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EnterpriseMemberBudgetEntry) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EnterpriseMemberBudgetEntry) predicate.EnterpriseMemberBudgetEntry {
	return predicate.EnterpriseMemberBudgetEntry(sql.NotPredicates(p))
}
